### ISSUE TITLE
[Feature]: Add Optimism Kovan to the supported chains

### ISSUE THREAD

**Issue by leovct** [blocknative/web3-onboard#1006]
## Feature Description

I noticed that **Optimism Kovan** is not in the list of supported chains by web3-onboard. Is this something you plan to add to the library? If yes, is it easy to implement? I could do it but I'm not familiar with the source code and I would like to know if it is feasible by a noob like me! :)

Here's the list of supported chains (defined [here](https://github.com/blocknative/web3-onboard/blob/7066f29e7832cfac7981f10a450c6d6f0275d90e/packages/core/src/utils.ts#L68)):
```js
export const chainIdToLabel: Record<string, string> = {
  '0x1': 'Ethereum',
  '0x3': 'Ropsten',
  '0x4': 'Rinkeby',
  '0x5': 'Goerli',
  '0x2a': 'Kovan',
  '0x38': 'Binance',
  '0x89': 'Polygon',
  '0xfa': 'Fantom',
  '0xa': 'Optimism',
  '0xa86a': 'Avalanche',
  '0xa4ec': 'Celo',
  '0x64': 'Gnosis',
  '0x63564C40': 'Harmony One',
  '0xa4b1': 'Arbitrum'
}
```

**Comment by techgangboss** [comment]
This is already supported - do you need an example on how to do it? @leovct

**Comment by leovct** [comment]
Yeah sure!

**Comment by taylorjdawson** [comment]
```js
import Onboard from '@web3-onboard/core'
import injectedModule from '@web3-onboard/injected-wallets'

const MAINNET_RPC_URL = 'https://mainnet.infura.io/v3/<INFURA_KEY>'

const injected = injectedModule()

const onboard = Onboard({
  wallets: [injected],
  chains: [
    {
      id: '0x45',
      token: 'ETH',
      label: 'Optimism Kovan',
      rpcUrl: 'https://kovan.optimism.io'
    }
  ],
  appMetadata: {
    name: 'My App',
    icon: '<SVG_ICON_STRING>',
    description: 'My app using Onboard'
  }
})

const wallets = await onboard.connectWallet()

console.log(wallets)
```

@leovct Here's an example of using **Optimism Kovan** 👍🏾

**Comment by taylorjdawson** [comment]
Closing for now -- please feel free to reach out on [discord](https://discord.gg/THH2QNgBYn) if you have any further issues 🙂
