### ISSUE TITLE
[Feature]: Customize modal background color

### ISSUE THREAD

**Issue by greynguyen** [blocknative/web3-onboard#1013]
### Feature Description

Would love a way to customize the background color of this modal via CSS variable (https://share.cleanshot.com/SYiSIk).

**Comment by Adamj1232** [comment]
Hey @greynguyen I have a update for this in staging and should be release today to a new version of core/react package. The variable will be `--onboard-action-required-modal-background` with fallbacks on `--onboard-white` and `--white` if you are wanting to use global Onboard theming

**Comment by greynguyen** [comment]
Perfect! Thank you.

**Comment by Adamj1232** [comment]
Updated in latest release!
