### ISSUE TITLE
Dismiss a wallet

### ISSUE THREAD

**Issue by quangas** [blocknative/web3-onboard#1017]
We're in the process of creating a new wallet sdk for blocknative, however there is no documentation on dismissing the wallet after selecting a wallet. 

When you click the X icon to close/dismiss, what event needs to be returned in order for it to "try again" and remove the UI?

What event does the connection look for stop it from connecting?

_Connecting...
Make sure to select all accounts that you want to grant access to._

**Comment by aaronbarnardsound** [comment]
When the wallet is selected, Onboard will then make a `eth_requestAccounts` RPC method call which will either resolve with an array of account addresses or reject with an error. If it rejects with an error, then that is when the "try again" UI is shown.
