### ISSUE TITLE
Outdated Wallet Link Code --> Needs to be updated to Coinbase Wallet SDK

### ISSUE THREAD

**Issue by FreddyMJ3** [blocknative/web3-onboard#1018]
Hi,

I work on the DevRel team at Coinbase and am submitting this issue to inform you that the WalletLink SDK has been deprecated in favor of our new [Coinbase Wallet SDK](https://github.com/coinbase/coinbase-wallet-sdk) You can find more on that and how to upgrade to the latest version [here](https://docs.cloud.coinbase.com/wallet-sdk/docs/welcome).

Please let me know if you have any questions!

Thanks,
Freddy

**Comment by Adamj1232** [comment]
Hi @FreddyMJ3 we have the WalletLink package [marked as deprecated](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/packages/walletlink#deprecated-wallet-module-for-connecting-walletlink-to-web3-onboard) and have a [Coinbase SDK package](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/packages/coinbase) available and live.
