### ISSUE TITLE
[Bug]: v2.2.9 breaks NextJS apps

### ISSUE THREAD

**Issue by cmalex23** [blocknative/web3-onboard#1026]
### Current Behavior

The `const APP_INITIAL_STATE' is accessing the `window` object before it being initialized in a NextJS app and so it throws.

### Expected Behavior

The `const APP_INITIAL_STATE` could have this code instead
`wallets: [],
    walletModules: [],
    chains: [],
    accountCenter: {
        enabled: true,
        position: 'topRight',
        expanded: false,
        minimal: typeof window != 'undefined' && getDevice().type === 'mobile'
    },
    locale: ''`

### Onboard Version

2.2.9

### Node Version

next^12.1.6

**Comment by enzoferey** [comment]
This has been previously covered at https://github.com/blocknative/web3-onboard/pull/931, but I'm facing the same issue too. You can't just import the module and run it on a Next.js context.

The line causing the issue:

https://github.com/blocknative/web3-onboard/blob/09df2e1a8ddeb5100566db78f57b1b88bf406cd5/packages/core/src/utils.ts#L29

**Comment by s-pcode** [comment]
@aaronbarnardsound @taylorjdawson any update? This is a breaking change for me, so pls this needs to be resolved.

**Comment by aaronbarnardsound** [comment]
Will be taking a look at this today :)
