### ISSUE TITLE
[Feature]: Add metamask option in the wallet list even if it is not installed 

### ISSUE THREAD

**Issue by deepak-quo** [blocknative/web3-onboard#1027]
### Is your request related to a problem?

Metamask is the most popular crypto-wallet but it is only visible in the modal if is installed. We should give an option to add the metamask and redirect to metamask website if not present in the user system.

**Comment by techgangboss** [comment]
Is there a reason you want to give this option to users other than a wallet being popular? This existed in previous versions and we removed it as having wallets that you can't use created confusion for users. We are exploring "cant find your wallet?" and "need a wallet?" user paths that will solve for those use cases.

**Comment by techgangboss** [comment]
@deepak-quo please let us know, we will close the issue next week if no reply or comment is received
