### ISSUE TITLE
[Feature]: Clicking address copies address to clipboard

### ISSUE THREAD

**Issue by taylorjdawson** [blocknative/web3-onboard#1028]
### Feature Description

In the account UI center it would be nice to copy the address to the clipboard when clicking it.

### Anything else?

<img width="309" alt="image" src="https://user-images.githubusercontent.com/29665732/171058662-aeb36327-20a2-4e30-a1ea-5a833bb80c4a.png">

**Comment by Adamj1232** [comment]
Currently in development by @mahmud-bn ! 🚀
