### ISSUE TITLE
[Bug]: connectWallet  with autoSelect  and disableModal doesn't works if call it more than one time

### ISSUE THREAD

**Issue by applicature-dlitvinov** [blocknative/web3-onboard#1032]
### Current Behavior

For example, developers don't want to use a native modal for the connection wallets.
For example needs to connect only with WalletConnect after clicking on the **Connect** button, without any modals.
You will use the following code after the **Connect** button is clicked:
```
onboard.connectWallet({
  autoSelect: {
    label: 'WalletConnect',
    disableModals: true
  }
})
```
When the user clicks on the **Connect** button the first time the WalletConnect modal with QR code opens, so it works as expected.
If the user clicks on the close button and clicks on the **Connect** button again, nothing happens.

Look at the video:
https://user-images.githubusercontent.com/101503007/171252895-405d42fb-c529-4f81-8066-43bcb2b66830.mov

### Expected Behavior

When the user clicks on the **Connect** button the second time if the previous time connection was canceled, the WalletConnect modal with QR code should be opened.

### Onboard Version

2.2.9

### Node Version

16.15.0

**Comment by Adamj1232** [comment]
@applicature-dlitvinov thank you for this submission! I reviewed today, left PR comments

**Comment by Adamj1232** [comment]
This has been merged into staging for testing and should be released shortly!
