### ISSUE TITLE
[Bug]: Type Error: Cannot assign to "AirGappedKeyring" because it is a constant

### ISSUE THREAD

**Issue by taylorjdawson** [blocknative/web3-onboard#1040]
### Onboard Version

v2

### Node Version

16

### Anything else?

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/29665732/172023624-60569ae6-3fe4-429a-8a33-897c1a50b43b.png">

**Comment by aaronbarnardsound** [comment]
Closed via #1047
