### ISSUE TITLE
[Bug]: MEW module cannot change network on desktop and cannot connect on mobile

### ISSUE THREAD

**Issue by DawidFulmes** [blocknative/web3-onboard#1044]
### Current Behavior

I have application with web3-onboard setup that is working perfect for injected wallets, coinbase and walletconnect. As they are working, I assume that my configuration of `Onboard` object is fine.

Then I wanted to add MEW module via just adding next wallet in array like here https://docs.blocknative.com/onboard/mew-my-ether-wallet. What issues I've got:

Issue 1: After chosing MEW in connect modal, I can scan the QR code with my mobile MEW wallet app and application connect perfectly, There is no option to pick network in mobile application after connection. When I am trying to change network with `setChain` method (which is working for other wallets that i have in wallets array) nothing happened and I see only `400 error on POST to rpcUrl` in console.

Issue 2: When I am trying to enter hosted application through MEW wallet mobile app and their dapp browser, and I pick MEW method in modal, mobile app is asking for picking one of wallets, but then onboard modal is still in `connecting` state. Also what is interesting, in this embeded mode, modal detects Trust wallet available. After chosing it, bahavior is the same (connecting state never ends).

### Expected Behavior

Issue 1: Since MEW mobile app doesn't allow to change network in UI after connection, it would be perfect to change network via `setChain`.

Issue2: On mobile connection also should be working - it can be connected to Trust as it detects it in this mode.

### Steps To Reproduce

Issue1:
1. Add mew module to working setup like here https://docs.blocknative.com/onboard/react-hooks
2. Connect MEW mobile wallet throught qr scanning
3. Try to trigger `setChain` method

Issue2:
1. Enter MEW mobile wallet
2. Enter `dapp browser` there
3. Pick an url of app that have added mew module 
4. Pick MEW and if you have more than 1 wallet in MEW app (chose proper one).

### Onboard Version

@web3-onboard/mew - 2.0.0

### Node Version

16.10.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

I was trying to change rpcUrl in config to wss, but other wallets were throwing errors, even if MEW was not raising `POST 400`, but still nothing happened on `setChain`.

**Comment by taylorjdawson** [comment]
@DawidFulmes Thanks for opening this issue, cross-linking [discord thread](https://discord.com/channels/542403978693050389/542406313347514388/981125531510644756) for visibility and context.

**Comment by aaronbarnardsound** [comment]
@DawidFulmes 

1. MEW only supports mainnet connections, so that is why the switch chain call is failing. We could make a change so that calls to switch chain throw an error without trying on the provider.

2. The MEW connect module does not work when accessing from within the MEW browser. I would expect it to work like the Coinbase SDK does, ie if the sdk detects it's own injected provider, it should connect to it, otherwise show the connect QR code. It might be worth creating an issue on the [Mew Connect repo](https://github.com/MyEtherWallet/MEWconnect-web-client).

**Comment by aaronbarnardsound** [comment]
@DawidFulmes 
Yeah their provider does not seem to support the `wallet_switchEthereumChain` method which the `onboard.setChain` method uses under the hood. I will get an update out that indicates that those methods are not supported.

**Comment by DawidFulmes** [comment]
@aaronbarnardsound Hmm, but setChain works when I am trying to setChain from MEW browser. So probably, null should be provided only on desktop, what do you think about it?
