### ISSUE TITLE
[Feature]: Follow and update keepkeyoss/hd-wallet-webusb dependency

### ISSUE THREAD

**Issue by arosboro** [blocknative/web3-onboard#1054]
### Is your request related to a problem?

npm audit when using `@web3-onboard/keepkey` generates 13 security vulnerability warnings.

These warnings are due to an unnecessary dependency, and it is in the process of being made optional by @mrnerdhair of the KeepKey workstream participating in the ShapeShift DAO through this PR.  https://github.com/shapeshift/hdwallet/pull/538

### Feature Description

The upstream pull request will make an unmaintained SDK dependency, `bnb-javascript-sdk-nobroadcast`, optional allowing onboard users of the KeepKey integration to squelch dependency bot security audit warnings in GitHub about their projects.

### Alternative Solutions

I found you can add these packages to peg dependencies in your "overrides"
```
...
"dependencies": {
    ...
},
"overrides": {
    "@cosmjs/amino": "0.28.4",
    "@cosmjs/encoding": "0.28.4",
    "@cosmjs/math": "0.28.4",
    "@cosmjs/proto-signing": "0.28.4",
    "@cosmjs/stream": "0.28.4",
    "@cosmjs/tendermint-rpc": "0.28.4",
    "@cosmjs/utils": "0.28.4",
    "axios": "0.27.2",
    "marked": "4.0.10",
    "minimist": "1.2.6",
    "mkdirp": "1.0.4",
    "typedoc": "0.22.17",
    "protobufjs": "6.11.3",
    "web3": "1.7.3"
  },
  ...
```
### Anything else?

This is just a friendly heads-up asking the maintainers to kindly consider updating the relevant dependencies when https://github.com/shapeshift/hdwallet/pull/538 is eventually merged.

**Comment by techgangboss** [comment]
Thanks we'll keep an eye out!

**Comment by arosboro** [comment]
@techgangboss, I added a workaround. I got some audit messages resolved using overrides in case anyone else faces a similar issue.

**Comment by arosboro** [comment]
For anyone having something related to this, you should use the process of making "overrides" while not necessarily copying the exact overrides shown in the description.  Use `npm list` (it is your friend for exploring the dependency tree), and study the `npm audit` log until you better understand which packages come with CVE warnings.  The output will also show which packages in dependencies are causing those child dependencies to install at vulnerable versions.
