### ISSUE TITLE
[Feature]: Hide the "powered by Blocknative"

### ISSUE THREAD

**Issue by pauldemarco** [blocknative/web3-onboard#1058]
Is it legal and possible to hide this "powered by Blocknative" logo?

![image](https://user-images.githubusercontent.com/16725750/173293620-a8fa4eef-c175-4374-8e17-76cba3171d6e.png)

**Comment by techgangboss** [comment]
Hey @pauldemarco , it's okay to do this as web3-onboard is open source and MIT licensed, however we appreciate that our integrators show blocknative some love if they gain value from our efforts. If it's a requirement for your project, you can always fork the repo and remove it, or add the option yourself and do a PR for us to evaluate.
