### ISSUE TITLE
[Feature]: Pre-selection of network on WalletConnect session request

### ISSUE THREAD

**Issue by tfalencar** [blocknative/web3-onboard#1076]
### Is your request related to a problem?

With WalletConnect the Dapp tells the wallet which network to connect to on establishing the connection. 

Currently, when onboard library is configured, even if chainId of 1 is not even specified, a walletconnect session request is sent with chainId of '1' (Ethereum mainnet) instead of whatever is specified in the "chains" array. The problem with this approach is that then yet another request needs to be sent for the user to authorise "switching networks", which is quite bad UX. Modern / good mobile wallets allows simultaneous connections of different dapps to multiple networks at the same time, by keeping track of which dapp is connected to which chainId. The widespread "metamask standard" is bad even for browsers: imagine having 5 dapps in 5 tabs, and having to switch networks every-time a tab in the browser is switched - makes no sense at all, so it is good that walletconnect doesn't follow the metamask approach and we should allow this.

### Feature Description

As a user from the onboard library, I'd like to specify the networks my dapp supports like this:

const onboard = Onboard({
  wallets: [walletConnect],
  chains: [
    {
      id: '0xA',
      token: 'ETH',
      label: 'Optimism',
      rpcUrl: '....'
    }
    ]}
});

And have the walletconnect session request dialog on the mobile wallet side (iOS or Android) to already make the request to connect to the proper network. One solution for when there is support for multiple networks, is for Onboard to send the walletconnect session request with the first item in the array, as the "default" network for the request.

### Alternative Solutions

Here's another dapp describing a similar issue: https://github.com/gnosis/cowswap/issues/1973 

### Anything else?

Screenshot of the desired result on the mobile wallet side (as example, rainbow wallet was used):
<img width="421" alt="Screenshot 2022-06-17 at 15 27 48" src="https://user-images.githubusercontent.com/4054009/174437714-658d5d07-8250-467d-bf59-c07e6c529f95.png">

**Comment by aaronbarnardsound** [comment]
Just did some digging in to this and I believe that we can set a `chainId` when connecting the session by changing [this line here](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/src/index.ts#L132) to : `this.connector.createSession({chainId: parseInt(chains[0].id, 16)})` and that would connect to the first chain in the `chains` array passed in on init. We will need to check what WalletConnect does on that call if the chain is not supported by the wallet and handle that accordingly.

**Comment by tfalencar** [comment]
I'm doing a bit of guessing here, but I think what happens if the wallet doesn't support said network will be wallet-specific. What I would do is inform the user about this and potentially reject the connection from the wallet side.

**Comment by aaronbarnardsound** [comment]
Yeah that would make sense. We'll let you know once we have some progress on this.

**Comment by mahmud-bn** [comment]
@tfalencar 
Thanks for bringing this up. The associated PR has been merged and released with the latest version of @web3-onboard/walletconnect - 2.0.4

**Comment by ArshiaDhiman** [comment]
Thanks, just thought I would specify that I am using @web3-onboard/react. 
I still get a message on the screen asking to switch networks without walletconnect connecting to the specified chain.
Thanks a lot 😃 
This is the versions I'm using
`"@web3-onboard/gnosis": "^2.0.5",
        "@web3-onboard/injected-wallets": "^2.0.7",
        "@web3-onboard/ledger": "^2.1.4",
        "@web3-onboard/react": "^2.1.7",
        "@web3-onboard/walletconnect": "^2.0.5"`

**Comment by ArshiaDhiman** [comment]
Yeah sure @mahmud-bn. I'm using next.js and this is my web3-onboard setup:
 
`
const injected = injectedModule();
const ledger = ledgerModule();
const wallet_connect = walletConnectModule({ connectFirstChainId: true });
const gnosis = gnosisModule();

export const NETWORK = NETWORKS[CHAIN_ID];

const web3onboard = init({
    wallets: [injected, ledger, wallet_connect, gnosis],
    chains: [
        {
            id: "0x" + CHAIN_ID.toString(16),
            token: NETWORK.symbol,
            label: NETWORK.network_name,
            rpcUrl: getRPCUrl(),
        },
    ],
    appMetadata: {
        name: `...`,
        icon: ONBOARD_LOGO || LOGO,
        description: `...`,
    },
    accountCenter: {
        desktop: { enabled: false },
        mobile: { enabled: false },
    },
});`

The wallet modal is working fine, just when a user tries to connect their wallet using walletconnect it does not send the preferred chain with the request it just prompts the user to change network manually. Usually the user then has to end the session and reconnect their wallet to change chain on the mobile app.
