### ISSUE TITLE
[Feature]: Adding z-index to the Account-Center 

### ISSUE THREAD

**Issue by sgurmani** [blocknative/web3-onboard#1080]
### Feature Description

For many valid reason , the account-center should be configurable and styling the main container should be possible. Where ever it is used, it is not supposed to be on the z-index:0 but rather your already existing application should have be able to support it. For that as much configuration on the top level of the account center should be possible.

**Comment by aaronbarnardsound** [comment]
Yes we do need to add this. Thanks for creating the issue. We'll try and get this sorted this week.

**Comment by Adamj1232** [comment]
Thank you again for the comment! Closing as this is available with latest releases - https://github.com/blocknative/web3-onboard/releases/tag/web3-onboard%2F2.2.0

**Comment by sgurmani** [comment]
@Adamj1232 Thank you the change. Can you please tell me how to change the z-index of the account-center. I have pulled the latest version and passed the   --account-center-z-index: 1600; in the css file but it is not taking an effect.

**Comment by Adamj1232** [comment]
@mahmud-bn can you take a look?

**Comment by mahmud-bn** [comment]
Hi @sgurmani, as explained in [our docs](https://docs.blocknative.com/onboard/core#custom-styling), you have to add account-center custom styling CSS variables to the :root in your CSS file 

For example, 
```
:root {
  --account-center-z-index: 1600
}
```
will implement your desired effect.
