### ISSUE TITLE
[Feature]: Allow defining the container element

### ISSUE THREAD

**Issue by moein** [blocknative/web3-onboard#1094]
### Is your request related to a problem?

Our application has a boxed layout which means in bigger screens the corners are out of our main container. Since the onboard-v2 element is being appended to the document it's hard to control where it appears in a boxed layout application

### Feature Description

Allow passing an optional query selector element in the init options which then is used to append onboard-v2 element to it.

### Alternative Solutions

We can calculate the right position based on the max width and screen size we have but this approach has 2 downsides:
1. It's ugly and not developer friendly
2. The screen size change requires js to update the position

### Anything else?

I would like to contribute to this great library if possible as this feature doesn't look that complicated and doesn't cause any breaking change.

**Comment by moein** [comment]
Hi @techgangboss 
Is there a contribution doc? If not I will just do the PR then you can guide me with missing details :D

**Comment by Adamj1232** [comment]
@moein there are some notes on your PR and a merge conflict. We can start moving on it as soon as those are resolved.

**Comment by Adamj1232** [comment]
@moein friendly ping to get your PR through if still needed
