### ISSUE TITLE
NextJS: TypeError: Cannot use 'in' operator to search for 'desktop' in undefined

### ISSUE THREAD

**Issue by thugzook** [blocknative/web3-onboard#1105]
Getting error `TypeError: Cannot use 'in' operator to search for 'desktop' in undefined` in web3-onboard-core v2.2.12. Prevents successful build or dev build.

Rolling back to v2.2.6 seems to fix this issue.

Npm 8.11.0
Nextjs 12.1.4
Node 16.15.0

**Comment by benjaminreid** [comment]
I ran into this today.

I think this `typeof` check is incorrect.

```js
    if (typeof notify !== undefined) {
        if ('desktop' in notify || 'mobile' in notify) {
```

Should be...

```js
if (typeof notify !== "undefined") {
```

As `typeof notify !== undefined` is `true` if is actually `undefined`.

**Comment by Adamj1232** [comment]
This fix will be released into pro later today or early tomorrow. Until then you can use of the latest alpha release should cover the cases. Thanks again for surfacing this!

**Comment by benjaminreid** [comment]
@Adamj1232 Great stuff, thanks for responding and getting the fix in quickly too 🙌

**Comment by thugzook** [comment]
@Adamj1232 thanks again! I thought I was going crazy. Cheers
