### ISSUE TITLE
[Bug]: Coinbase wallet switch network got stuck, "Allow" button grayed out.

### ISSUE THREAD

**Issue by lianqiang** [blocknative/web3-onboard#1111]
### Current Behavior

You can try our [app](https://hotfix-web3-onboard-mobile.d25sunzr70t45r.amplifyapp.com/#/dashboard) on **Coinbase Wallet's built-in browser**. You can click on the network button on the right of the top bar,

![image](https://user-images.githubusercontent.com/5622208/176497614-24b0a3ed-381b-4419-8601-16eecaccd9e5.png)

and select Celo or Meter network.

![image](https://user-images.githubusercontent.com/5622208/176497745-7d57cc0e-4b9a-44bc-9ed9-56fba6b41d4a.png)

This will call the network switch function of Coinbase Wallet, but the "Allow" button is grayed out. As shown below:

![image](https://user-images.githubusercontent.com/5622208/176496943-7ed3ddac-b886-4840-be49-33cce0748aff.png)

Not sure if this is due to our input params or Coinbase Wallet issue.

However if you added the new network in Coinbase Wallet's settings directly, then Switch Network will work without any problems.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.3.2-alpha.2

### Anything else?

Here are the version we are using in our project. We just updated with the newest version.

`"@web3-onboard/coinbase": "^2.0.7-alpha.1"`
`"@web3-onboard/core": "^2.3.2-alpha.2"`
`"@web3-onboard/injected-wallets": "^2.0.12-alpha.2"`
`"@web3-onboard/magic": "^2.0.7-alpha.1"`
`"@web3-onboard/walletconnect": "^2.0.5-alpha.1",`

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Interesting, but this does not occur when switching to BNB it seems. Do you see this with any other networks?

**Comment by Adamj1232** [comment]
What request are you calling to switch chains?
From the coinbase SDK docs:

> If Wallet SDK receives either a wallet_switchEthereumChain or wallet_addEthereumChain request for a [whitelisted network](https://docs.cloud.coinbase.com/wallet-sdk/docs/whitelisted-networks) then it switches the user to that network after asking approval from the user.

Coinbase Wallet clients handle wallet_addEthereumChain requests for non-whitelisted networks (for example, a network such as Harmony One which is not currently supported by clients by default).

A dapp can determine if a network is whitelisted or not by sending a wallet_switchEthereumChain request for that network. If error code 4092 is returned, then the network is not supported by default by the client wallet.

**Comment by lianqiang** [comment]
@Adamj1232 Thanks for the reply.

Yeah for not whitelisted networks, Coinbase Wallet will pop up a "Switch to unknown network" page. Since there is an "Allow" button on it, it seems it should support adding new networks, pretty much like how other wallets function.

**Comment by lianqiang** [comment]
> Interesting, but this does not occur when switching to BNB it seems. Do you see this with any other networks?

For us, just Celo & Meter.io, but I suppose maybe for all non-whitelisted networks, it will be the same.

**Comment by Adamj1232** [comment]
Going to close this issue as it looks like a separate request must be called for non-whitelisted chains

**Comment by lianqiang** [comment]
Hi @Adamj1232 I am actually calling onboard.setChain to switch chains. I do not think we have an addChain function in our library, right?

**Comment by Adamj1232** [comment]
@lianqiang ahhh you are using the React Hooks? Gotcha, in that case we don't have hooks released to wrap that request yet so you would have to send it as 
```typescript
export interface EIP3085Request {
  method: 'wallet_addEthereumChain'
  params: AddChainParams[]
}

export type AddChainParams = {
  chainId: ChainId
  chainName?: string
  nativeCurrency: {
    name?: string
    symbol?: string
    decimals: number
  }
  rpcUrls: string[]
}
```
```javascript
  const addEthChain = async (provider) => {
    const chainRequest = await provider.request({
      method: 'wallet_addEthereumChain',
      params: [...chainParams]
    })

    console.log(chainRequest)
  }
```

**Comment by lianqiang** [comment]
@Adamj1232 thanks so much! Will dive into it.

**Comment by lianqiang** [comment]
@Adamj1232 we found where the issue is caused. 

If the field `blockExplorerUrls` is empty, then Coinbase Wallet will not add that new network, greying out the "Allow" button as shown above.

**Comment by Adamj1232** [comment]
Interesting, I will make sure to add a note around this to the docs
