### ISSUE TITLE
[Feature]: Bump web3-onboard v1 version

### ISSUE THREAD

**Issue by chendatony31** [blocknative/web3-onboard#1122]
### Is your request related to a problem?

https://github.com/blocknative/web3-onboard/pull/1053

### Feature Description

Could you pls bump the version of v1 branch?  Some projects are waiting for the change  https://github.com/blocknative/web3-onboard/pull/1053

thanks

**Comment by Adamj1232** [comment]
@chendatony31 I will get that updated today, thanks for reporting the issue

**Comment by Adamj1232** [comment]
This has been fixed with the latest onboard version release completed this afternoon with your target being `1.38.4`
Thank you for letting us know!

**Comment by chendatony31** [comment]
Thank you @Adamj1232
