### ISSUE TITLE
[Feature]: Add Avalanche Core Wallet Support

### ISSUE THREAD

**Issue by DocBadTouch** [blocknative/web3-onboard#1152]
### Is your request related to a problem?

No

### Feature Description

Please add support for Avalanche Core Wallet as an injected wallet. This wallet is incredible powerful and supporting it would be very helpful. 

### Alternative Solutions

Here is and example of implementation using web3-react: https://github.com/ava-labs/avalanche-dapp-sdks/tree/alpha-release/packages/avalanche-connector-example

### Anything else?

Additional resources:
This has the link to the repo and a link to svgs for the icons
https://support.avax.network/en/articles/6303769-how-to-integrate-core-into-a-website

SVGs: 
![Core Owl Black bg](https://user-images.githubusercontent.com/36558871/179652689-0d196d1f-bac7-4d9b-9661-0929f2fafed9.svg)
![Core Owl White](https://user-images.githubusercontent.com/36558871/179652690-08138835-690d-4300-8479-43d8d7c59fe4.svg)

**Comment by mahmud-bn** [comment]
Thanks, @DocBadTouch for creating the feature request. The team will deliberate on that and get back to you. 
In the meantime, have you considered creating a PR to add Add Avalanche Core Wallet as an injected wallet as that would make the process faster?
Here are examples of similar community injected wallet PRs: #1127 and #1073

**Comment by itsmnthn** [comment]
Created PR to add support for core wallet #1160

**Comment by Adamj1232** [comment]
@itsmnthn we have reached out to AvaLabs to get the issues with the wallet provider resolved

**Comment by Adamj1232** [comment]
Closing as Core wallet support has been merged with #1259 and is available with [injected-wallet package version 2.2.2-alpha.1 ](https://www.npmjs.com/package/@web3-onboard/injected-wallets/v/2.2.2-alpha.1)
