### ISSUE TITLE
[Bug]: await connectWallet with autoSelect and disableModals will stuck forever if the injected provider is not found

### ISSUE THREAD

**Issue by mayone** [blocknative/web3-onboard#1153]
### Current Behavior

Using `await onboard.connectWallet()` with `autoSelect` and `disableModals` seems to be the only way to connect all the previously connected wallets.
I followed the instruction here https://docs.blocknative.com/onboard/core#auto-selecting-a-wallet

```typescript
for (const walletLabel of prevConnectedWallets.reverse()) {
    await onboard.connectWallet({
        autoSelect: {
            label: walletLabel,
            disableModals: true,
        },
    });
}
```
But if one of the wallet extension is closed or crashed, the `autoSelect` will fail (to look up for the injected provider) and the `connectWallet` will stuck there without returning anything (since `disableModals`)

### Expected Behavior

The `await connectWallet` with `autoSelect` and `disableModals` should return when the auto select failed (maybe injected provider not found) instead of hanging there.
Since the modal is disabled, the behavior should be different in my opinion.

### Easy way to reproduce
- Connect to a none existed wallet
- Instead of returning error, it will stuck there

```typescript
await onboard.connectWallet({
    autoSelect: {
        label: 'Wallet not found',
        disableModals: true,
    },
 });
```

### Practical case
- Connect to a closed wallet extension
- Instead of returning error, it will stuck there

```typescript
await onboard.connectWallet({
    autoSelect: {
        label: 'MetaMask',
        disableModals: true,
    },
 });
```

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.5.0

### Node Version

18.6.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @mayone, thanks for reporting, I will take a look at this today.
