### ISSUE TITLE
[Feature]: Add i18n conf in documention

### ISSUE THREAD

**Issue by zed-wong** [blocknative/web3-onboard#1163]
### Is your request related to a problem?

There's no i18n format in the official documentation. It cost me a while to finally find the format. It's located in `packages/core/src/i18n/en.json`. I supposed it should better be in the documentation. So other developers don't have to find it from the source code.

### Feature Description

Add an `i18n format` page in the offcial documentaion.

### Alternative Solutions

mention this file `https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/core/src/i18n/en.json`

**Comment by mahmud-bn** [comment]
Hi @zed-wong 

Thanks for bringing this up.

We do have existing documentation on the available i18n format: https://docs.blocknative.com/onboard/core#options that links to the format file - I noticed that the link becomes inaccessible after reloading so I've linked to the folder instead with extra guidance. 

This is to keep our documentation clutter-free.
