### ISSUE TITLE
[Bug]: Bump vue-demi to ^13.x.x to support Vue 2.7

### ISSUE THREAD

**Issue by ihorbond** [blocknative/web3-onboard#1167]
### Current Behavior

I'm using Nuxt 2 with Vue 2.7 to get composition API out of the box. Project breaks after installing web3-onboard/vue cause it installs vue-demi ^12.5 as dependency which tries to import from @vue/composition-api instead of just @vue.

### Expected Behavior

Projects using Vue 2.7 don't break.

### Steps To Reproduce

Install web3-onboard/vue into a project that depends on vue 2.7 and run the project.

### What package is effected by this issue?

@web3-onboard/vue

### Is this a build or a runtime issue?

Build

### Package Version

latest

### Node Version

"@web3-onboard/vue": "^2.1.4"

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
These dependencies were not found:                                                     
* @vue/composition-api in ./node_modules/vue-demi/lib/index.cjs                                                              friendly-errors 13:15:09  
* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs    
```
```


### Anything else?

_No response_

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@ihorbond  Thank you for the feedback through this issue, we will look into adding this shortly. We will update here as soon as we have a fix out.

**Comment by aaronbarnardsound** [comment]
@taylorjdawson Did this get fixed when you were working on your Vue 2 example?

**Comment by taylorjdawson** [comment]
Yes! @ihorbond Please refer to our [vuejs-v2](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/examples/with-vuejs-v2) example and let me know if the configuration there solves your issues

**Comment by ihorbond** [comment]
> Yes! @ihorbond Please refer to our [vuejs-v2](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/examples/with-vuejs-v2) example and let me know if the configuration there solves your issues

Your example depends on vue v2.16.2

**Comment by Adamj1232** [comment]
@ihorbond is this issue still persisting? It looks like the example repo has a `^` within the vue versions so it should resolve to the latest minor version including 2.7.x

**Comment by ihorbond** [comment]
> @ihorbond is this issue still persisting? It looks like the example repo has a `^` within the vue versions so it should resolve to the latest minor version including 2.7.x

Im not sure tbh, I found the workaround at that time and never looked back haha

**Comment by Adamj1232** [comment]
Great to hear! I will close this issue for now with the example shared by @taylorjdawson above
