### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by dweng0** [blocknative/web3-onboard#1173]
### Is your request related to a problem?

We are currently experiencing an issue on Android phones where users on Android can't see the MetaMask icon and have to connect via a different mechanism (wallet connect). 
However users on iPhone are able to see the MetaMask icon and can click it and get to the native MetaMask application from there.

### Feature Description

I can see that in the [documentation ](https://docs.blocknative.com/onboard/injected-wallets#injected-wallets-supported-natively) it specifies that MetaMask is only available via walletconnect, however because it's working on iPhone I wasn't sure if this is the case. Could we get clarity on MetaMask support for Android. 

### Alternative Solutions

In the interim, is there a recommended workaround? For example a custom injected wallet that points to MetaMask so that Android users get the same experience as iPhone users.

### Anything else?

Pictures:
This is Iphone:
![image](https://user-images.githubusercontent.com/5268627/181262831-8dd9b5c7-96ac-4e16-83cf-85b11884092c.png)

This is Android:
![image](https://user-images.githubusercontent.com/5268627/181262987-9b1cd1e8-8bfd-4d45-9cca-aabab95a1269.png)

**Comment by Adamj1232** [comment]
@dweng0 is this issue arising when selecting a wallet through the MetaMask application on Android?
Can you provide detailed reproduction steps(apps/browsers used on android)?

**Comment by Adamj1232** [comment]
From testing we are able to see the MM option within the MM application on Android. 
Are you expecting to see MM outside of the MM application? 
If so only wallets whose providers are injected on the current browser will be shown on all devices(iOS, Android, desktop)
![image](https://user-images.githubusercontent.com/24457880/181377332-dc1baddc-41df-4c7f-960a-7f0ad9592e6b.png)

**Comment by olivermehr** [comment]
@Adamj1232 So when we go to our application from within the metamask wallet browser we are not seeing an option to connect to the metamask wallet when using an Android. 

Is this an issue you are aware of others having? Perhaps a config we need to set?

**Comment by Adamj1232** [comment]
@olivermehr hmm interesting. The image above I sent was our ReactDemo from within the MetaMask app/browser.
Can you try visiting https://reactdemo.blocknative.com/ from within your MetaMask application browser to see if you can see the option there? If you are able to there might be a config misalign, if this is the case can you shoot over your config for onboard or a link to your repo?

**Comment by dweng0** [comment]
> @olivermehr hmm interesting. The image above I sent was our ReactDemo from within the MetaMask app/browser. Can you try visiting https://reactdemo.blocknative.com/ from within your MetaMask application browser to see if you can see the option there? If you are able to there might be a config misalign, if this is the case can you shoot over your config for onboard or a link to your repo?

Hey Adam, thanks for reaching out, 

I can confirm I am able to see MM when using metamask browser and going to the react demo you linked. 

I'll have a poke about in the react demo source code and see if we are potentially missing anything. its the react demo source code available on Github?

Thanks for taking the time to reach out to us about this.

Jay
