### ISSUE TITLE
[Bug]: No migration guide to go from bnc-onboard to web3-onboard

### ISSUE THREAD

**Issue by doliG** [blocknative/web3-onboard#1178]
### Current Behavior

I'm trying to migrate our bnc-onboard (1.35.4) to @web3-onboard/core (2.5.0) but I don't know if there's a migration guide available, and I can't find it on github nor on the doc

### Expected Behavior

A guide is available to explain the major !== between `bnc-onboard` && `@web3-onboard` and help devs to migrate

### What package is effected by this issue?

bnc-onboard (v1)

### Is this a build or a runtime issue?

N/A

### Package Version

1.35.4

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by techgangboss** [comment]
Thanks for pointing this out, we'll add one shortly!

**Comment by techgangboss** [comment]
Hey we've added https://docs.blocknative.com/onboard/migration-guide, please take a look and let us know your impressions / what else you would like to see. We'll close this issue in 1 week if we don't hear from you @doliG @mahmud-bn
