### ISSUE TITLE
[Bug]: How do you build the code?

### ISSUE THREAD

**Issue by sgehrman** [blocknative/web3-onboard#1181]
### Current Behavior

This code base is a mess.  Can't even build it.

$ yarn build
yarn run v1.22.19
$ yarn wsrun --stages build
$ /home/steve/Documents/GitHub/mavrik/web3-onboard/node_modules/.bin/wsrun --stages build
@web3-onboard/gas
$ tsc
@web3-onboard/common
$ rollup -c
 | 
 | src/index.ts → dist/...
 | (!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
 | created dist/ in 3.1s
@web3-onboard/injected-wallets
$ tsc
@web3-onboard/fortmatic
$ tsc
@web3-onboard/coinbase
$ tsc
@web3-onboard/keepkey
$ tsc
@web3-onboard/core
$ rollup -c
@web3-onboard/portis
$ tsc
@web3-onboard/gnosis
$ tsc
@web3-onboard/ledger
$ tsc
@web3-onboard/trezor
$ tsc
@web3-onboard/keystone
$ tsc
@web3-onboard/torus
$ tsc
@web3-onboard/dcent
$ tsc
@web3-onboard/mew
$ tsc
@web3-onboard/walletlink
$ tsc
@web3-onboard/magic
$ rollup -c
@web3-onboard/walletconnect
$ tsc
@web3-onboard/core
 | 
 | src/index.ts → dist/...
@web3-onboard/magic
 | 
 | src/index.ts → dist/...
@web3-onboard/fortmatic
 | src/index.ts(50,29): error TS2339: Property 'from' does not exist on type 'typeof BigNumber'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn build` failed with exit code 2
@web3-onboard/web3auth
$ tsc
@web3-onboard/trezor
 | src/index.ts(73,7): error TS2740: Type 'BigNumber' is missing the following properties from type 'BigNumber': c, e, s, absoluteValue, and 33 more.
 | src/index.ts(178,19): error TS2322: Type 'import("/home/steve/Documents/GitHub/mavrik/web3-onboard/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber' is not assignable to type 'import("/home/steve/Documents/GitHub/mavrik/web3-onboard/node_modules/bignumber.js/bignumber").default'.
@web3-onboard/ledger
 | src/index.ts(74,7): error TS2740: Type 'BigNumber' is missing the following properties from type 'BigNumber': c, e, s, absoluteValue, and 33 more.
 | src/index.ts(171,21): error TS2322: Type 'import("/home/steve/Documents/GitHub/mavrik/web3-onboard/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber' is not assignable to type 'import("/home/steve/Documents/GitHub/mavrik/web3-onboard/node_modules/bignumber.js/bignumber").default'.
@web3-onboard/trezor
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn build` failed with exit code 2
@web3-onboard/ledger
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn build` failed with exit code 2
@web3-onboard/keystone
 | src/index.ts(38,7): error TS2740: Type 'BigNumber' is missing the following properties from type 'BigNumber': c, e, s, absoluteValue, and 33 more.
@web3-onboard/keepkey
 | src/index.ts(232,23): error TS2322: Type '{ derivationPath: string; address: string; balance: { asset: string; value: BigNumber; }; }' is not assignable to type 'Account'.
 |   The types of 'balance.value' are incompatible between these types.
 |     Type 'BigNumber' is missing the following properties from type 'BigNumber': c, e, s, absoluteValue, and 33 more.
 | src/index.ts(238,11): error TS2322: Type '{ derivationPath: string; address: string; balance: { asset: string; value: BigNumber; }; }[]' is not assignable to type 'Account[]'.
 |   Type '{ derivationPath: string; address: string; balance: { asset: string; value: BigNumber; }; }' is not assignable to type 'Account'.
@web3-onboard/keystone
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@web3-onboard/keepkey
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@web3-onboard/keystone
 | `yarn build` failed with exit code 2
@web3-onboard/keepkey
 | `yarn build` failed with exit code 2
@web3-onboard/magic
 | (!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'from' does not exist on type 'typeof BigNumber'.
 | src/index.ts: (101:29)
 | 
 | 101                 ? BigNumber.from(balance).mul('1000000000000000000').toString()
 |                                 ~~~~
 | 
 | created dist/ in 2.2s
@web3-onboard/core
 | (!) Circular dependencies
 | src/disconnect.ts -> src/services.ts -> src/notify.ts -> src/update-balances.ts -> src/provider.ts -> src/disconnect.ts
 | src/services.ts -> src/notify.ts -> src/update-balances.ts -> src/provider.ts -> src/services.ts
 | (!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
 | created dist/ in 5.8s
@web3-onboard/react
$ tsc
demo
$ cross-env NODE_ENV=production webpack
@web3-onboard/vue
$ tsc
demo
 | assets by chunk 9.47 MiB (id hint: vendors)
 |   assets by status 7.44 MiB [big]
 |     asset 2094.2094.js 1.6 MiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     asset 1561.1561.js 1.19 MiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     asset 9631.9631.js 996 KiB [compared for emit] [minimized] [big] (id hint: vendors)
 |     asset 8205.8205.js 906 KiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     asset 5806.5806.js 845 KiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     asset 6446.6446.js 689 KiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     asset 3889.3889.js 470 KiB [compared for emit] [minimized] [big] (id hint: vendors) 1 related asset
 |     + 3 assets
 |   + 37 assets
 | assets by chunk 1.96 MiB (name: main)
 |   asset main.js 1.96 MiB [compared for emit] [minimized] [big] (name: main) 1 related asset
 |   asset main.css 799 bytes [compared for emit] (name: main)
 | + 71 assets
 | Entrypoint main [big] 1.96 MiB = main.css 799 bytes main.js 1.96 MiB
 | orphan modules 2.98 MiB [orphan] 1262 modules
 | runtime modules 7.57 KiB 15 modules
 | javascript modules 17.3 MiB 1769 modules
 | json modules 2.79 MiB
 |   modules by path ../../node_modules/@web3auth/ 670 KiB 49 modules
 |   modules by path ../../node_modules/@keystonehq/ 669 KiB 47 modules
 |   modules by path ../../node_modules/eth-dcent-keyring/ 669 KiB 47 modules
 |   modules by path ../../node_modules/@ethereumjs/common/dist.browser/ 668 KiB 42 modules
 |   optional modules 159 KiB [optional] 10 modules
 |   modules by path ../../node_modules/browserify-sign/ 2.23 KiB 2 modules
 |   + 10 modules
 | css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/svelte-loader/index.js?cssPath=/home/steve/Documents/GitHub/mavrik/web3-onboard/packages/demo/src/App.svelte.0.css!./src/App.svelte 798 bytes [built] [code generated]
 | 
 | WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
 | This can impact web performance.
 | Assets: 
 |   main.js (1.96 MiB)
 |   9631.9631.js (996 KiB)
 |   3889.3889.js (470 KiB)
 |   6446.6446.js (689 KiB)
 |   5573.5573.js (301 KiB)
 |   8205.8205.js (906 KiB)
 |   2094.2094.js (1.6 MiB)
 |   1561.1561.js (1.19 MiB)
 |   5806.5806.js (845 KiB)
 |   5224.5224.js (266 KiB)
 |   140.140.js (281 KiB)
 | 
 | WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
 | Entrypoints:
 |   main (1.96 MiB)
 |       main.css
 |       main.js
 | 
 | 
 | webpack 5.69.1 compiled with 2 warnings in 18023 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
steve@5950x:~/Documents/GitHub/mavrik/web3-onboard$ 

### Expected Behavior

build successful

### Steps To Reproduce

on linux

get clone ...

yarn

yarn build

fails

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.6.0

### Node Version

16

### What browsers are you seeing the problem on?

Chrome

### Anything else?

I'm on branch release/2.6.0

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by sgehrman** [comment]
I was trying to use 2.6.0 since 2.5.0 is completely broken and overly hipster.

![gnome-shell-screenshot-JPV4P1](https://user-images.githubusercontent.com/287137/181719918-37818662-f021-43bb-9cd8-b87e4555d4ee.png)

**Comment by Adamj1232** [comment]
@sgehrman It looks like you are using the develop branch of the project, please use the main release branch `v2-web3-onboard`
Using your reproduction steps the project builds fine with the proper release branch.
Also not sure what `overly hipster` means in the context of an opensource, blockchain project.
