### ISSUE TITLE
[Bug]: Account centre options breaking application

### ISSUE THREAD

**Issue by Afitzy98** [blocknative/web3-onboard#1184]
### Current Behavior

After removing the lock file on our project and re-installing our node modules an error has propped up from this library. The core and react packages were updated that introduced a BREAKING CHANGE into our application. This has happened before also and is causing us many issues. If you are following the semantic release guidelines then no breaking changes should be introduced unless you are incrementing the major version. Please take some extra caution when changing/updating interfaces as it will introduce both development and build errors for the users consuming this library. I really like this library as it has an nice interface and supports many wallets/features but we are facing too many issues maintaining the library once it has already been implemented based on these changes that are introduced. 

The following images display our current configuration for the account centre options which is also working fine in the development environment. It can be seen in the image that a new rule was introduced that you must specify the containerElement for the account centre. Firstly, we do not want to use the account centre so it doesn't make sense that we have to specify an element it should have a default value and secondly when we actually do set the element value then the connect function stops working.

<img width="1440" alt="Screenshot 2022-08-01 at 12 33 43" src="https://user-images.githubusercontent.com/38539400/182130889-4c88a523-91c3-45ec-b351-79407eeef0eb.png">
<img width="1440" alt="Screenshot 2022-08-01 at 12 33 50" src="https://user-images.githubusercontent.com/38539400/182130904-bf99a995-126e-4b43-aca8-7766f77245ec.png">

Below is showing the specified containerElement but causing the application to break.

<img width="1440" alt="Screenshot 2022-08-01 at 12 34 05" src="https://user-images.githubusercontent.com/38539400/182131476-28a2bb25-d49c-4937-bbce-5b57b52b3b6e.png">
<img width="1440" alt="Screenshot 2022-08-01 at 12 34 21" src="https://user-images.githubusercontent.com/38539400/182131480-07644b3c-b5e2-4e03-ad08-d70939d2d812.png">

So right now I can't build the application with working config as the interface you have provided is giving a typescript error and I can't push the code with the 'correct' config as it break the app. Please can you push a fix for this ASAP and try not to push these breaking changes in a minor or patch release as otherwise we will need to use another solution as this is just wasting too much of our time.

The last time this happened I was able to revert to an older version of the library but that is not a satisfactory option. The semantic release guidelines should be followed to prevent anyone from running into these issues.

### Expected Behavior

The config interface for AccountCentre should both make sense and work.

### Steps To Reproduce

1. Use latest versions of web3-onboard/core, web3-onbooard/ & @web3-onboard/injected-wallets
2. Specify the account centre config
3. Try to connect wallet and error is thrown
4. Remove the containerElement props from mobile & desktop
5. Try to connect wallet again (will succeed)
6. Try to build application and get TS build error.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build, Runtime

### Package Version

2.5.0

### Node Version

18.3.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Property 'containerElement' is missing in type '{ enabled: false; }' but required in type 'Omit<AccountCenter, "expanded">'.ts(2741)

index.js?04b5:1280 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertRule')
    at create_rule (index.js?04b5:1280:1)
    at go (index.js?04b5:1569:1)
    at Object.start (index.js?04b5:1605:1)
    at eval (index.js?04b5:4962:1)
    at flush (index.js?04b5:1479:1)
helpers.js?0b5b:107 Uncaught TypeError: Cannot read properties of null (reading 'cssRules')
    at eval (index.js?04b5:1307:1)
    at Map.forEach (<anonymous>)
    at eval (index.js?04b5:1305:1)
    at sentryWrapped (helpers.js?0b5b:85:1)
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Afitzy98** [comment]
Checking in the dist folder of the core I see the default tag is body. I specified this and it is now working but my points relating to semantic versioning and default values remain.

**Comment by Adamj1232** [comment]
@Afitzy98 thank you for the heads up! We have a fix for this in staging and will be releasing shortly. 
You can try out the Alpha release published with Core version `2.6.0-alpha.7`
We do always try and follow semantic versioning but as this is an open source project sometimes issues arise and we try to handle them as quickly as possible, I will update when the new version is published.

**Comment by Afitzy98** [comment]
@Adamj1232 thanks for the response. The issue is resolved for me for the moment anyways I imagine I was using an invalid element type. I understand this is an open source project so apologies if I am being a little harsh but some of these issues can be tricky to solve. Using TypeScript types for the options rather than typing them as strings could be a good way to go for the core config? Just a suggestion, thanks again.

**Comment by Adamj1232** [comment]
@Afitzy98 This has been fixed in our latest release! Please checkout the Core 2.6.0 package for that fix
