### ISSUE TITLE
[Bug]: Ledger integration error

### ISSUE THREAD

**Issue by ihorbond** [blocknative/web3-onboard#1201]
### Current Behavior

After installing "@web3-onboard/ledger": "^2.1.7" and importing get the following error:

ERROR in ./node_modules/@ledgerhq/hw-transport-webusb/lib-es/TransportWebUSB.js
Module not found: Error: Can't resolve '@ledgerhq/devices/hid-framing' in 'C:\Code\zerocodenft\mint\node_modules\@ledgerhq\hw-transport-webusb\lib-es'

### Expected Behavior

Ledger integration works as intended

### Steps To Reproduce

npm i @web3-onboard/ledger
import it somewhere
build & run the app

### What package is effected by this issue?

@web3-onboard/ledger

### Is this a build or a runtime issue?

Runtime

### Package Version

2.5.0

### Node Version

16.15

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
ERROR in ./node_modules/@ledgerhq/hw-transport-webusb/lib-es/TransportWebUSB.js
Module not found: Error: Can't resolve '@ledgerhq/devices/hid-framing' in 'C:\Code\zerocodenft\mint\node_modules\@ledgerhq\hw-transport-webusb\lib-es'
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@ihorbond this looks like an internal Ledger issue that can be [found here](https://github.com/LedgerHQ/ledger-live/issues/763)
We will keep an eye on it and update with any changes around this issue. 
Thanks for reporting it!

**Comment by ihorbond** [comment]
ah good call, I should have done better research into it. for Nuxt v2 the fix is just adding 
```
alias: {
  "@ledgerhq/devices": "@ledgerhq/devices/lib-es"
}
```
to the nuxt.config.js

**Comment by aaronbarnardsound** [comment]
@ihorbond thanks for posting the fix here, i'll close this issue for the moment, but feel free to reopen if needed.
