### ISSUE TITLE
[Bug]: Switching to a new network on metamask mobile app does not prompt "Add Network" like it does on desktop

### ISSUE THREAD

**Issue by dweng0** [blocknative/web3-onboard#1234]
### Current Behavior

**On Desktop**
1. Go to [blocknative react demo ](https://reactdemo.blocknative.com/)
2. Connect your meta mask wallet
3. Connect to a network from the list that you **do not** currently have added. You will be prompted to add the network

**On Mobile (Metamask App)**

1. Go to [blocknative react demo ](https://reactdemo.blocknative.com/)
2. Connect your meta mask wallet
3. Connect to a network from the list that you **do not** currently have added. Nothing will happen.
The following error shows in the console:
![Screenshot_20220826-093114](https://user-images.githubusercontent.com/5268627/186859938-c69a90ac-85c7-4a0b-b0cc-2a9623ea6d69.png)

### Expected Behavior

**On Mobile Metamask App**
1. Go to [blocknative react demo ](https://reactdemo.blocknative.com/)
2. Connect your meta mask wallet
3. Connect to a network from the list that you **do not** currently have added. 
4. Attempt to switch to that network. 
5. If the unrecognised chain error occurs:
6. Attempt to Add that network instead

### Steps To Reproduce

1. On metamask mobile browser
2. Go to block native react demo
3. try to change to a network that you have not added

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

latest

### Node Version

latest supported

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
MetaMask - RPC Error: Unrecognized chain ID "..."
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Thanks we'll take a look in to this. I did some quick digging and this may have something to do with a different error code being returned on mobile for the switch chain method.

**Comment by dweng0** [comment]
As a temporary fix: If the wallet is metamask, we listen for the error code and then manually execute an "add chain" event (metamask native)

**Comment by Adamj1232** [comment]
@dweng0 thanks for the note on the temp fix! I will keep this issue open until we have a fix deployed to production for both community and eng team visibility

**Comment by Adamj1232** [comment]
The change for this is in [PR here](https://github.com/blocknative/web3-onboard/pull/1248) I will update this issue when an alpha package is available. Thanks again!

**Comment by Adamj1232** [comment]
Closing as issue is resolved with latest release. Thanks again!
