### ISSUE TITLE
request: css variable for wallet button color on hover

### ISSUE THREAD

**Issue by DisruptiveMind** [blocknative/web3-onboard#1240]
Hi,

Apologies if this is the wrong place to request but before sending a PR I'd like to confirm.

I'm looking at restyling for a dark theme and saw that there is a missing variable to set wallet button color on hover.
I see that the background has a variable and wondering if there is a companion for the font color.
`--onboard-wallet-button-color-hover`

Is there a plan for this variable to be added?

**Comment by Adamj1232** [comment]
@DisruptiveMind there currently is not a css variable for text color on wallet button hover. If you would like to create a PR with that addition that would be great otherwise I will be sure to add it to an upcoming version. Thanks for bringing that to our attention!
