### ISSUE TITLE
[Bug]: Connection to WalletConnect>Crypto.com | DeFi Wallet on Desktop is rejected

### ISSUE THREAD

**Issue by emeraldFBear** [blocknative/web3-onboard#1242]
### Current Behavior

Connecting to Crypto.com | DeFi Wallet, the redirect only opens an empty tab and does not ask the user for any action.
This is the url in the new tab: cryptowallet://wc?uri=wc%3Aaba3ae9e-9c4d-4e51-8c11-4754e124e6c1%401%3Fbridge%3Dhttps%253A%252F%252Ff.bridge.walletconnect.org%26key%3D98803d47cef584a99bb10dffa4c76843d1ae3a030ee13392305fb5ecace8c212

### Expected Behavior

On choosing Crypto.com | DeFi Wallet, the user should be prompted to connect/create a wallet then the wallet gets connected.

### Steps To Reproduce

1. On Desktop, connect Wallet through WalletConnect
2. Choose Cryptom.com | DeFi Wallet
3. New browser tab opens and remains blank
4. Going back to WalletConnect, it says Connection Rejected

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.1

### Node Version

v16.15.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@emeraldFBear thatnk you for reporting this issue. Do you see this issue with other instances of WalletConnect/Crypto.com usages? i.e. An instance of WalletConnect routing to the proper install address for Crypto.com that is not used within Web3-Onboard?

**Comment by Adamj1232** [comment]
This is an issue with WalletConnect. An issue has been opened within their repo that can be tracked [here](https://github.com/WalletConnect/walletconnect-monorepo/issues/1421)

**Comment by Adamj1232** [comment]
Closing as this is not an issue with W3O. Thanks for reporting!
