### ISSUE TITLE
[Bug]: Connect to MetaMask/Brave not accurate

### ISSUE THREAD

**Issue by mario-iliev** [blocknative/web3-onboard#1250]
### Current Behavior

Hey guys. I stumbled upon a problem which I tried to detect in the codebase but I'm not really sure where is the correct place to do it, so I can't provide PR for it.
When there is MetaMask and Coinbase wallet installed on Brave browser and I choose to connect to MetaMask trough 
`onboard
.connectWallet({
      autoSelect: { label: 'MetaMask', disableModals: true },
})`
I'm being connected to Brave Wallet instead. I suspect that there is a loop check in the window.ethereum.providers and the first which has isMetaMask === true is selected but there is no specific check for "isBraveWallet". From the official onboard connect modal I see that there is no differentiation between MetaMask and Brave wallet but I really think there should be.

### Expected Behavior

Target correctly MetaMask and Brave wallet connection.

### Steps To Reproduce

1. Install the following injected wallets in a Brave browser: Metamask and Coinbase
2. Try to connect to Metamask

Result: You will be connected to Brave Wallet but the modal will state that it's MetaMask

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.1

### Node Version

16.14.2

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@mario-iliev I have a PR with the fix created. If interested you can check it out here - https://github.com/blocknative/web3-onboard/pull/1258

**Comment by Adamj1232** [comment]
This fix is available with injected package 2.2.2-alpha.2 and will be released early next week

**Comment by Adamj1232** [comment]
Closing as this fix is available with the injected-wallet package v2.2.2
