### ISSUE TITLE
How can I add a custom module that has same provider name with another provider? 

### ISSUE THREAD

**Issue by huy23121994** [blocknative/web3-onboard#1251]
I want to add a custom injected module but this module has the same provider name as Metamask. 

Metamask injects an obj named 'ethereum' and the custom injected module too.
So how can I integrate both?

**Comment by taylorjdawson** [comment]
Hey @huy23121994 👋🏾 Which injected wallet are you trying to add that has the same provider name?

**Comment by aaronbarnardsound** [comment]
Closing this issue for now, feel free to reopen if you are still having trouble creating a custom module.
