### ISSUE TITLE
[Feature]: Transpile with babel

### ISSUE THREAD

**Issue by georgesmithishere** [blocknative/web3-onboard#1256]
### Is your request related to a problem?

Hello and thank you for great library!
not able to run a tests
<img width="966" alt="Screenshot 2022-09-07 at 15 10 51" src="https://user-images.githubusercontent.com/107099523/188875354-0fa5d3be-5429-4c74-9a3f-8e69a30f9cb6.png">

### Feature Description

maybe you could transpile assets with babel to get rid of ES6 syntax (which is not supported by Jest/NodeJS)

### Anything else?

https://github.com/prepo-io/prepo-monorepo/tree/feat/onboard_wallets
this is our public mono-repo
steps to reproduce:
1. go to `/apps/frontend/core-dapp`
2. install dependencies `yarn install` 
3. and then `yarn test`

**Comment by techgangboss** [comment]
Hey @georgesmithishere we're considering this and it's on our list - if you want to make sure it's in sooner than later we urge you to do a PR and add it in.

What is the build env you're using this with?

**Comment by aaronbarnardsound** [comment]
@georgesmithishere could you try [configuring your test env](https://stackoverflow.com/questions/35756479/does-jest-support-es6-import-export) to use Babel?

**Comment by aaronbarnardsound** [comment]
Closing this issue for now, feel free to reopen if the above suggestion does not help.

**Comment by carlosrsabreu** [comment]
Hello!

Is there any news about this? I'm getting also the same error as @georgesmithishere mentioned.

@aaronbarnardsound I tried the workaround you mentioned here but it's still now working: https://github.com/blocknative/web3-onboard/issues/1256#issuecomment-1244789235

**Comment by ChihYang41** [comment]
Hi! 
I'm also getting the same error when I'm trying to run jest.  I tried the solution @aaronbarnardsound provided and it doesn't work either.

If you can provide any solution for this issue, I would really appreciate it.

my environment:
- Next.js v12.1.0
- React.js v17.0.0
- Jest v27.5.1

my jest config:
```javascript
const nextJest = require('next/jest');
const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig.json');

const createJestConfig = nextJest({
  dir: './',
});

const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleDirectories: ['node_modules', '<rootDir>/'],
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    '^@/(.*)': '<rootDir>/$1',
  },
  testPathIgnorePatterns: ['/nodule_modules/'],
};

module.exports = createJestConfig(customJestConfig);
```

**Comment by carlos-menezes** [comment]
Any news on this? I've tried countless solutions, including @aaronbarnardsound , but to no avail.

**Comment by carlosfaria94** [comment]
@aaronbarnardsound @techgangboss we are having the same issue running tests on Jest.
It's possible to provide a transpile with babel?

Thanks
