### ISSUE TITLE
[Bug]: eth_signTypedData_v4 not supported when use the function of _signTypedData 

### ISSUE THREAD

**Issue by fuhuimin** [blocknative/web3-onboard#1271]
### Steps To Reproduce

1.conncet wallet through the walletconnect
2.scan the qrcode with imtoken wallet
3.use the function of _signTypedData to sign
4.throw a error : The method eth_signTypedData_v4 does not exist/is not available

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

^2.0.8

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @fuhuimin thanks for pointing this out and creating a PR. We will get it reviewed as soon as possible.
