### ISSUE TITLE
[Bug]: walletconnect with vite runtime global/buffer not defined

### ISSUE THREAD

**Issue by syffs** [blocknative/web3-onboard#1285]
### Current Behavior

using web3-onboard with SvelteKit, import of '@web3-onboard/walletconnect' is failing for on 2 points as browser errors:
- "global is not defined": can fix it by adding this to `vite.config.js`, but it's creating other issues for libs which includes some `global.js` files, which then gets translated to `globalThis.js` and throw (`@sentry/core` in my case)
```ts
/** @type {import('vite').UserConfig} */
const config = {
	define: {
		global: 'globalThis' // <== here
	},
...
```
- "Buffer is not defined": I do have polyfills but I guess they're not getting through for some reason
```ts
import nodePolyfills from 'rollup-plugin-polyfill-node';
/** @type {import('vite').UserConfig} */
const config = {
...
	build: {
		rollupOptions: {
			plugins: [
				// Enable rollup polyfills plugin
				// used during production bundling
				nodePolyfills()
			]
		}
	}
...
```
It seems that walletconnect faces the same [kind of issue when standalone](https://github.com/vitejs/vite/issues/7257#issuecomment-1079579892), but `@web3-onboard/walletconnect` doesnt include an UMD build to workaround it

Also weirdly, walletconnect does work through vite dev, but not once built.

### Expected Behavior

dynamic import should be seamless.

### Steps To Reproduce

using SvelteKit & vite, here is a [similar setup](https://github.com/tankbottoms/tiles-wtf-gallery/blob/main/src/stores/web3.ts)

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.1.2

### Node Version

16.16.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Relevant log output

```shell
Uncaught (in promise) ReferenceError: Buffer is not defined
    at Er (index-340e11d4.js:1:44728)
    at Ht (index-340e11d4.js:1:45066)
    at Module.dr [as generateKey] (index-340e11d4.js:1:76479)
    at sn._generateKey (index-340e11d4.js:1:74081)
    at sn.createSession (index-340e11d4.js:1:65154)
    at d.code (index-ad162ce8.js:1:2732)
    at new Promise (<anonymous>)
    at R.request (index-ad162ce8.js:1:2668)
    at Gp (index-b6702a51.js:106:13299)
    at he (index-b6702a51.js:203:6461)
```
```


### Anything else?

_No response_

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by syffs** [comment]
@Adamj1232 thanks for the quick response!

I did try something similar following [this](https://stackoverflow.com/questions/71067299/walletconnect-fails-to-get-bundled-with-vite). It's giving me the same error, I also tried including walletconnect manually to optimizeDeps (without success):
```ts
  optimizeDeps: {
		include: ['nodes_modules/@web3-onboard/walletconnect/**/*.js'],
  }
```

**Comment by syffs** [comment]
This is a non-sense: but here is a workaround:
```ts
	(window.global as any) = globalThis;
	window.Buffer = (await import('buffer')).Buffer;
	const walletConnect = (await import('@web3-onboard/walletconnect')).default();
```

**Comment by Adamj1232** [comment]
> This is a non-sense: but here is a workaround (client-side only):
> 
> ```ts
> 
> 	(window as any).global = globalThis;
> 
> 	global.Buffer = global.Buffer || (await import('buffer')).Buffer;
> 
> 	// global.process = global.process || (await import('process')).default; // coinbase
> 
> 	const walletConnect = (await import('@web3-onboard/walletconnect')).default();
> 
> ```
> 
> 
> 
> 

Hmmm very Interesting! 
Is this within your vite.config? If so can can you send your whole configuration over?
Glad you got it working!
cc @taylorjdawson 👀

**Comment by syffs** [comment]
> > This is a non-sense: but here is a workaround (client-side only):
> > ```ts
> > 	(window as any).global = globalThis;
> > 
> > 	global.Buffer = global.Buffer || (await import('buffer')).Buffer;
> > 
> > 	// global.process = global.process || (await import('process')).default; // coinbase
> > 
> > 	const walletConnect = (await import('@web3-onboard/walletconnect')).default();
> > ```
> 
> Hmmm very Interesting! Is this within your vite.config? If so can can you send your whole configuration over? Glad you got it working! cc @taylorjdawson 👀

It's not in my `vite.config`, it's directly in the file setting up `web3-onboard` and `walletconnect`. My `vite.config` has nothing out of the ordinary:
```ts
const config: UserConfig = {
	plugins: [
		development &&
			nodePolyfills({
				include: ['node_modules/**/*.js', new RegExp('node_modules/.vite/.*js')]
			}),
		sveltekit()
	],
	build: {
		chunkSizeWarningLimit: 1900,
		rollupOptions: {
			plugins: [
				// Enable rollup polyfills plugin
				// used during production bundling
				nodePolyfills()
			]
		},
		commonjsOptions: {
			transformMixedEsModules: true
		}
	}
};
```

I still fail to understand why it's working in `dev` but not once built for prod

**Comment by kujtimprenku** [comment]
Hey, @syffs I am not very familiar with either Vite or Svelte but I've seen something like this in a project with Vite + React.

To fix the error about **global** in prod instead of setting the value to `"globalThis"` try setting it to the string `"window"`

```ts
import { sveltekit } from '@sveltejs/kit/vite';

const config = {
  plugins: [sveltekit()],
  define: {
    "global": "window",
  },
};

export default config;

```

For errors about **Buffer is not defined** try installing buffer as a dependency and then in your **index.html** (root html file) add something like this inside `body`  below the root element:

```ts
<body data-sveltekit-prefetch>
  <div>%sveltekit.body%</div>

  <script type="module">
    import { Buffer } from 'buffer';
    window.Buffer = Buffer;
  </script>

</body>
```

**Comment by taylorjdawson** [comment]
@syffs FYI I got it working using [this config](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/examples/with-vite-react/vite.config.ts)

```js
import { defineConfig } from 'vite'

import react from '@vitejs/plugin-react'
import nodePolyfills from 'vite-plugin-node-stdlib-browser'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), nodePolyfills()],
  optimizeDeps: {
    exclude: ['@ethersproject/hash', 'wrtc'],
    include: ['js-sha3', '@ethersproject/bignumber']
  }
})
```

**Comment by ryeshrimp** [comment]
This fixed my issue using svelte/vite

```
import Buffer from "buffer";

(window as any).global = globalThis;
global.Buffer = Buffer.Buffer;
```

**Comment by taylorjdawson** [comment]
@syffs Closing for now, please feel free to re-open if you think that this issue is not resolved 👍🏾
