### ISSUE TITLE
[Feature]: Fallback provider

### ISSUE THREAD

**Issue by bachstatter** [blocknative/web3-onboard#1300]
### Is your request related to a problem?

An rpc node might be down, a fallback option would resolve the issue

### Feature Description

It would be good to be able to use ethers defaultProvider or a fallback provider. 
https://docs.ethers.io/v5/api/providers/#providers-getDefaultProvider.

**Comment by aaronbarnardsound** [comment]
Hey @bachstatter could you add some more detail to this feature request so we can better understand what you need? We use a provider internally for ENS lookups, so not sure if you are referring to that, or possibly the provider we use in the hardware wallet modules? 

If you are referring to the provider that is added to the `wallet` object, that is just the one that the wallet exposes. You can pass it in to ethers to create an ethers provider and then call the `getDefaultProvider` method on that i believe.

**Comment by ejc8** [comment]
Hi @bachstatter we're closing this issue - if you have more details feel free to reopen

**Comment by Bosper** [comment]
Hello, 

It is about an array of providers and handle a fallback if default provider has error or a fallback method..

`const provider = new Web3(new Web3.providers.HttpProvider([_network.urlRPC, _network.urlRPC_fallback, ...]));`

or 

`const provider = new Web3(new Web3.providers.HttpFallbackProvider(_network.urlRPC_fallback));`


Best Regards :)
