### ISSUE TITLE
[Bug]: `containerElement` option for Account Center attaches full Onboard instance rather than just AC component

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/web3-onboard#1311]
### Current Behavior

When passing in an element query string for the `containerElement` option within the Account Center options, the whole Onboard UI is mounted to the element.

### Expected Behavior

I would expect that just the Account Center component would mount to the element so there is greater control of where that component is rendered.

One use case is to be able to position just the Account Center component relative to another element on the page.

### Steps To Reproduce

1. Pass in `containerElement` option
2. See that all of Onboard is rendered to the element that is passed in

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

core: 2.8.3

### Node Version

16.10.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Development on this is in progress 🎸
