### ISSUE TITLE
[Feature]: Add support for wallet_switchEthereumChain in the walletConnect provider

### ISSUE THREAD

**Issue by alexkeating** [blocknative/web3-onboard#1313]
### Is your request related to a problem?

- When a user connects to our app with walletconnect we want to be able to switch the chain they are connected to in our app. 

### Feature Description

Implement wallet_switchEthereumChain in the below provider. My guess is that the wallet connect session could be updated to the passed in chainId. 

- https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/src/index.ts#L183

**Comment by aaronbarnardsound** [comment]
@alexkeating we will take a look in to this and see if can get a workaround like recreating the session to make it work.

**Comment by alexkeating** [comment]
Great, thank you!

**Comment by alexkeating** [comment]
Any updates on this? Anything I can do to help move this along?

**Comment by aaronbarnardsound** [comment]
Hey @alexkeating sorry we have a lot in our backlog at the moment, so have not had a chance to get to this yet. You can try and work out a solution and create a PR if you have time which will speed up the process as we would only need to review in that case.

**Comment by alexkeating** [comment]
I am upgrading Umbra to the latest version of the wallet connect package, and it doesn't seem to be switching when wallet_switchEthereumChain is sent. I am not sure why yet, but I thought it would be good to surface, and I am wondering if you guys are seeing the same thing locally.

**Comment by Adamj1232** [comment]
@alexkeating I have a PR open that you can track that issue [here](https://github.com/blocknative/web3-onboard/pull/1380)
Should have an alpha fix available shortly

**Comment by Adamj1232** [comment]
@alexkeating an alpha version of this fix has been published and you can try the alpha release of the WalletConnect package at version `2.2.1-alpha.1`
