### ISSUE TITLE
[Bug]: Trezor module not getting triggered to begin unlocking/connecting

### ISSUE THREAD

**Issue by n4n0GH** [blocknative/web3-onboard#1325]
### Current Behavior

After installing `@web3-onboard/trezor` and setting it up according to documentation (including checking build environment requirements) I found the Trezor button inside the web3-onboard modal, but clicking it just yields an infinite idle state. Attached video for visualization.

https://user-images.githubusercontent.com/27410256/196785937-a167ef61-42a6-4e60-8130-a9859a2b3fd1.mov

As can be seen, there's no error output in the console.

Implementation is done like so:

```javascript
// ...
import Onboard from '@web3-onboard/core';
import injectedModule from '@web3-onboard/injected-wallets';
import walletConnectModule from '@web3-onboard/walletconnect';
import coinbaseWalletModule from '@web3-onboard/coinbase';
import trezorModule from '@web3-onboard/trezor';
// ...
const injected = injectedModule();
const walletConnect = walletConnectModule();
const coinbase = coinbaseWalletModule();
const trezor = trezorModule({
  email: 'zosimos@mail.alchemix.fi',
  appUrl: 'https://alchemix.fi/',
});
// ...
const onboard = Onboard({
  wallets: [injected, walletConnect, coinbase, trezor],
  // ... other init configs 
});
```

Apart from Trezor, all other wallet integrations work as expected.

### Expected Behavior

Clicking the Trezor button should create a tab or new window asking me to unlock my device and export my private key and finally connect the frontend with my device, allowing me to use the dapp.

### What package is effected by this issue?

@web3-onboard/trezor

### Is this a build or a runtime issue?

N/A

### Package Version

2.7.0

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@n4n0GH what browser are you seeing this issue with?
Can you provide me with code to reproduce this issue?
I am not seeing the same behavior using our deployed demo site - for example [here](https://reactdemo.blocknative.com/)

**Comment by n4n0GH** [comment]
@Adamj1232 this was happening on Firefox, Chrome and Brave, all latest versions, running on macOS 12.6.
To reproduce you need to clone our repo (https://github.com/alchemix-finance/alchemix-v2-frontend), install trezor module as per Blocknative's documentation and implement it here: https://github.com/alchemix-finance/alchemix-v2-frontend/blob/prod/src/helpers/walletManager.js
The React demo site is working fine for me as well.

**Comment by Adamj1232** [comment]
@n4n0GH I also noticed you haven't themed your Connect modal, if interested we have a new tool to help with that. 
Just drop your url in and you can update the theme mapping to help onboard look native to your site(click the color circle and change - the dropper tool is really helpful here). 
Then copy the config and drop into you main css.
https://onboard.blocknative.com/theming-tool

**Comment by n4n0GH** [comment]
Got it working as well, but it wasn't due to our vite config (looked same-ish on my local instance); instead with `@web3-onboard/core^2.7.0` it will still fail. I updated to `^2.9.0` now and that's got it going.
And thanks for that theming tool!

Thank you!
