### ISSUE TITLE
[Bug]: Connect to Rabby

### ISSUE THREAD

**Issue by heisenberg-2077** [blocknative/web3-onboard#1326]
### Current Behavior

Hey guys.
I'm a Rabby Team member. In previous versions, if Rabby is in use, Rabby was connected when the user choose MetaMask. But [this PR](https://github.com/blocknative/web3-onboard/pull/1258) breaks this feature. When MetaMask is choose, neither Metamask nor Rabby will be connected.

### Expected Behavior

if Rabby is in use, Rabby was connected when the user choose MetaMask

### Steps To Reproduce

1. Open Dapp https://theaptosbridge.com/
2. Install Rabby
3. Choose "Connect Metamask"

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.13.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@heisenberg-2077 I followed your reproduction steps for the issue and https://theaptosbridge.com/ is not using web3-onboard for connecting a wallet.
<img width="1118" alt="Screen Shot 2022-10-20 at 3 08 56 PM" src="https://user-images.githubusercontent.com/24457880/197058551-40c4baa5-7baa-499a-a896-649a16c47347.png">

**Comment by heisenberg-2077** [comment]
I searched the code and saw that they used the web3-onboard.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/110591045/197104808-ffb71b33-11ff-46bf-9814-68c9d672a33d.png">

>  if I am understanding your request correctly we do not want to add misdirection to Web3-Onboard when selecting a wallet.

Sure, But if the user only has Rabby installed, and the MetaMask icon is selected, I would like to be able to fallback to connecting to Rabby

**Comment by Adamj1232** [comment]
@heisenberg-2077 hmm interesting, I can't discern how they are using W3O from a quick glance. They are def not using our onboard UI.
As for the fallback from MM, this is not something we are currently looking to support. We are trying to reduce the level of end user confusion by unexpected behavior, in this case being when one wallet is selected(by name and icon) a different wallet responds.
