### ISSUE TITLE
[Bug]: @web3-onboard/trezor throws error when attempting to execute state changing transaction

### ISSUE THREAD

**Issue by n4n0GH** [blocknative/web3-onboard#1341]
### Current Behavior

When connecting to a Trezor hardware wallet and trying to execute a transaction that would change state on-chain, the Trezor module is trying to call a function from the included `ethereumjs-util` package that does not exist: https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/trezor/src/index.ts#L383

Looking at the package.json and checking out the source for that specific version of the package used, it seems like that function indeed doesn't exist. (https://www.npmjs.com/package/ethereumjs-util)

It does however exist in the now archived and old repository: https://github.com/ethereumjs/ethereumjs-util/blob/master/src/bytes.ts#L204

The problem occurs most likely because the npm link has been updated to point to https://github.com/ethereumjs/ethereumjs-monorepo instead of https://github.com/ethereumjs/ethereumjs-util/

### Expected Behavior

Transactions should work without issues like they do for other connectors.

### Steps To Reproduce

1. Set up project with trezor module installed
2. Connect project to trezor wallet
3. Attempt calling a function to execute a transaction

### What package is effected by this issue?

@web3-onboard/trezor

### Is this a build or a runtime issue?

Runtime

### Package Version

2.10.0

### Node Version

14.18.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@n4n0GH thanks for raising this issue, we will take a look at this later this week or early next week. 
Can you verify the issue presents on our internal demo reactdemo.blocknative.com?
If you have a fix you are welcome to submit a PR in the meantime if that gets you unblocked and we can get that reviewed more quickly.

**Comment by Adamj1232** [comment]
Those errors are related to the Infura provider api key that is domain scoped.
It is interesting that I see that method available in my local build and it should be there because of the yarn.lock.
How are you using web3-onboard? Did you use npm or yarn to install or do you have a local instance/fork?
Can you send a screenshot of the error you see?

**Comment by ejc8** [comment]
@n4n0GH closing this issue, if this comes back up or you have more details please re-open
