### ISSUE TITLE
[Bug]: Mew Wallet not working properly

### ISSUE THREAD

**Issue by dweng0** [blocknative/web3-onboard#1348]
### Current Behavior

Currently when connected to mew wallet, block native hangs and doesn't update the account states.

It essentially just hangs while "connecting"

On our test server
![mew_wallet_switch](https://user-images.githubusercontent.com/5268627/199231778-a6ced3d6-53a4-4a34-9c60-676eac7d2349.gif)

On a fork of React demo
![hang connection](https://user-images.githubusercontent.com/5268627/199232019-de5fc8dd-9d38-4459-ac4d-4ab398c4d03b.gif)

https://user-images.githubusercontent.com/5268627/199231826-92ff5e23-8ec2-4e56-8f5e-c9da5ca888ee.mp4

### Expected Behavior

Should connect and then update things like balances and such

### Steps To Reproduce

- Clone react demo
- Install MEW wallet `@web3-onboard/mew`
- Add it to services.js:
-`import mewModule from '@web3-onboard/mew'`
- include it in wallet array:
- `wallets:[injected, mew]
- Run the application via HTTPS (local tunnel if required).

### What package is effected by this issue?

@web3-onboard/mew

### Is this a build or a runtime issue?

Runtime

### Package Version

/react - 2.4.0

### Node Version

16.15.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@dweng0 we are working with the MEW team to create a [new MEW package](https://github.com/blocknative/web3-onboard/pull/1291) and the current will become deprecated because of some changes happening on the wallet side. This should be out in the next week or two.
I have touched base with their team to get more information(they may even chime in if applicable) but I will keep you up to date on this change.

**Comment by dweng0** [comment]
Hey, thanks for the info

**Comment by dweng0** [comment]
As an update. We've decided to remove MEW until the new module comes out. So this issue can be closed. Thanks for your time.

**Comment by Adamj1232** [comment]
Sounds good, we will keep this card open for any other users experiencing the same issue and update when the new MEW package is released. Thanks again for raising this issue!

**Comment by Adamj1232** [comment]
Closing as @web3-onboard/mew is deprecated in favor of @web3-onboard/mew-wallet - We worked with the MEW team to get this new package out to provide full support for the new MEW wallet
