### ISSUE TITLE
--account-center-border is not applied to minimized account center

### ISSUE THREAD

**Issue by CherryDT** [blocknative/web3-onboard#1358]
The reason is a typo (`--acount-center-border` with one `c`) here:

https://github.com/blocknative/web3-onboard/blob/860fad574b69efe62ef61c5e050f3f4cdbde64eb/packages/core/src/views/account-center/Micro.svelte#L25

While we are at it: In the docs, there is another typo that talks about an `--account-center-boarder-radius` with extra `a` in "border".

**Comment by taylorjdawson** [comment]
@CherryDT Thanks for pointing that out! Fix for the docs [here](https://github.com/blocknative/web3-onboard/pull/1361/files#diff-1b650a22d454649ccc22a843f70577ff7d141a5ff6482e9508f36c6ed24e70aa) and for the account center [here](https://github.com/blocknative/web3-onboard/pull/1362)
