### ISSUE TITLE
Inconsistent / broken mobile provider detection

### ISSUE THREAD

**Issue by CryptoKira** [blocknative/web3-onboard#1364]
Imported the web3-onboard library into a Vuejs 2 app, did the correct setup as per documentation.
From desktop, Metamask connects fine.

From Metamask mobile browser, no Metamask is detected. I have imported the 'walletconnect' module, and it does have walletconnect as a option on MM mobile, but this doesn't connect correctly.

From TrustWallet, it doesn't detect either. I choose again the walletconnect option, which then connects, after which I then do a refresh, and then the TrustWallet option appears.

I have tried different vuejs version, different import locations, even the @web3-onboard/vue, nothing seems to resolve these issues.
On previous builds it would inconsistently detect Metamask on mobile.

**Comment by CryptoKira** [comment]
did a quick test.
I used the default vue version 3 starter page and added just the functionality to connect.
This worked on all the mobile cases as expected, on Metamask and TrustWallet.
Now why in my application would the mobile detection be so faulty? Is it based on page loading time? or some other dependencies that break it? 
Any suggestions welcome

**Comment by CryptoKira** [comment]
Seems the issue is not related the library but something else.

I'm using this script from the Metamask docs.

```if (window.ethereum) {
    handleEthereum();
} else {
    window.addEventListener('ethereum#initialized', handleEthereum, {
        once: true,
    });
    // If the event is not dispatched by the end of the timeout,
    // the user probably doesn't have MetaMask installed.
    setTimeout(handleEthereum, 5000); //5 seconds
}

function handleEthereum() {
    const { ethereum } = window;
    if (ethereum && ethereum.isMetaMask) {
        console.log('Ethereum successfully detected!');
    } else {
        console.log('Please install MetaMask!');
    }
}```

On my brand new testing page, this works fine in all wallets.
On my main application, this doesn't work at all, only on desktop.
Not sure where its going so wrong, since its just a vue 2 project, nothing too complicated...

**Comment by Adamj1232** [comment]
@CryptoKira are you using server side rendering?
If you are using web3-onboard you shouldnt need the above script as this is all handled for you by the web3-onboard lib.
I am going to close this issue as there isn't a problem with the library but we can continue the conversation 😃

**Comment by CryptoKira** [comment]
Finally figured it out, in the main html I had this line

```<link rel="preconnect" href="https://fonts.gstatic.com">```

When this is present, it breaks MM and TrustWallet. My guess is it doesn't have compatibility with "preconnect" then completely crashes internally or something.
ZZZ this took forever to find
