### ISSUE TITLE
 How to add other wallets to Web3-onbord and main panel?

### ISSUE THREAD

**Issue by crazySadSoul** [blocknative/web3-onboard#1366]
our company want to add a wallet , but web3-onbord wallets list is not support yet.
dose web3-onbord support to set another wallet?
forgive my english is bad.

**Comment by Adamj1232** [comment]
@crazySadSoul we have some documentation around adding a wallet [here](https://onboard.blocknative.com/docs/overview/contribution-guide#how-can-i-get-a-new-wallet-added)
Please let me know if this documentation suits your needs or if there is anything else I can help with. Thanks!

**Comment by crazySadSoul** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/26052793/202075826-786f3e6e-1a36-443b-9acc-79669697ea15.png">
@Adamj1232 Hi, this document showed how to add a wallet to "injected" wallet, does web3-onbord support add to the panel like the picture show.

**Comment by crazySadSoul** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/26052793/202098117-e3c3552a-4f72-4b13-8f90-d56eb223c111.png">
@Adamj1232 is this it?  i click the link of the "See here for an example of a pull request.", i saw the pull request info. 
Can you guys provide a clearer documentation? Thank you~~~~~

**Comment by crazySadSoul** [comment]
> @crazySadSoul we have some documentation around adding a wallet [here](https://onboard.blocknative.com/docs/overview/contribution-guide#how-can-i-get-a-new-wallet-added) Please let me know if this documentation suits your needs or if there is anything else I can help with. Thanks!

thank you ! thats clear! i see!
should i create a new branch for the new wallet and push it?

**Comment by Adamj1232** [comment]
@crazySadSoul It would be best to fork the project and then create a PR when ready. Please let me know if you run into any challenges around this. I will close this issue but feel free to keep this conversation going for any support 😄

**Comment by crazySadSoul** [comment]
@Adamj1232 Hi， i've add the wallet in the web3-onbord of my native environment. i want to test it on my native environment. what should i do next~~~~

**Comment by Adamj1232** [comment]
You can use `yarn link` to link projects locally - https://classic.yarnpkg.com/lang/en/docs/cli/link/
Generally you can run `yarn link` within the `injected-wallets` package of onboard and then in you app using onboard run `yarn link "@web3-onboard/injected-wallets"` or something close to that and you will be able to use the local instance in your app.
Alternatively you can test with the local demo project that is part of the web3-onboard app under `packages/demo`
To do this Just update the version of the injected-wallets package package.json and the injected-wallets package within the package/demo/package.json

**Comment by Adamj1232** [comment]
@crazySadSoul you wont need to do that. The project used yarn workspaces so just bumping the version within the demo package and the injected-wallets package and running yarn will handle all that for you

**Comment by crazySadSoul** [comment]
> @crazySadSoul you wont need to do that. The project used yarn workspaces so just bumping the version within the demo package and the injected-wallets package and running yarn will handle all that for you

Hi, i've success test the project~~~. i want to create the PR next, but i dont have the permission to push. help~~~~

**Comment by crazySadSoul** [comment]
> @crazySadSoul you wont need to do that. The project used yarn workspaces so just bumping the version within the demo package and the injected-wallets package and running yarn will handle all that for you

Hi, i've success test the project~~~. i want to create the PR next, but i dont have the permission to push. help~~~~

**Comment by Adamj1232** [comment]
@crazySadSoul you will need to fork the project and create a PR from the fork of the project rather than pushing a branch. Are you familiar with forking github projects?

**Comment by crazySadSoul** [comment]
> @crazySadSoul you will need to fork the project and create a PR from the fork of the project rather than pushing a branch. Are you familiar with forking github projects?

ok, thanks, i see . its my first time to create pr :)

**Comment by crazySadSoul** [comment]
other question: why metamask dont have a package like @web3-onboard/xxx

**Comment by Adamj1232** [comment]
@crazySadSoul Awesome! Glad you are creating your first PR!
MetaMask is an injected only wallet, they dont have an SDK and their team or the community has not created a MM package. A separate MM package would only add the ability to see  the MetaMask option if a wallet wasnt available and then on click would take the user to MM download

**Comment by crazySadSoul** [comment]
> 

got it~~~~

**Comment by crazySadSoul** [comment]
> @crazySadSoul Awesome! Glad you are creating your first PR! MetaMask is an injected only wallet, they dont have an SDK and their team or the community has not created a MM package. A separate MM package would only add the ability to see the MetaMask option if a wallet wasnt available and then on click would take the user to MM download

Got it~~~~
