### ISSUE TITLE
[Bug]:  ValidationError: "txDetails.to" must be a string - when deploying contact

### ISSUE THREAD

**Issue by CherryDT** [blocknative/web3-onboard#1374]
### Current Behavior

Passing `to: null` (i.e. contract deployment) in the TX details to `preflightNotifications` results in an error `ValidationError: "txDetails.to" must be a string`.

### Expected Behavior

No error, contract getting deployed.

### Steps To Reproduce

Attempt deploying a contract using `to: null` in `preflightNotifications` - copy the example from docs and set `txDetails` to `to: null, data: contractDataHexHere, value: 0`.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.10.1

### Anything else?

I also tried setting it to an empty string but then the error says it's not allowed to be empty. I then tried setting it to the _string_ `'null'` but this results in `txDetails.data is not allowed`...

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@CherryDT thank you for reporting this, we will have a look shortly. 
For clarity you are using `preflightNotifications` for updates on your contract deployment?

**Comment by CherryDT** [comment]
Right. I was trying to run a contract deployment TX through this method. It works with regular transactions but with contract deployments it caused this error.

**Comment by Adamj1232** [comment]
@CherryDT thank you for the response. Upon initial release we did not have that usage in mind but will share your feedback with our product team and asses a follow up ticket for support. We will update here with that progress.

**Comment by Haoxiqiang** [comment]
same problem.
`TransactionPreview` check transaction as 
```
export interface TransactionObject {
    data?: string;
    from: string;
    gas?: string;
    gasLimit?: string;
    gasPrice?: string;
    to: string;
    chainId: number;
    value?: string;
    maxFeePerGas?: string;
    maxPriorityFeePerGas?: string;
    nonce?: string;
}
but deploy a contract `to` value is null or "0x"
I'm not sure how this should be used.
```

**Comment by ejc8** [comment]
@CherryDT and @Haoxiqiang - touching back, would this still be of use?

**Comment by ejc8** [comment]
Closing for now - if this becomes helpful again it can always be re-opened
