### ISSUE TITLE
[Bug]: "ValidationError: \"appMetadata.containerElements\" is not allowed"

### ISSUE THREAD

**Issue by Brentably** [blocknative/web3-onboard#1378]
### Current Behavior

Whenever I try to do a custom container element for my Account Center. I get this error: 
"ValidationError: \"appMetadata.containerElements\" is not allowed"

My appMetadata params are as follows:
`const appMetadata = {
  name: 'Connect Wallet Example',
  icon: '<svg>My App Icon</svg>',
  description: 'Example showcasing how to connect a wallet.',
  recommendedInjectedWallets: [
    { name: 'MetaMask', url: 'https://metamask.io' },
    { name: 'Coinbase', url: 'https://wallet.coinbase.com/' }
  ]
  ,containerElements: {accountCenter: 'div'}
}`

I've tried doing 'body' instead of 'div'. I've tried 'null' as well....

Repo is here: [https://github.com/Brentably/summon-lend-frontend/blob/main/src/index.tsx](https://github.com/Brentably/summon-lend-frontend/blob/main/src/index.tsx)

### Expected Behavior

I expected the account center to append to the first div element.

### Steps To Reproduce

just clone my repo as of me posting this and try this.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.10.1

### Node Version

19.0.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@Brentably `containerElements` is a top level prop and does not sit within `appMetaData`
An example can be seen [here](https://github.com/blocknative/web3-onboard/blob/96ddb7c81d641a037d11488299c75cde51901cff/packages/demo/src/App.svelte#L257)
Going to close this issue for now but feel free to continue the conversation here, thank for using web3-onboard and please feel free to reach out with any further questions!

**Comment by Adamj1232** [comment]
@Brentably oh yep you are correct, that hasn't been updated. Will get that in the next release. Thank you for flagging!
