### ISSUE TITLE
Re-connect to all wallet accounts

### ISSUE THREAD

**Issue by zned45** [blocknative/web3-onboard#1397]
Hi,

First, thank you for a great project.

I understand that is possible to pass the autoSelect parameter to connect to re-connect to a wallet, but this only connects one account of that wallet. I was wondering if there is a way to re-connect accounts of the wallet.

Thanks. 

Best.

**Comment by taylorjdawson** [comment]
Hey @zned45 thanks for this feature request! We have put it on our product road map and will update this issue as we progress on this feature.

**Comment by aaronbarnardsound** [comment]
Hey @zned45 there is not any current wallet provider API's (that we know of) that allow for requesting specific accounts to be connected, so the user will need to do that themselves manually. If a wallet implements an API that allows for that, we could look at implementing.
Closing this issue for now, but feel free to reopen if you know of a wallet API that has this functionality.
