### ISSUE TITLE
[Bug]: Style Border Radius hardcoded instead of variable

### ISSUE THREAD

**Issue by Dinuz** [blocknative/web3-onboard#1401]
### Current Behavior

the class connecting-container.svelte-1c0xedm has the border-radius defined as 24px (hardcoded value)

### Expected Behavior

the class connecting-container.svelte-1c0xedm should define the border-radius defined as --onboard-border-radius-1 variable, in order to easily manipulate it.

### Steps To Reproduce

Just look at the code

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

2.10.1

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@Dinuz I have a fix for this on a branch and should have it out shortly

**Comment by Dinuz** [comment]
@Adamj1232 Fantastic:))
