### ISSUE TITLE
[Bug]: Infinite Rendering Loop With React--Wallet Connect

### ISSUE THREAD

**Issue by Brentably** [blocknative/web3-onboard#1409]
### Current Behavior

I'm using @web3-onboard/react and @web3-onboard/walletconnect. This issue _only_ happens with wallet connect. It doesn't happen with any other wallet.

Whenever I click connect wallet, and scan the QR code from my rainbow app, or whatever wallet connect wallet I'm using, the wallet _does_ connect, but then the Wallet object seems to constantly update in an infinite loop, causing all sorts of re-renders and 429 calls to my APIs. 

I have a useEffect with a [wallet] dependency, which updates my global state with an asynchronous dispatch. 

Let me include a loom. 
[https://www.loom.com/share/3557ea703e9d4bcb85dd7b8f304a9651](https://www.loom.com/share/3557ea703e9d4bcb85dd7b8f304a9651)

### Expected Behavior

Expecting the wallet to connect, and not constantly update in an infinite loop.

### Steps To Reproduce

**Edit: Isolated the problem in this example repo:**
[https://github.com/Brentably/onboard-troubleshoot](https://github.com/Brentably/onboard-troubleshoot)

You can fork my repo here:
[https://github.com/Brentably/summon-lend-frontend](https://github.com/Brentably/summon-lend-frontend)

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

@web3-onboard/react: ^2.4.1

### Node Version

v18.12.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Brentably** [comment]
There was a line I was missing. My useEffect was calling an async function that was setting up the provider. 

`await provider.send("eth_requestAccounts", []);`

I had this line in there that I had copy pasted when I was building this thing, but it's actually sending a transaction / updating WalletState in some way, which triggers the useEffect.

As to why it only happens with wallet connect, I'm not sure.  I'll leave this open to see if anyone has any clues.

**Comment by aaronbarnardsound** [comment]
Hey @Brentably is there a reason you are calling the `eth_requestAccounts` method on the provider? Onboard takes care of that for you when you call the `connectWallet` function.

**Comment by Brentably** [comment]
Yeah, as I mentioned, it was just a line of code I had copy / pasted when I was developing (this is before I added web3onboard and was just building with injected metamask)

I know why there was an issue now, but do you know why it only happened with wallet connect? That definitely threw me off...

**Comment by aaronbarnardsound** [comment]
Ah I see. Yeah I am not sure why that would only happen with WalletConnect. My first guess would be that every time the request accounts method is called, WalletConnect must be emitting an `accountsChanged` event, whereas other wallets may not emit the event unless a new account is connected.

Closing this issue for now as there is no action needed on our end, but feel free to reopen if there is more info to add, or a bug that we need to fix.
