### ISSUE TITLE
[Bug]:  Mew Wallet Not showing as an option (latest one @web3-onboard/mew-wallet)

### ISSUE THREAD

**Issue by dweng0** [blocknative/web3-onboard#1428]
### Current Behavior

Pulled down react demo, checked that mew wallet was there:
![image](https://user-images.githubusercontent.com/5268627/207866559-c55e1f18-1a2b-4716-b12f-36f8a74de670.png)

Ran the application, but noticed that mew wallet doesn't show as an option:

![image](https://user-images.githubusercontent.com/5268627/207867284-915d8e21-136c-44ce-a05d-f96988655e7c.png)

### Expected Behavior

Mew wallet shows as an option

### Steps To Reproduce

1. pull down react demo
2. Run it (had https off)

### What package is effected by this issue?

@web3-onboard/mew

### Is this a build or a runtime issue?

Runtime, N/A

### Package Version

latest

### Node Version

16.15.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@dweng0 mew-wallet is a mobile only package as can be seen within the package [here](https://github.com/blocknative/web3-onboard/blob/a7d086e8eb6a8ded3ed04754a9baa8610c53b56c/packages/mew-wallet/src/index.ts#L9). MEW's new wallet product Enkrypt is their browser extension. Will close this issue for now but feel free to continue the conversation with any questions. Thanks!
