### ISSUE TITLE
[Feature]: Keycard support

### ISSUE THREAD

**Issue by willianpaixao** [blocknative/web3-onboard#1429]
### Is your request related to a problem?

As a Keycard user I can't connect to the web3 applications this library is used.

### Feature Description

Implement support for the [Keycard](https://keycard.tech/) wallet.

### Anything else?

I was initially redirected by the Gnosis team: https://github.com/safe-global/web-core/issues/1315

**Comment by willianpaixao** [comment]
cc @bitgamma @gravityblast @guylouis for visibility.

**Comment by Adamj1232** [comment]
@willianpaixao thanks for the feature request! Most of our wallet support packages are community driven at this point. If you or a member of the Keycard team would like to create a PR to extend support we would be happy to provide full assistance in the process. If this isn't an option we can create a card in the backlog but it could be a while before we get to it. Much faster route would be through PR. 
P.S. Dig the layout of your GH profile page 🔥

**Comment by guylouis** [comment]
thanks @willianpaixao 
unfortunately keycard can't connect with a web browser (using webHID for instance) when you're using a standard usb smart card reader 
we are actually working on a specific open source hardware device that will allow this type of use cases though

**Comment by Adamj1232** [comment]
@guylouis thank you for chiming in! Keycard looks super interesting and innovative! When your team is ready to integrate with Web3-Onboard please let us know and we can assist. Thank you! Closing issue for now.
