### ISSUE TITLE
[Bug]: Issue overriding CSS variable styles for a dark theme

### ISSUE THREAD

**Issue by 0xflumedev** [blocknative/web3-onboard#1432]
### Current Behavior

Button text colour is being ignored in favour of default web browser button color (black) when `--onboard-gray-700` or `--onboard-modal-color` is being set.

![image](https://user-images.githubusercontent.com/94210181/208004907-582203c4-cb11-4565-be33-55b402b69457.png)

![image](https://user-images.githubusercontent.com/94210181/208004980-48824b58-709c-496d-ae0f-7f29401b9be6.png)
![image](https://user-images.githubusercontent.com/94210181/208005063-1e469225-e734-42ec-a6ad-a800470e3a74.png)

### Expected Behavior

The button text variable should be honoured.

I actually think if you guys play with setting up a dark theme, you will find a few issues and lack of customisation. Truly button text should have it's own custom variable I think.

I'd also like to be able to turn off/control color for top (header) and bottom (footer) border colors really.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.12.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/94210181/208005523-e0c3ef2e-6907-4357-a1f3-444038db13c9.png)

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by 0xflumedev** [comment]
Also guys, hardcoded font sizes on the wallet name in the popup - causing a few headaches today, we have to manually override in node_modules 😔

![image](https://user-images.githubusercontent.com/94210181/208008722-78227631-0d56-48c0-9783-3342a1c6e6ca.png)

![image](https://user-images.githubusercontent.com/94210181/208008688-397c050d-e538-4204-bd95-1c435f129eef.png)

**Comment by Adamj1232** [comment]
@0xflumedev the CSS var target for the button text for selecting wallets is `--onboard-wallet-button-color` & `--onboard-wallet-button-color-hover`.
We use `rem` for font size so there is consistent font ratios throughout the lib/app which it inherits from the front-size of the root el. It would be challenging to provide and upkeep css vars for every font instance.

**Comment by Adamj1232** [comment]
If there are any other variables required to expose please feel free to note them here and I will discuss with the team.
We are in the process of developing themes to select from including a dark mode. We will update here when those are available.

**Comment by Adamj1232** [comment]
Opps looks like in the latest release those variables were accidentally deleted. Please use the previous version until we have a hot fix out.

**Comment by Adamj1232** [comment]
@0xflumedev this fix is available with the latest version of core `2.12.1-alpha.1` or the latest alpha tagged versions of react or vue packages if you use them. Thanks!

**Comment by Adamj1232** [comment]
This fix has been released with the latest Core, React and Vue packages. Please let me know if there are any other CSS variables causing issue
