### ISSUE TITLE
[Bug]: No mobile optimization for HD wallets connect interface

### ISSUE THREAD

**Issue by KarandeepSWranch** [blocknative/web3-onboard#1440]
### Current Behavior

The HD wallets connect interface is not responsive to screen dimensions and does not look good on smaller devices.

The below images are using the **[Keystone](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/packages/keystone)** and **[Trezor](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/packages/trezor)** packages:
- https://i.imgur.com/mUqgRjO.png
- https://i.imgur.com/lZ0P4UD.png

### Steps To Reproduce

Access the wallet connect modal on any device that has a smaller screen width than the HD Wallets connect interface width

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

^2.8.5

### Node Version

v18.12.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Anything else?

Didn't allow me to select the [hw-common](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard-develop/packages/hw-common) package but I guess that is probably what I should be referencing in regards to this issue.

**_Adam | Blocknative_**'s[ discord message](https://discord.com/channels/542403978693050389/1050488289775321148/1055240855478337646) regarding the issue.

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment]
@KarandeepSWranch Thanks for pointing that out! Our team is in the process of improving mobile exp for HW wallets. Will update the issue once we address this.

**Comment by Adamj1232** [comment]
@KarandeepSWranch you can keep an eye on these changes as they evolve with this PR - https://github.com/blocknative/web3-onboard/pull/1453

**Comment by Adamj1232** [comment]
Fixed in latest release of HW packages
