### ISSUE TITLE
[Bug]: Switching chain breaks when connected through Torus module

### ISSUE THREAD

**Issue by L03TJ3** [blocknative/web3-onboard#1446]
### Current Behavior

When connected with a Torus wallet after initial connection and wanting to switch chains, after confirming the switch in wallet the app gets stuck on switching status (see screens)

### Expected Behavior

Should be able to switch chains

### Steps To Reproduce

1. reproducible on https://reactdemo.blocknative.com/
2. locally I ran setChain hook while connected with torus

### What package is effected by this issue?

@web3-onboard/torus

### Is this a build or a runtime issue?

Runtime

### Package Version

2.12.1

### Node Version

16

### Anything else?

(local build)
![](https://cdn.discordapp.com/attachments/1050488289775321148/1060223080745676970/image.png)

(react-demo)

![](https://cdn.discordapp.com/attachments/1050488289775321148/1060224809084133446/image.png)

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @L03TJ3 thanks for the issue, we will take a look to see what might be happening here.

**Comment by L03TJ3** [comment]
Torus dev: _it seems like their example is using a custom infura connection which is being passed into our wallet.
that infura connection doesn't whitelist our domain and hence the example is failing_

Maybe you already found, but thought it good to share

**Comment by aaronbarnardsound** [comment]
Ah thanks for the additional info @L03TJ3

**Comment by Adamj1232** [comment]
@L03TJ3 We will look into this shortly. Escalating to our PM to find a timeline as this is blocking.

**Comment by aaronbarnardsound** [comment]
@L03TJ3 I am taking a look at this one now. Will post updates here shortly hopefully.

**Comment by aaronbarnardsound** [comment]
@L03TJ3 The fix for this has been merged in to develop. You can install the Torus alpha version package: `2.2.1-alpha.1` if need to get unblocked. A prod version will be out after it is packaged in to the next release which should happen within a week.
