### ISSUE TITLE
Add missing documentation for App Metadata

### ISSUE THREAD

**Issue by MeanBoyCousin** [blocknative/web3-onboard#1451]
The official documentation for [adding app metadata](https://onboard.blocknative.com/docs/getting-started/installation#app-metadata-optional) does not list of all the options available in the `AppMetaData` type. I only discovered the agreement section by digging into the source types. It would be good for future users if this documentation was complete.

**Comment by aaronbarnardsound** [comment]
@MeanBoyCousin thanks for pointing this out, we'll get those docs fixed up.

**Comment by Adamj1232** [comment]
@MeanBoyCousin you can find a full list of AppMetaData option [here](https://onboard.blocknative.com/docs/modules/core#options). I added a link to our appMetaData docs to the section you noted as well. Thanks for reporting!
Closing the issue for now.
