### ISSUE TITLE
[Question] Does w3o support Crypto.com Defi Wallet? Is it possible to integrate it?

### ISSUE THREAD

**Issue by kabaluyot** [blocknative/web3-onboard#1455]

**Comment by kabaluyot** [comment]
Yeah currently integrating it .. will open PR here soon

**Comment by taylorjdawson** [comment]
@kabaluyot Excellent! Looking forward to it!

**Comment by kabaluyot** [comment]
PR is up: https://github.com/blocknative/web3-onboard/pull/1499
