### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by inmarelibero** [blocknative/web3-onboard#1464]
### Current Behavior

Right after installing the library and following the [quickstart](https://github.com/blocknative/web3-onboard/tree/web3-onboard/2.3.0#quickstart) I'm getting the error `500 At least one chain must be set before attempting to connect a wallet`

I'm on Nuxt3, Vue3 and my code is pretty straightforward:

```
<script setup>

import Onboard from '@web3-onboard/core'
import injectedModule from '@web3-onboard/injected-wallets'
import { ethers } from 'ethers'

const MAINNET_RPC_URL = 'https://mainnet.infura.io/v3/...'

const injected = injectedModule()

const onboard = Onboard({
    wallets: [injected],
    chains: [
        {
            id: '0x1',
            token: 'ETH',
            label: 'Ethereum Mainnet',
            rpcUrl: MAINNET_RPC_URL
        }
    ]
})

const wallets = await onboard.connectWallet()

console.log(wallets)

</script>
```

### Expected Behavior

not getting the error `At least one chain must be set before attempting to connect a wallet`

### Steps To Reproduce

1. install Onboard
2. try the quickstart code https://github.com/blocknative/web3-onboard/tree/web3-onboard/2.3.0#quickstart

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.13.0

### Node Version

16

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
500
At least one chain must be set before attempting to connect a wallet

at ./app.js:40:78
at Module.withAsyncContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7558:21)
at setup (./app.js:40:47)
at _sfc_main.setup (./app.js:104:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7176:29)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7131:11)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:12)
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by inmarelibero** [comment]
the problem is due to the use of `<script setup>`, because using the `mounted()` function it works nicely

**Comment by Adamj1232** [comment]
@inmarelibero thank you for reporting a solution to this issue! I will close this issue as resolved with you fix above
