### ISSUE TITLE
[Bug]: Does not work in Deno.

### ISSUE THREAD

**Issue by jakubdonovan** [blocknative/web3-onboard#1481]
### Current Behavior
App fails to start properly due to `HTMLElement is not defined` when running on Deno. 

The problem is in `@web3-onboard/core/dist/index-b688f3fd.js`, it does this:
```ts
function init(options) {
    if (typeof window === 'undefined')
        return API;
```
this check returns false in Deno because we have window global variable and it tries to mount a DOM element instead of returning the API instance
if I change it to `if (typeof window === "undefined" || typeof Deno !== "undefined")` then the app starts up properly. This check should probably check for `typeof document !== "undefined"`

However, the above fix brings up another issue, where `Uncaught (in promise) ValidationError: "device" is not allowed` is logged to console when trying to connect with 
```ts
export const connect = async () => {
	const wallets = await onboard.connectWallet();
};
```

Minimal reproduction repo (branch web3): https://github.com/jakubdonovan/deno-sveltekit/tree/web3

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.9.0

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@jakubdonovan thanks for opening this issue!. We have pulled this issue into the sprint and will update here as progress is made

**Comment by jakubdonovan** [comment]
Appreciate it!

**Comment by ejc8** [comment]
Closing for now. Open to revisiting in the future
