### ISSUE TITLE
[Bug]: Readme.md links to localhost

### ISSUE THREAD

**Issue by parseb** [blocknative/web3-onboard#1487]
### Current Behavior

Invalid link.
https://github.com/blocknative/web3-onboard/blob/3bf7c486477ba05da0808150504c23d4419423d3/README.md?plain=1#L126

### Expected Behavior

Clicking "View demo app in browser" should deliver on its promise.

### Steps To Reproduce

1. Click on link.
2. Be disappointed.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

latest

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@parseb it will work following the above steps to start the demo locally. We have clarified the README and it will be updated shortly
