### ISSUE TITLE
[Bug]: When implementing custom injected wallet, it doesn't reconnect on refresh and doesn't logout

### ISSUE THREAD

**Issue by faillacec** [blocknative/web3-onboard#1491]
### Current Behavior

Web3Auth with OpenLogin implementation 
- Login with custom injected wallet
- Refresh browser
- Error You do not have any wallets installed that app support

const injectedGoogle = injectedModule({
  custom: [Google] //Web3Auth Google Provider
})

<img width="474" alt="Screenshot 2023-01-25 at 9 40 24 PM" src="https://user-images.githubusercontent.com/97037379/214746490-4c8ffdc9-19c7-4b23-a515-aadebc911f04.png">

### Expected Behavior

When refreshing browser, connect({autoselect: }) keep login or reconnect like other wallets

<img width="765" alt="Screenshot 2023-01-25 at 9 33 52 PM" src="https://user-images.githubusercontent.com/97037379/214745538-aa4d3391-7823-48ff-9d25-8f908c508b8f.png">

I appreciate your help
Thanks

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.4.0

### Node Version

16

### What browsers are you seeing the problem on?

Chrome, Safari

### Anything else?

Injected wallet implementation similar to current web3auth provider (@web3-onboard/web3auth) but using core not modal

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @faillacec can you please provide some more detailed code to reproduce this?

**Comment by faillacec** [comment]
Hey @aaronbarnardsound how are you doing? Yes  
I implemented this custom injected wallet (From Web3Auth) 
`import type {
	Chain,
	EIP1193Provider,
	ProviderAccounts,
} from "@web3-onboard/common";
import { web3AuthKey } from "../config";

const Google = {
		label: "Google",
        injectedNamespace: 'ethereum',
        checkProviderIdentity: ({ provider }) => !!provider,
		getIcon: async () => "/icons/google-logo.png",
		getInterface: async ({ EventEmitter, chains }) => {
			const { Web3AuthCore } = await import("@web3auth/core");
			const { OpenloginAdapter } = await import("@web3auth/openlogin-adapter");
			const { WALLET_ADAPTERS, CHAIN_NAMESPACES } = await import("@web3auth/base");
        
			const { createEIP1193Provider, ProviderRpcError, ProviderRpcErrorCode } =
				await import("@web3-onboard/common");

			const emitter = new EventEmitter();
			let [currentChain] = chains;

            const getChainConfig = ({
                rpcUrl,
                namespace,
                id,
                token,
                label
              }: Chain) => ({
                chainConfig: {
                  ticker: token,
                  tickerName: label,
                  chainId: id,
                  rpcTarget: rpcUrl,
                  chainNamespace:
                    namespace === 'evm'
                      ? CHAIN_NAMESPACES.EIP155
                      : CHAIN_NAMESPACES.OTHER
                }
              })

            const web3authCoreOptions = {
                clientId: web3AuthKey,
                ...getChainConfig(currentChain)
            }
			let web3authInstance = new Web3AuthCore(web3authCoreOptions);

			let openloginAdapterInstance = new OpenloginAdapter({
				loginSettings: {
					loginProvider: "google",
				},
			});

			web3authInstance.configureAdapter(openloginAdapterInstance);
			
			await web3authInstance.init();

            let provider: EIP1193Provider;

            let web3authProvider = await web3authInstance.connectTo(WALLET_ADAPTERS.OPENLOGIN, {
                mfaLevel: "default", // Pass on the mfa level of your choice: default, optional, mandatory, none
                loginProvider: "google", // Pass on the login provider of your choice: google, facebook, discord, twitch, twitter, github, linkedin, apple, etc.
            });            

			function patchProvider(): EIP1193Provider {
				const patchedProvider = createEIP1193Provider(web3authProvider, {
                    eth_selectAccounts: null,
					eth_requestAccounts: async ({ baseRequest }) => {
						try {
							const accounts = await baseRequest({
								method: "eth_accounts",
							});
                            
							return accounts as ProviderAccounts;
						} catch (error) {
							console.error(error);
							throw new ProviderRpcError({
								code: ProviderRpcErrorCode.ACCOUNT_ACCESS_REJECTED,
								message: "Account access rejected",
							});
						}
					},                    
					wallet_switchEthereumChain: async ({ params }) => {
                        const chain = chains.find(({ id }) => id === params[0].chainId)
                        if (!chain) throw new Error('Chain must be set before switching')
                        currentChain = chain
            
                        // re-instantiate instance with new network
                        web3authInstance = new Web3AuthCore({
                          ...web3authCoreOptions,
                          ...getChainConfig(currentChain)
                        })
            
                        await web3authInstance.init();
            
                        web3authProvider = await web3authInstance.connectTo(WALLET_ADAPTERS.OPENLOGIN, {
                            mfaLevel: "default", // Pass on the mfa level of your choice: default, optional, mandatory, none
                            loginProvider: "google", // Pass on the login provider of your choice: google, facebook, discord, twitch, twitter, github, linkedin, apple, etc.
                        }); 
            
                        emitter.emit('chainChanged', currentChain.id)
            
                        patchProvider()
            
                        return null
                      }
				})

				if (!provider) {
					patchedProvider.on = emitter.on.bind(emitter);
					patchedProvider.disconnect = () => web3authInstance?.logout();

					return patchedProvider;
				} else {
					provider.request = patchedProvider.request.bind(patchedProvider);

					// @ts-ignore - bind old methods for backwards compat
					provider.send = patchedProvider.send.bind(patchedProvider);

					// @ts-ignore - bind old methods for backwards compat
					provider.sendAsync = patchedProvider.sendAsync.bind(patchedProvider);

					return provider;
				}
			}

			provider = patchProvider();

			return {
				provider,
				instance: web3authInstance,
			};
		},
		// A list of platforms that this wallet supports
		platforms: ['all'],
}

export default Google;
` 

And added this to onboardInit 
`const injectedGoogle = injectedModule({
  custom: [Google]
})

const wallets = [web3auth, magic, walletConnect, coinbaseWalletSdk, injectedModule(), injectedGoogle];

const web3Onboard = init({
  wallets,
  chains,
  appMetadata: {
    name: "App",
    icon: '<svg>App Icon</svg>',
    description: "App"
  },
  i18n: {
    en: i18nWeb3OnBoardEN,
    es: i18nWeb3OnBoardES
  }
})
`
And this code seems to work ok when login. injected option appear in modal as google and i can login, but when page is refreshed session doesn't persist or when I tried to logout 

When refresh i call this method passing the walletConnected that was saved in local storage (this works for others wallets) but not with custom. I pass here 'Google'  the same name as label of custom login wallet

connect({autoSelect: walletConnected})

And to logout I use 
disconnect(wallet) 
this work for others wallets too

**Comment by aaronbarnardsound** [comment]
> `const wallets = [web3auth, magic, walletConnect, coinbaseWalletSdk, injectedModule(), injectedGoogle];`
That line might be causing issues as you are passing the injected module in twice. Try this instead:

`const wallets = [web3auth, magic, walletConnect, coinbaseWalletSdk, injectedGoogle];`

If that does not work, if you could link to a repo with this basic reproduction, then I can pull it down and take a look.

**Comment by Adamj1232** [comment]
@faillacec wanted to check in and see if your issue has been resolved? Thanks!

**Comment by Adamj1232** [comment]
@faillacec friendly 😄 ping on the above. We will close this issue at the end of the week if no response

**Comment by faillacec** [comment]
Hi @Adamj1232 yes i could solve the problem, with a custom module instead of injected, and some changes in the code.
Thanks for your time.

**Comment by Adamj1232** [comment]
@faillacec great to hear!  thank you!
