### ISSUE TITLE
[Feature]: Add Watch-Only input 

### ISSUE THREAD

**Issue by nicodelatorre7** [blocknative/web3-onboard#1507]
### Feature Description

Is only an input field to put an address and in the app you are logged in with this address but obviously you can't deposit, withdraw or pay, you can see the balance for example. 

You can see app.aave.com

<img width="412" alt="Captura de pantalla 2023-02-01 a la(s) 14 27 33" src="https://user-images.githubusercontent.com/44775737/216117763-19736621-8fb1-4ae9-a341-eed5ffe8595c.png">

**Comment by Adamj1232** [comment]
Chatted on discord about this but wanted to post here for tracking - This input doesn't really belongs as part of web3-onboard. The reasoning behind this decision is that onboard is used to abstract wallet providers for blockchain based interactions.
Adding an input to add a wallet address would only provide further complexity for your application and would only be a pass through for web3onboard.
An alternative approach for you could be an input with Track Wallet button and below that a Connect Wallet button. This may be better UX as well give clear delineation between the two actions.
