### ISSUE TITLE
[Bug]: Translations do not seem to be working on confirmation

### ISSUE THREAD

**Issue by alexkeating** [blocknative/web3-onboard#1524]
### Current Behavior

![217038330-d074c347-33a4-4583-ad78-769541273f62](https://user-images.githubusercontent.com/12705146/218635683-9301f101-393f-4975-8713-5a261b684549.png)

The text is not rendering in Chinese when we have that language set and have provided the i18 configuration 

### Expected Behavior

We expect the connect text be in Chinese.

### Steps To Reproduce

[Here](https://github.com/ScopeLift/umbra-protocol/blob/master/frontend/src/store/wallet.ts#L104) is our i18 configuration. The issue can be recreated by going to [Umbra](https://app.umbra.cash/) scrolling down and switching the language to Chinese and then attempting to login using the connect button

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.11.1

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by alexkeating** [comment]
Relevant issue https://github.com/ScopeLift/umbra-protocol/issues/449

**Comment by taylorjdawson** [comment]
@alexkeating oh wow! Thanks for pointing this out, I'll try and repro and see what's going on.

**Comment by taylorjdawson** [comment]
@alexkeating I wasn't able to reproduce 🤔 where in your code do you call `onboard.state.actions.setLocale`?

**Comment by alexkeating** [comment]
We don't use setLocale directly on onboard. We have been setting the locale below. I will add setting the locale on onboard and let you know if we are still running into issues.

https://github.com/ScopeLift/umbra-protocol/blob/cff346c2125af2097eece678f3cc625ea3310e6d/frontend/src/store/settings.ts#L72

**Comment by taylorjdawson** [comment]
@alexkeating is there a reason why you're using this method for setting the locale?

**Comment by alexkeating** [comment]
I think it is to set the locale for the whole app based on the Vue docs, added a link below. Also, added the onboard method and it seems to be working.

https://vue-i18n.intlify.dev/guide/essentials/scope.html#global-scope-1
