### ISSUE TITLE
[Bug]: I can't get the generated walletConnect uri

### ISSUE THREAD

**Issue by YordanMarchev** [blocknative/web3-onboard#1525]
### Current Behavior

When I open the modal I see in the console generated walletConnect uri but I can't get it because I want to use it another way

### Expected Behavior

I want to somehow get the generated walletConnect uri and use it.

### Steps To Reproduce

1. click connect
2. choose walletConnect
3. see the URI in the console but don't know how to get it 

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

"@web3-onboard/react": "^2.6.2",     "@web3-onboard/walletconnect": "^2.2.2",

### Node Version

16.14.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
wc:0d67c4bd-e4b5-4871-aea5-1dcbcb35ebc6@1?bridge=https%3A%2F%2Fu.bridge.walletconnect.org&key=508301c45cba6d6d76dff9b5d02d2b026a6f564961e108d707977fc1051aa97b
```

### Sanity Check

- [ ] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Hi @YordanMarchev - there is a Copy To Clipboard option at the bottom - is this what you are looking for?
Also important to note WalletConnect V1 is being sunset at the end of this month and will no longer be supported by the WC team.
We have worked with there team to create an alpha(`2.3.0-alpha.2`) release of the wallet connect package that can be easily configured to support WC V2 - please see https://www.npmjs.com/package/@web3-onboard/walletconnect/v/2.3.0-alpha.2
Official release will come out within the next 2 weeks after WalletConnect v1 deprecation

**Comment by YordanMarchev** [comment]
Hi @Adamj1232 
This is not my case
My case is that when the user is open the app from the phone I want to redirect him with a deep link without scanning the qr-code
But I need somehow to get the URI in the code and add it to the redirect url

**Comment by YordanMarchev** [comment]
So my question is:
 Can I somehow get the generated URI in the code and redirect the user without seeing the QR code?

**Comment by Adamj1232** [comment]
@YordanMarchev I will check with the WC team for a V2 implementation. 
This can be done in WalletConnect V1 but that is being sunset in 2 weeks so wouldnt be much help.

**Comment by YordanMarchev** [comment]
@Adamj1232 yea, it's will be better to have it in version 2

**Comment by YordanMarchev** [comment]
@Adamj1232 Do you have some new information?

**Comment by Adamj1232** [comment]
Can you describe the use case for passing the wallet URI out of web3-onboard to better understand the feature request?

**Comment by kraikov** [comment]
Hey @Adamj1232, we have a mobile wallet that we want to connect to a dApp that we're developing. The dApp will be accessed through a mobile phone, using an in-app browser from the mobile wallet. To connect the wallet to the dApp, the user needs to click on the "Connect wallet" button and choose wallet-connect. We aim to get the URI and make a deep link between the mobile wallet and the dApp without displaying the QR code.

**Comment by Adamj1232** [comment]
Hey @kraikov thank you for your patience! 
I have chatted with the team and we have a plan for a path forward. We will add a walletconnect module init option that will accept a function to handle/pass the walletconnect uri - this is the most dynamic and flexible path and can maintain our current patterns and avoid further eventEmitters - does this sound good to you?

**Comment by kraikov** [comment]
So the function will be called by you guys and the function will receive the uri? That would be ideal <3

**Comment by Adamj1232** [comment]
@kraikov yep you got it! Will have a PR to share shortly
