### ISSUE TITLE
Question About Types

### ISSUE THREAD

**Issue by Brentably** [blocknative/web3-onboard#1533]
[https://github.com/blocknative/web3-onboard/blob/develop/packages/core/README.md?plain=1#L215](https://github.com/blocknative/web3-onboard/blob/develop/packages/core/README.md?plain=1#L215)

Why are you omitting "expanded" on the types here? This is kind of confusing to me.

**Comment by Adamj1232** [comment]
@Brentably friendly ping on the above question

**Comment by Adamj1232** [comment]
@Brentably will go ahead and close if this issue isn't causing problems or needed as a feature request. Please feel free to continue chatting if anything should arise 😃
