### ISSUE TITLE
can it be integrated with purejs ?

### ISSUE THREAD

**Issue by developer-devo** [blocknative/web3-onboard#1541]
Hi there, can this be integrated with purejs ?

**Comment by Adamj1232** [comment]
Hi @developer-devo ! Web3-onboard is framework agnostic and should work within any front-end javascript language based programming. Are you referring to vanilla javascript as in no framework or a framework called purejs?

**Comment by developer-devo** [comment]
sorry for the framework confusion, one of our client wants to integrate this with simple html/js code. No framework to be used, I guess this should be possible. If yes, can you share link to the document for such integration ?

TIA
Rohit

**Comment by Adamj1232** [comment]
@developer-devo we dont have an example for vanilla/pure JS integration but it should be similar to integrating any other module you are familiar with. Import the packages in the script section and build out using the same API's as you would using for example svelte. The only difference would be in the handling of html and promises resolving. An example of that can be found [here](https://github.com/blocknative/web3-onboard/blob/develop/packages/demo/src/App.svelte) I will also get a ticket added to our backlog around creating a vanilla/pure javascript example together but it make take some time as most of our devs are participating in the EthDenver conference and we have a full backlog. I will update here with any progress. Please feel free to reach out with any questions or send a repo/code over. Thanks!

**Comment by Adamj1232** [comment]
@nickgreen5 - Blocknative engineer @leightkt is working on this currently and will update here when the example is available 🤓

**Comment by Adamj1232** [comment]
@nickgreen5 @developer-devo you can follow the progress of this example here: https://github.com/blocknative/web3-onboard/pull/1643/files#diff-1735cbf2dcd559179d664f8e1b05ea29e418b2c0cb45636266a5b23a023e8bf7

**Comment by nickgreen5** [comment]
Thank you for providing this example. However it doesn't work because it has missing file. I opened new issue https://github.com/blocknative/web3-onboard/issues/1664

**Comment by Adamj1232** [comment]
@nickgreen5 thank you for reporting. We will have a look shortly.
