### ISSUE TITLE
[Bug]: reconnect after disconnect

### ISSUE THREAD

**Issue by frankye23** [blocknative/web3-onboard#1545]
### Current Behavior

I use this code below to reconnect after i reload the page which works great.
`
connect: {
    autoConnectLastWallet: true
  },
`
But when i disconnect and reload my page, it also reconnect. Does that on purpose, or am i making mistake using the disconnect methods.
`
const onDisconnect = () => {
  disconnectConnectedWallet()
}
`

### Expected Behavior

reconnect after i reload but does not reconnect after i disconnect and reload

### Steps To Reproduce

disconnect -> reload

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

@web3-onboard/vue: "^2.5.2",

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment]
@frankye23 Hey! This is the expected behaviour as if the user explicitly wishes to disconnect their wallet from the dapp then it shouldn't reconnect the users app after the dapp reloads

**Comment by hans-crypto** [comment]
I can confirm that this is a bug. After using the "Disconnect Wallet" or "Disconnect all Wallets" button the library is not connected anymore. BUT the key `onboard.js:last_connected_wallet` (STORAGE_KEYS.LAST_CONNECTED_WALLET) is still in the local storage. So after a hard page reload the libraray will automatically reconnect again.

See here:  https://github.com/blocknative/web3-onboard/blob/8b84fc5dd5362253ee52789a078fd493e54bd9cf/packages/core/src/index.ts#L230-L242) {


My workaround for now is to listen to state changes and execute the following logic after a disconnect:
```
export function delLocalStore(key: string): void {
  try {
    localStorage.removeItem(key)
  } catch (error) {
    return
  }
}

delLocalStore('onboard.js:last_connected_wallet')
```

Cheers!

**Comment by aaronbarnardsound** [comment]
Ah ok it looks like @taylorjdawson misunderstood the report of current behaviour. We would expect it to remove the storage key when disconnect is called. We'll get a fix out for this and we can expose the types for the action type as well.
