### ISSUE TITLE
[Feature]: Option to exclude default fonts (Sofia Pro)

### ISSUE THREAD

**Issue by mendimr** [blocknative/web3-onboard#1550]
### Is your request related to a problem?

SofiaPro font included in bundle, increases the size by ~200kb.

### Feature Description

An option to not include it would be perfect, currently even if you don't use the font by setting the `--onboard-font-family-*` the font still gets included.

It would be awesome if we had an option to not include it on init and if there is no `--onboard-font-family-*` just set it to inherit.

**Comment by taylorjdawson** [comment]
Hey @mendimr! This is a great idea and we've added it to our backlog 👍🏾

**Comment by Adamj1232** [comment]
@mendimr we have pulled this into our current sprint and will update as progress is made.

**Comment by Adamj1232** [comment]
@mendimr this is available with our latest packages released today! Thanks again for the suggestion!
