### ISSUE TITLE
[Feature]: Custom derivative path for hardware wallets

### ISSUE THREAD

**Issue by 0xK3K** [blocknative/web3-onboard#1562]
### Feature Description

When using ledger, trezor or other hardware wallets, allow custom derivation path. Truly custom, not only the ones that ledger or trezor provide.

**Comment by aaronbarnardsound** [comment]
<img width="861" alt="Screen Shot 2023-03-02 at 10 56 00 am" src="https://user-images.githubusercontent.com/29873495/222294107-7838ae3c-d06a-4259-a54d-e9638330d1c8.png">

The hardware wallet UI allows for inputting a custom derivation path. Just click the base path dropdown and you should see it.

**Comment by Adamj1232** [comment]
@0xK3K did you happen to see Aaron's message above? The modal will display for Trezor, Keepkey and other HD wallets except for Ledger which we use their SDK for wallet interaction.

**Comment by Adamj1232** [comment]
Closing as the issue is stale and there hasnt been response. Feel free to open if the issue persists.
