### ISSUE TITLE
[Bug]: Infinity Wallet Build Error

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/web3-onboard#1564]
### Current Behavior

Error in the console regarding import extensions that stops Onboard from working:

```
Uncaught (in promise) TypeError: Failed to resolve module specifier "@web3-react/types". Relative references must start with either "/", "./", or "../"
```

### Expected Behavior

No error and Onboard works as expected.

### Steps To Reproduce

1. Add infinity wallet to a sveltekit project
2. Build
3. Preview
4. See error in console and Onboard not working

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

Infinity v2.0.0

### Node Version

16.0.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught (in promise) TypeError: Failed to resolve module specifier "@web3-react/types". Relative references must start with either "/", "./", or "../"
```
```


### Anything else?

_No response_

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Working in latest docs!
