### ISSUE TITLE
[Bug]: Cannot mix different versions of joi schemas w/ SvelteKit + Vite and pnpm - Request to export types through Core

### ISSUE THREAD

**Issue by beeb** [blocknative/web3-onboard#1567]
### Current Behavior

Runtime error:

```
Error: Cannot mix different versions of joi schemas
    at new module.exports (node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports (node_modules/@hapi/hoek/lib/assert.js:21:11)
    at Object.exports.isSchema (node_modules/joi/lib/common.js:132:5)
    at Object.internals.schema (node_modules/joi/lib/compile.js:66:16)
    at Object.exports.schema (node_modules/joi/lib/compile.js:17:26)
    at internals.Base.$_compile (node_modules/joi/lib/base.js:646:24)
    at node_modules/joi/lib/types/keys.js:262:92
    at Object.exports.tryWithPath (node_modules/joi/lib/common.js:176:16)
    at internals.Base.method [as keys] (node_modules/joi/lib/types/keys.js:262:32)
    at Object.args (node_modules/joi/lib/types/keys.js:49:23)
```

### Expected Behavior

Page should work (it does with the following package versions):

- @web3-onboard/common: 2.2.3
- @web3-onboard/core: 2.14.1
- @web3-onboard/injected-wallets: 2.6.2
- @web3-onboard/walletconnect: 2.2.2

### Steps To Reproduce

1. Clone https://github.com/beeb/lp-rescue-frontend
2. Run `pnpm build` and `pnpm preview` to see that everything works
3. Run `pnpm update` to get the update to the latest version of web3-onboard packages
4. Run `pnpm build` and `pnpm preview` to see a 500 error

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

- @web3-onboard/common: 2.2.3
- @web3-onboard/core: 2.15.4
- @web3-onboard/injected-wallets: 2.8.1
- @web3-onboard/walletconnect: 2.3.1

### Node Version

16.19

### Relevant log output

```shell
Error: Cannot mix different versions of joi schemas
    at new module.exports (node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports (node_modules/@hapi/hoek/lib/assert.js:21:11)
    at Object.exports.isSchema (node_modules/joi/lib/common.js:132:5)
    at Object.internals.schema (node_modules/joi/lib/compile.js:66:16)
    at Object.exports.schema (node_modules/joi/lib/compile.js:17:26)
    at internals.Base.$_compile (node_modules/joi/lib/base.js:646:24)
    at node_modules/joi/lib/types/keys.js:262:92
    at Object.exports.tryWithPath (node_modules/joi/lib/common.js:176:16)
    at internals.Base.method [as keys] (node_modules/joi/lib/types/keys.js:262:32)
    at Object.args (node_modules/joi/lib/types/keys.js:49:23)
```

### Anything else?

Seems like a regression of https://github.com/blocknative/web3-onboard/issues/1287

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Hey @beeb I am unable to recreate the error described with the steps provided.
Try removing the @web3-onboard/common package from your package.json as it is not needed and is imported by the packages that require it.

**Comment by beeb** [comment]
Hi @Adamj1232 thanks for the reply! I'm using the `Chain` type from the common package to make my interfaces typesafe. What's an alternative way I could import that type without the common package?

**Comment by beeb** [comment]
I confirm that removing `@web3-onboard/common` solves the issue. If I could get the `Chain` type from somewhere else it would be helpful. Does any of the other packages re-export it?

**Comment by Adamj1232** [comment]
@beeb you should still be able to access @web3-onboard/common after removing from your package.json as it is a dep of @web3-onboard/common package. Are you seeing an error when importing that type?

**Comment by beeb** [comment]
I checked which version is used by `@web3-onboard/core` and it appears right now it's `@web3-onboard/common@2.2.3` so I pinned the version to 2.2.3 and it works for now. But you guys should ideally fix this! 

At least have your packages depend on the latest version of `common`.

**Comment by Adamj1232** [comment]
Ah makes sense, we will update Core to export all the types from common so this wont be required in the future.
Agreed it isnt an ideal fix but common doesnt change often and we will have the types exported through Core shortly

**Comment by beeb** [comment]
After testing with a different system (WSL2), I still have the error even if I pin the version of the `common` package. I was testing on macOS and I thought for some reason I fixed it but it might have been a fluke.

Anyway, although it's not a fix for the issue, exporting the types from Core will help me in my particular use case.

**Comment by beeb** [comment]
@Adamj1232 You are right, problem only happens with `pnpm`.

**Comment by Adamj1232** [comment]
Upon thinking on this issue a bit more of the importing of @web3-onboard/common for type usage...that package should be imported within devDependencies in the package.json rather than the dependencies object.

**Comment by beeb** [comment]
Yes anyway with sveltekit all packages are in devdependencies since vite does all the bundling in the end.

**Comment by Adamj1232** [comment]
We have pinned the joi versions so all the latest packages will employ the same versions of joi and remove this error.
