### ISSUE TITLE
[Feature]: Add Sepolia test net to the supported chains 

### ISSUE THREAD

**Issue by lewis-kori** [blocknative/web3-onboard#1598]
### Feature Description

I noticed that Sepolia test net is not in the list of supported chains by web3-onboard. Is this something you plan to add to the library? If yes, is it easy to implement? I could do it but I'm not familiar with the source code and I would like to know if it is feasible :)

Here's the list of supported chains (defined [here](https://github.com/blocknative/web3-onboard/blob/develop/packages/core/src/utils.ts#L114-L131)):

```sh
export const chainIdToLabel: Record<string, string> = {
  '0x1': 'Ethereum',
  '0x3': 'Ropsten',
  '0x4': 'Rinkeby',
  '0x5': 'Goerli',
  '0x2a': 'Kovan',
  '0x38': 'Binance',
  '0x89': 'Polygon',
  '0xfa': 'Fantom',
  '0xa': 'Optimism',
  '0x45': 'Optimism Kovan',
  '0xa86a': 'Avalanche',
  '0xa4ec': 'Celo',
  '0x14a33': 'Base Goerli',
  '0x64': 'Gnosis',
  '0x63564C40': 'Harmony One',
  '0xa4b1': 'Arbitrum'
}
```

**Comment by leightkt** [comment]
@lewis-kori Thanks for the suggestion! We'll take a look!
