### ISSUE TITLE
[Bug]: -react/core: 6.1.9 (latest) and -onboard/core 2.15.5 (latest) - compatibility issue

### ISSUE THREAD

**Issue by dweng0** [blocknative/web3-onboard#1610]
### Current Behavior

Hey all, did a minor/patch upgrade for our web3onBoard dependencies:
![image](https://user-images.githubusercontent.com/5268627/228192276-011ceb93-623a-44dc-9b93-d9ec23e644ac.png)

This compile error now occurs.

```
 Types of property 'accounts' are incompatible.
                Type 'import(".../node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").Account[]' is not assignable to type 'import(".../node_modules/@web3-onboard/core/dist/types").Account[]'.
```

```
Property 'uns' is missing in type 'import(".../node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").Account' but required in type 'import(".../node_modules/@web3-onboard/core/dist/types").Account'.
```

The problem:
Please correct me if I'm wrong. But there seems to now be a discrepancy between (web3)react/core and web3/core  Account Types? Where as they were effectively the same (or shared) before? 

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Build

### Package Version

2.15.5

### Node Version

16.15.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
The types returned by 'connectWallet(...)' are incompatible between these types.
        Type 'Promise<import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").WalletState[]>' is not assignable to type 'Promise<import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/core/dist/types").WalletState[]>'.
          Type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").WalletState[]' is not assignable to type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/core/dist/types").WalletState[]'.
            Type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").WalletState' is not assignable to type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/core/dist/types").WalletState'.
              Types of property 'accounts' are incompatible.
                Type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").Account[]' is not assignable to type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/core/dist/types").Account[]'.
                  Property 'uns' is missing in type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/react/node_modules/@web3-onboard/core/dist/types").Account' but required in type 'import("C:/Projects/Phuture/phuture-web-app/node_modules/@web3-onboard/core/dist/types").Account'.  TS2345
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@dweng0 latest version of `@web3-onboard/react` is 2.6.6, not 2.5.1. Can you try that version and let me know how it goes?
It looks like `@web3-onboard/core` was updated to the latest minor/patch appropriately. 
Did you run a command to do this?

**Comment by Adamj1232** [comment]
@dweng0 did this work for you? Will close tomorrow if no response as this seems to be a situation of mis-aligned versions

**Comment by dweng0** [comment]
Hey, haven't had a chance to look im afraid, please close and I'll circle back to this with more detailed info if it doesn't work. Thanks guys 🙏

**Comment by Adamj1232** [comment]
Closing as this issue seems to be resolved
