### ISSUE TITLE
[Bug]: Docs Broken Link

### ISSUE THREAD

**Issue by finessevanes** [blocknative/web3-onboard#1615]
### Current Behavior

When I'm in https://onboard.blocknative.com/docs/wallets/injected#install, I click on [recognizes many injected wallets natively](https://onboard.blocknative.com/docs/packages/injected#injected-wallets-supported-natively) and I'm getting a 404 error.

### Expected Behavior

I click on [recognizes many injected wallets natively](https://onboard.blocknative.com/docs/packages/injected#injected-wallets-supported-natively) and it takes me to the page it's referencing.

### Steps To Reproduce

1. Go to https://onboard.blocknative.com/docs/wallets/injected#install
2. Click on [recognizes many injected wallets natively](https://onboard.blocknative.com/docs/packages/injected#injected-wallets-supported-natively)
3. See 404 error

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

n/a

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@finessevanes thank you for reporting! This will be fixed shortly
