### ISSUE TITLE
[Bug]: Cannot find module '@hapi/hoek/assert' - when running tests

### ISSUE THREAD

**Issue by mario-iliev** [blocknative/web3-onboard#1629]
### Current Behavior

I receive this error when I run the project test suits. It happened after I updated to latest version of these packages:

```
@web3-onboard/coinbase - 2.2.1
@web3-onboard/core - 2.16.1
@web3-onboard/injected-wallets 2.8.3
@web3-onboard/ledger - 2.4.3
@web3-onboard/react - 2.7.1
@web3-onboard/trezor - 2.3.4
@web3-onboard/walletconnect - 2.3.4
```

 All tests which have imports referencing something from web3-onboard receive this error:

```
Cannot find module '@hapi/hoek/assert' from 'node_modules/joi/lib/index.js'

Require stack:
  node_modules/joi/lib/index.js
  node_modules/@web3-onboard/common/dist/validation.js
  node_modules/@web3-onboard/common/dist/index.js
  node_modules/@web3-onboard/injected-wallets/dist/wallets.js
  node_modules/@web3-onboard/injected-wallets/dist/index.js
  src/_constants/wallets.js
  src/utils/utils.js
  src/utils/file-one.js
  src/utils/file-one.test.js

  at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
  at Object.<anonymous> (node_modules/joi/lib/index.js:3:16)
```

I think this is the third time I have problems with wrong/missing/bad packages when updating "web3-onboard" versions. It'll be great to have some sort of test to catch such problems before release. Sorry for not being able to give reproducable example.

### Expected Behavior

Packages to work in "test" environment.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.16.1

### Node Version

16.14.2

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@mario-iliev it looks like this is a[ bug noted by the Joi team and fixed in a more recent version](https://github.com/hapijs/joi/issues/2917). We will update our internal Joi versions to resolve this issue. Apologies for the inconvenience.
What frameworks(name/version) and compiler/bundlers are you using and seeing this issue in? 
I ask because this issue did not arise in our lib of frameworks we use to test release.

**Comment by mario-iliev** [comment]
> 

Sorry that I missed this info. React JS, always latest version with Webpack 5. I like to be early adopter of latest of the latest so I'm used to find problems in new releases :)

**Comment by Adamj1232** [comment]
@mario-iliev no worries and thank you for reporting! A fix for this issue has been published and is available with the latest package versions. Let me know if you have any issue with those! thanks again!
