### ISSUE TITLE
MaxListenersExceededWarning when I try to init contract in Goerli chain.

### ISSUE THREAD

**Issue by Chocopieca** [blocknative/web3-onboard#1631]
### Current Behavior

I init web3 instance by using web3-onboard/core with Goerli chain in options.
After that I try to init my smart contract by this instance.

When I push my connect button, I get MaxListenersExceededWarning in my console.
![image](https://user-images.githubusercontent.com/48634382/230354147-c7297851-c3a3-4e94-9019-890515393636.png)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 "message" listeners added. Use emitter.setMaxListeners() to increase limit.
And I get error TypeError: Resolution is not a constructor:
![image](https://user-images.githubusercontent.com/48634382/230355576-7ff868ee-71b0-4f77-b894-1bc2f92a21e9.png)

After that tab freezes, my vue dev tools don't updates and somtimes dev tools enables debug mode.

My logs:
[localhost-1680776884854.log](https://github.com/blocknative/web3-onboard/files/11169925/localhost-1680776884854.log)

### Steps To Reproduce

1. I init onboarding from web3-onboard/core with this options:
`{
wallets: [injected, fortmatic],
chains:{
          id: "0x5",
          token: "ETH",
          label: "Goerli",
          rpcUrl: "https://eth-goerli.public.blastapi.io",
        },
       appMetadata: {
        name: "MyProject",
        icon: logo,
        logo: logo,
        description: "Project using Onboard",
        recommendedInjectedWallets: [
          { name: "Coinbase", url: "https://wallet.coinbase.com/" },
          { name: "MetaMask", url: "https://metamask.io" },
        ],
      },
}`
2. Toggle connectWallet and setChain with value 5
3. After gat web3 instance I try to init contract by eth.Contract with abi and address.
4. I catch my problem.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

9.4.0

### Node Version

v16.17.1

### Anything else?

It happans on all browsers.
I tried to increase the listeners limit but unfortunately, it is not working.
If I use another chain, this problem does not occur.

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @Chocopieca the `Resolution is not a constructor` error might be the problem here. Could you try turning it off via the init options to onboard to confirm that is the case or not:

```javascript
const onboard = web3Onboard({
  // .... other options
  connect: {
    disableUDResolution: true
  }
})
```

Also which bundler are you using with Vue? If you are using Vite, check out our docs for [Vite build environments](https://onboard.blocknative.com/docs/modules/core#vite) as this is likely an issue with module resolution.

**Comment by Chocopieca** [comment]
I set disableUDResolution to true but it doesn't resolve my problem. I steel catch MaxListenersExceededWarning.

I use vite build evironments from your doc and catch "node_modules/crypto-js/core.js:53:30: ERROR: Could not read from C:/path-for-project/crypto-browserify".
After I set alias "crypto: 'crypto-browserify'" build script try to require crypto in this path with doesn't exist.
![image](https://user-images.githubusercontent.com/48634382/231545746-d3a71825-303d-4c50-b31d-54fccf7d9c48.png)
Am I doing something wrong?
My problem still happens.

For test I use a common usdt contract from google search.

**Comment by Chocopieca** [comment]
[Adamj1232](https://github.com/Adamj1232) Yes, I tried this example and still catch Listeners warning and tab freeze.
When I connect to Metamask, everyone is going well, but when I initiate usdt contract I catch this problem.

I tried to use vite expended example from doc and I tried to use vite code from react project.
I rework my code with example from vue3 project.
Now I use sepolia chain, it works fine, but I want to use goerli in the future.

**Comment by kennyyS** [comment]
@Adamj1232, is it possible to provide an example with Nuxt3 stable version with vite, I am blocked with the same issue of  @Chocopieca...

<img width="530" alt="Screen Shot 2023-04-17 at 22 37 03" src="https://user-images.githubusercontent.com/7330705/232593651-fc2acc57-87fa-417c-b68b-686522ac76a8.png">

**Comment by Adamj1232** [comment]
@Chocopieca Might try a look at #1645 for possible resolution. Looks like you are missing dep. 
Also, the contract should have no affect on web3-onboard as we do not alter or perform any actions on contract calls.

**Comment by Adamj1232** [comment]
@Chocopieca If you are able to send a stackblitz or way to reproduce this issue that would be helpful as I am unable to reproduce this locally. We don't do any contract interaction manipulation so I dont think this is an issue within onboard. Can you confirm all dev-deps have been added?

**Comment by kennyyS** [comment]
Working well on my side - if I can help tell me @Adamj1232 using also Vite and Vue3
