### ISSUE TITLE
MetaMask connection language is very misleading

### ISSUE THREAD

**Issue by wbt** [blocknative/web3-onboard#1632]
### Current Behavior

Language presented in the user interface emphasizes a desirable but not actually supported feature of connecting multiple accounts.

### Expected Behavior

When the interface says "Make sure to select all accounts that you want to grant access to" and lets me select multiple accounts to grant access, I expect the Dapp to get an `accounts[ ]` array with all of those accounts, not just one of them.

### Steps To Reproduce

1. Visiting a site that supports useful functionality from having multiple accounts connected, and which uses this Onboard library.
2. Click to connect and choose to connect to MetaMask as the wallet.
3. See a screen like this (site logo redacted as it's a general issue): 
![image](https://user-images.githubusercontent.com/563406/230470464-c9441774-ff10-43f2-95dc-241f562f2c6f.png)
4. Note the language "Make sure to select all accounts that you want to grant access to."
5. Notice that the MetaMask interface also strongly supports allowing you to select multiple accounts for connecting to a site, emphasizing selection of multiple accounts: 
![image](https://user-images.githubusercontent.com/563406/230475898-1da3e285-308d-442b-a3f7-7d9458e5354c.png)
7. Select multiple accounts.
8. Confirm that you are connecting multiple accounts, for example:
![image](https://user-images.githubusercontent.com/563406/230476102-dac8dd5f-1ecb-4565-bef9-ee7c0526422d.png)
9. The site code gets the wallet object but the accounts array is just length 1, always.  See [this comment](https://github.com/blocknative/web3-onboard/issues/1219#issuecomment-1221030555) in this repo and [this documentation in MetaMask](https://docs.metamask.io/guide/accessing-accounts.html#accessing-accounts):   

> If the first account in the returned array isn't the account you expected, you should notify the user! In the future, the accounts array may contain more than one account. This functionality isn't available yet. The first account in the array will always be considered the user's "selected" account.

Ideally, MetaMask would also fix this UI issue and not lead users to think they can meaningfully connect multiple accounts to the same site when MetaMask will only ever pass the first selected account (according to ordering the user can't control, especially if currently using a non-connected account) to the site.  However, the current behavior is [intentional](https://github.com/MetaMask/metamask-extension/issues/3207) and unlikely to be changed anytime soon (it's closed "wontfix" and MetaMask's own misleading interface is unlikely to be updated in the near future either).  

The Onboard library can at least not make the problem so much worse by giving this bad advice to users.  Maybe replace this language with something more accurate, ideally even helping users overcome Metamask's misleading UI. A strawman example that is better than the status quo but could still be improved: "MetaMask can only present one account, so connect just the one account you want. If the account you have currently active in MetaMask is not connected, you have no way to control which of multiple connected accounts MetaMask will actually connect."  

### What package is effected by this issue?

@web3-onboard/injected

### Is this a build or a runtime issue?

Runtime

### Package Version

@web3-onboard/injected-wallets@2.8.2

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aaronbarnardsound** [comment]
Hey @wbt thanks for the feedback. Yeah ideally MetaMask would return an array with all of the connected accounts, so that we could display them all as connected, but there is still a good reason as to why we have worded the message the way it is. 

If you grant access to a single account via MetaMask when connecting to Onboard, and then switch accounts in the MM UI, Onboard will not pickup the account change as MM does not fire an event when you switch to an account that permissions have not been granted for. This led to users being confused as to why their account is not showing up and a lot of support requests. 

If you instead grant permissions to multiple accounts (as instructed in the text), then when you switch accounts in MM, the change is picked up by Onboard. Notice that the wording: 
> "Make sure to select all accounts that you want to **grant access** to." 

refers to granting access, not connecting.

I don't think your suggestion is an improvement on the default text here, but if you would like to change it in your app, then you can customise it by modifying the text [here](https://github.com/blocknative/web3-onboard/blob/e92a3231852374c0238ca2e580897efb063c19c3/packages/core/src/i18n/en.json#L27) using the [i18n option](https://onboard.blocknative.com/docs/modules/core#i18n) in your init object.

**Comment by wbt** [comment]
The language I proposed might not be the best answer, but the wording "grant access to" seems like ti would actually grant access, reinforced by the "connect" language that this Onboard screen brings up in MetaMask- it's not unreasonable for especially novice users to assume those are the same thing.  Maybe it could be improved adding a sentence to the existing text like "Note that you can only select one account at a time to actually be connected, and later use the MetaMask account selector to change between connected accounts." Again, further refinement seems likely possible.

**Comment by aaronbarnardsound** [comment]
Yes updating in the i18n will show for all wallets and that would also be the case if we were to update the default text. If you would like to display something different to your users, you can customise as you see fit :)

**Comment by wbt** [comment]
Can the language be made different for different wallets?

**Comment by aaronbarnardsound** [comment]
Not currently. I think we could pass the wallet label in to the `translate` function to make that possible though.

**Comment by Adamj1232** [comment]
@wbt this ability has been release with the latest versions of the core/react/vue packages and documentation around how to use this functionality can be found [here](https://onboard.blocknative.com/docs/modules/core#i18n). Thank you for reporting!

**Comment by wbt** [comment]
Thanks much!  There may need to be an update to the types as well to allow partial overrides as suggested in the documentation.

I think the core fix will likely wind up looking something like [this](https://github.com/blocknative/web3-onboard/pull/1661), which works for me locally.
