### ISSUE TITLE
[Feature]: Allow z-index control

### ISSUE THREAD

**Issue by wbt** [blocknative/web3-onboard#1634]
### Is your request related to a problem?

A particular Dapp uses a Material UI DateRangePicker which, when empty, includes a label that is styled with a `z-index: 1` property by Material UI.  When using Onboard to connect an account and then clicking to "Disconnect all Wallets" there is a popup which looks like this: 
![image](https://user-images.githubusercontent.com/563406/230489741-20696f63-0a57-45ff-9e43-e5d1ce624d3a.png)

Unfortunately, that comes *under* the labels. It would be nice to have a non-hacky way to set the z-index to correct this, but I'm not seeing how.  

In documentation there's a note that says "please see containerElement usage [here](https://github.com/blocknative/web3-onboard/blob/8531a73d69365f7d584320f1c4b97a5d90f1c34e/packages/demo/src/App.svelte#L227)" but the link doesn't show an example of containerElement usage and there isn't a property there for the disconnect confirmation modal.  Specifying a containerElement for accountCenter seems likely to have other undesired effects for dropping the positioning of that.  

### Alternative Solutions

Within the shadow-root the top-level `div.container` has a property 
```css
.z-indexed.svelte-1mvm68y {
    z-index: var(--account-center-z-index);
}
```
and overriding this value (via dev tools) with '2' works fine, but there's not a documented way to do this programmatically.

**Comment by wbt** [comment]
This really is just a simple documentation issue - after more searching, I did find you can just put 
```css
:root {
	--account-center-z-index: 2;
}
```
in the application's css file and that takes care of it.
Filing this issue makes it easier to find the solution, but a documentation update could make it even easier.

**Comment by aaronbarnardsound** [comment]
For all modals you should be able to use the `--onboard-modal-z-index` CSS variable.
[Docs](https://onboard.blocknative.com/docs/getting-started/custom-styling#css-custom-properties-variables)
