### ISSUE TITLE
trezor-connect version 8 has been deprecated warnings

### ISSUE THREAD

**Issue by alyavasilyeva** [blocknative/web3-onboard#1652]
### Current Behavior

We've switched from `bnc-onboard` to `web3-onboard` recently and now we see `trezor-connect version 8 has been deprecated. Pease start using @trezor/connect version 9 https://www.npmjs.com/package/@trezor/connect` warnings on Sentry.
We were able to reproduce it on localhost too, by trying to connect Trezor wallet.

### Expected Behavior

No warnings

### Steps To Reproduce

1. @web3-onboard/core ^2.16.2, @web3-onboard/trezor ^2.3.5,
2. Mainnet on Goerli network (did not test with others)
3. Choose Trezor when you connect a wallet
4. Click `Scan Accounts` to find addresses
5. Check console, you should see the warning now

### What package is effected by this issue?

@web3-onboard/trezor

### Is this a build or a runtime issue?

Runtime

### Package Version

^2.16.2

### Node Version

16.18.1

### What browsers are you seeing the problem on?

Chrome

### Anything else?

I don't know if it breaks anything since I don't have a Trezor wallet to test, but it is not hard to upgrade it would be awesome 🙂 
<img width="1162" alt="Screenshot 2023-04-20 at 19 11 56" src="https://user-images.githubusercontent.com/27780611/233409699-78c89899-816b-47a5-9d35-c36b82ac1f0a.png">

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
Thanks so much for bringing this to our attention! The team will take a look as soon as possible.

**Comment by Adamj1232** [comment]
@alyavasilyeva this has been updated with the latest alpha version of the Trezor package and will be officially released after some testing shortly

**Comment by alyavasilyeva** [comment]
@Adamj1232 great, thank you for your quick response!

**Comment by Adamj1232** [comment]
@alyavasilyeva this has been updated with v2.3.6 of the Trezor package. Thank you for reporting this issue
