### ISSUE TITLE
Failure mode for Coinbase Wallet is not smooth

### ISSUE THREAD

**Issue by wbt** [blocknative/web3-onboard#1662]
### Current Behavior

When a user visits a site using this library and clicks to use Coinbase Wallet but doesn't have that extension activated, there is an ugly "Uncaught ReferenceError: Buffer is not defined."

### Expected Behavior

More elegant handling of the error, perhaps with a message that Coinbase Wallet was not found, click here to manage extensions if you have it installed but not activated, click here to install it, etc. 

### Steps To Reproduce

In Chrome, have MetaMask and Coinbase Wallet installed.
Visit chrome://extensions/ to disable Coinbase Wallet because of its nasty habit of taking precedence over MetaMask on sites where you really want to use MetaMask.
Create a sample React app with Web3-onboard and Coinbase wallet as one of the options.  
Run `yarn start` to run the app in dev mode.
Visit the app and click to try to use Coinbase Wallet
See an ugly compilation error pop up over the screen.

It's better in a production build, but the error is still in the console and the message shown to the user might leave them wondering why it's not working. 

### What package is effected by this issue?

@web3-onboard/coinbase

### Is this a build or a runtime issue?

Runtime

### Package Version

"@web3-onboard/coinbase": "^2.2.2", "@web3-onboard/core": "^2.17.0"

### Node Version

N/A

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
QRCode.js:27 Uncaught ReferenceError: Buffer is not defined
    at Object.__ (QRCode.js:27:1)
    at w (index.js:492:1)
    at Array.forEach (<anonymous>)
    at b (index.js:418:1)
hostReportError.ts:8 Uncaught ReferenceError: Buffer is not defined
    at Object.__ (QRCode.js:27:1)
    at w (index.js:492:1)
    at Array.forEach (<anonymous>)
    at preact__WEBPACK_IMPORTED_MODULE_0__.options.__r (index.js:51:1)
    at L (index.js:208:1)
    at x (children.js:141:1)
    at N (index.js:435:1)
    at L (index.js:260:1)
    at x (children.js:141:1)
    at N (index.js:435:1)
(anonymous) @ QRCode.js:27
w @ index.js:492
preact__WEBPACK_IMPORTED_MODULE_0__.options.__r @ index.js:51
L @ index.js:208
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
L @ index.js:219
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
N @ index.js:435
L @ index.js:260
x @ children.js:141
L @ index.js:219
x @ children.js:141
L @ index.js:219
B @ render.js:16
(anonymous) @ LinkFlow.js:77
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:266
SafeSubscriber.next @ Subscriber.ts:208
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
BehaviorSubject._subscribe @ BehaviorSubject.ts:28
Observable._trySubscribe @ Observable.ts:239
Subject._trySubscribe @ Subject.ts:117
Observable.subscribe @ Observable.ts:218
render @ LinkFlow.js:73
open @ LinkFlow.js:62
requestEthereumAccounts @ WalletSDKUI.js:55
(anonymous) @ WalletSDKRelay.js:640
requestEthereumAccounts @ WalletSDKRelay.js:595
_eth_requestAccounts @ CoinbaseWalletProvider.js:612
setTimeout (async)
hostReportError @ hostReportError.ts:8
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:272
SafeSubscriber.next @ Subscriber.ts:208
Subscriber._next @ Subscriber.ts:140
Subscriber.next @ Subscriber.ts:100
BehaviorSubject._subscribe @ BehaviorSubject.ts:28
Observable._trySubscribe @ Observable.ts:239
Subject._trySubscribe @ Subject.ts:117
Observable.subscribe @ Observable.ts:218
render @ LinkFlow.js:73
open @ LinkFlow.js:62
requestEthereumAccounts @ WalletSDKUI.js:55
(anonymous) @ WalletSDKRelay.js:640
requestEthereumAccounts @ WalletSDKRelay.js:595
_eth_requestAccounts @ CoinbaseWalletProvider.js:612
await in _eth_requestAccounts (async)
_handleAsynchronousMethods @ CoinbaseWalletProvider.js:433
(anonymous) @ CoinbaseWalletProvider.js:402
_sendRequestAsync @ CoinbaseWalletProvider.js:370
request @ CoinbaseWalletProvider.js:290
requestAccounts @ index-d817b0d2.js:2694
connectWallet @ index-d817b0d2.js:7716
(anonymous) @ index-d817b0d2.js:7874
ConsumerObserver.next @ Subscriber.ts:161
Subscriber._next @ Subscriber.ts:119
Subscriber.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
errorContext @ errorContext.ts:29
Subject.next @ Subject.ts:61
BehaviorSubject.next @ BehaviorSubject.ts:37
setStep @ index-d817b0d2.js:7888
(anonymous) @ index-d817b0d2.js:7674
setTimeout (async)
selectWallet @ index-d817b0d2.js:7674
await in selectWallet (async)
func @ index-d817b0d2.js:6083
func @ index-d817b0d2.js:5820
(anonymous) @ index-d817b0d2.js:5596
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
@wbt I'm having a hard time reproducing locally- I get this pop up when I have the coinbase extension disabled: 
<img width="789" alt="Screenshot 2023-04-25 at 5 32 49 PM" src="https://user-images.githubusercontent.com/33187102/234328244-d6689fa4-43ca-4bec-8100-d364ece0049b.png">

Can you provide a sample of the code you're using? Thx!

**Comment by wbt** [comment]
OK, got it down to a simple example.

- In a terminal in an empty folder on a machine with Node installed (v16 for test), `npx create-react-app coinbase-wallet-bug-demo`
- `cd coinbase-wallet-bug-demo`
- Replace src/index.js with src/index.tsx containing the following:

```tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import Onboard from '@web3-onboard/core';
import coinbaseWalletModule from '@web3-onboard/coinbase';
import walletConnectModule from '@web3-onboard/walletconnect';
import injectedModule from '@web3-onboard/injected-wallets';
const coinbaseWalletSdk = coinbaseWalletModule();
const walletConnect = walletConnectModule();
const injected = injectedModule();
const OnboardWrapper = Onboard({
    wallets: [coinbaseWalletSdk, walletConnect, injected],
    chains: [
        {
            // chain ID must be in hex, though use of parseInt could make that more flexible
            id: '0x1',
            token: 'ETH',
            namespace: 'evm',
            label: 'Ethereum Mainnet',
            rpcUrl: `https://mainnet.infura.io/v3/${process.env.REACT_APP_INFURA_KEY}`
        },
    ],
});
const connectWallet = async () => {
    try {
        const wallets = await OnboardWrapper.connectWallet();
        console.log('First connected account address: ' + wallets[0]?.accounts[0]?.address);
    } catch (error) {
        console.error(error);
    }
};
const root = ReactDOM.createRoot(
    document.getElementById('root') as HTMLElement
);
root.render(
    <React.StrictMode>
        <button
            onClick={connectWallet}
        >Click here to connect your wallet</button> and see the connected address in the console.
    </React.StrictMode>
);
```
- Run `npm start`
- In the Chrome browser with Coinbase Wallet extension installed but disabled, visit localhost:3000.
- Click the button
- Click Coinbase Wallet
- See this:
![image](https://user-images.githubusercontent.com/563406/234342190-7b4b36c1-1453-4e2f-83cc-f1154ff85f5e.png)

If you instead click on e.g. MetaMask you can successfully connect that and see that it works fine.

**Comment by wbt** [comment]
Ah, yes, that works much better now; sorry for the inconvenience.  

The documentation there says "The above webpack 5 example can be used in the craco.config.js file at the root level in this case." but the syntax around plugins is actually a bit [different](https://craco.js.org/docs/configuration/webpack/#webpackplugins) but after following the other instructions about packages to add, adding CRACO per its own documentation, and replacing the plugins object from this package's documentation with 

```js
webpack: {
    plugins: {
        add: [
            new webpack.ProvidePlugin({
                process: 'process/browser',
                Buffer: ['buffer', 'Buffer']
            })
        ]
    }
}
```
it worked with the expected behavior as pictured above.
