### ISSUE TITLE
Pagination on WalletConnect modal

### ISSUE THREAD

**Issue by Tsirov** [blocknative/web3-onboard#1663]
### Current Behavior

Using react js progect I am implementing connection to the Web3 with ` useWallets()` hook. When I try to connect to the Web3 and the current modal form `web3-onboard` appear and I click witch `walletConnect` after aper the modal witch suggested wallets under the wallet paginations is not working (pagination is starting from 4 number and user cannot go the lowest number of page ). It is tested on iPhone 14. 
You can test it event in this ### https://app.compound.finance/?market=usdc-mainnet app when you thy to connect witch wallet.

### Steps To Reproduce

1. Open the let's say this app `https://app.compound.finance/?market=usdc-mainnet` where they have [web3-onboard] implementation.
2. Click the icon for conectting with the wallet.
3. Choose WalletConnect.
4 See the pagination under the suggested wallets it is start from number 4

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

"@web3-onboard/react": "^2.2.6"

### Node Version

v16.18.0

### What browsers are you seeing the problem on?

Safari

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
@Tsirov I can see it on the site you provided, but I'm having trouble reproducing locally. Do you have a sample code you're working with?

**Comment by Tsirov** [comment]
Sorry but i cannot share the sample code, I will try to copy the logic for connection and will share. But it will after 2 days.

**Comment by leightkt** [comment]
@Tsirov can you actually provide your code in a pen or via link to a github repo that I can look at? Thx.

**Comment by leightkt** [comment]
@Tsirov also- are you using the most recent version of the web3onboard/walletconnect package- 2.3.6?

**Comment by leightkt** [comment]
@Tsirov I was actually finally able to reproduce locally- sorry for the delay. 
This is actually an issue within the V1 walletconnect module, not web3onboard. Please open an issue with the walletconnect team- [https://github.com/WalletConnect/web3modal](https://github.com/WalletConnect/web3modal)

**Comment by Tsirov** [comment]
@leightkt Sorry about that, and thank you for the time.
