### ISSUE TITLE
[Feature]: Load more hardware wallet addresses

### ISSUE THREAD

**Issue by iamacook** [blocknative/web3-onboard#1674]
### Is your request related to a problem?

It's not possible to load hardware wallet addresses beyond the 5th.

When actively using the 6th, for example, it cannot be loaded in the interface.

### Feature Description

The option to load more, or something similar, is present at the bottom of the address list.

### Alternative Solutions

Using the legacy version of `bnc-onboard`.

#### Current interface

![image](https://user-images.githubusercontent.com/20442784/235857953-605bc894-e4b2-4f13-9723-ebb205bbe987.png)

#### Legacy interface

![image](https://user-images.githubusercontent.com/20442784/235857879-f535477a-d5ae-4ff8-b869-d392d6acee10.png)

**Comment by Adamj1232** [comment]
@iamacook thank you for adding this feat request. We have talked about adding a feature along these lines. Would you want this to be a user side setting or a initialization param from the dev side?

**Comment by iamacook** [comment]
> Would you want this to be a user side setting or a initialization param from the dev side?

I think allowing the user to have full control makes the most sense.

**Comment by Adamj1232** [comment]
> > Would you want this to be a user side setting or a initialization param from the dev side?
> 
> I think allowing the user to have full control makes the most sense.

Sounds good! I will discuss this change with the team and update here as progress is made.

**Comment by Adamj1232** [comment]
@iamacook I will look into this further today. I will first confirm there isnt a bug and then later look into the feature of adding more accounts.
In the screenshot you provided I see that the Display empty addresses is not selected, by any chance can you select that with the same HW wallet and take a screenshot? Thank you!

**Comment by Adamj1232** [comment]
@iamacook digging into the code more the current Account Select modal will in-fact show all addresses up until 5 addresses with zero balance present in a row.
So with the original screenshot above, if the user had selected `Show Empty Addresses` they would have seen this list in this order.
<img width="356" alt="Screenshot 2023-05-09 at 2 50 05 PM" src="https://github.com/blocknative/web3-onboard/assets/24457880/eb460211-bac0-4010-bc41-2b42a1e725a2">

**Comment by iamacook** [comment]
> We have setup the Account Select display to only display the addresses with balances unless the Show Empty Addresses is selected with a break of 5 empty consecutive addresses.

This was an oversight on my accord. It does indeed show them correctly:

![image](https://github.com/blocknative/web3-onboard/assets/20442784/44c4d33b-dbb3-48b1-8232-05dcb35019b8)

> We can extend configurability of the Show More Addresses toggle or the threshold of consecutive zero-balance accounts as params to the dev if that would be helpful.

This would be beneficial. Addresses need no balance to be Safe signers.

**Comment by Adamj1232** [comment]
@iamacook no worries! 
From a little more digging - `Show Empty Addresses` should be on by default in the latest versions - is this what you are seeing?
Are you wanting a param to define the threshold of consecutive zero-balance accounts?

**Comment by iamacook** [comment]
> `Show Empty Addresses` should be on by default in the latest versions - is this what you are seeing?

Not at the moment. We will look into upgrading.

> Are you wanting a param to define the threshold of consecutive zero-balance accounts?

I am [waiting to hear back from the user who initially reported this](https://github.com/safe-global/safe-wallet-web/issues/1424#issuecomment-1541958210). Can I get back to you about this?

**Comment by Adamj1232** [comment]
Noting this issue: https://github.com/5afe/safe-support/issues/178

**Comment by MorpheusNetwork** [comment]
Please see: https://github.com/safe-global/safe-wallet-web/issues/1424#issuecomment-1546790245

**Comment by Adamj1232** [comment]
@iamacook this is available with the latest `alpha` versions of hardware wallets and I would recommend upgrading core as well (doesn't need to be in alpha)
We should have an official release for you by EOW

**Comment by Adamj1232** [comment]
@iamacook this ability for the dapp dev to set the empty account threshold for HW wallets is available now on the latest versions of the hardware wallet modules and can be set per HW module init. Closing for now, thanks again for raising this issue!
