### ISSUE TITLE
Installing okxWallet will affect other native wallets such as MetaMask Coinbase Wallet and Binance Smart Wallet

### ISSUE THREAD

**Issue by xinchen37** [blocknative/web3-onboard#1703]
### Current Behavior

Installing okxWallet will affect other native wallets such as MetaMask Coinbase Wallet and Binance Smart Wallet
<img width="781" alt="image" src="https://github.com/blocknative/web3-onboard/assets/9047883/69dda0bc-ada7-4e60-9a81-d1d64f08eba6">

### Expected Behavior

Wallet normal connection

### Steps To Reproduce

import injectedModule from '@web3-onboard/injected-wallets'
import coinbaseWalletModule from '@web3-onboard/coinbase'

const injected = injectedModule({
  displayUnavailable: true
})
const coinbaseWalletSdk = coinbaseWalletModule({ darkMode: true })

init({
  wallets: [injected, coinbaseWalletSdk],
  chains: [
    {
      id: '0x1',
      token: 'ETH',
      label: 'Ethereum Mainnet',
      rpcUrl
    }
  ]
})

### What package is effected by this issue?

@web3-onboard/injected

### Is this a build or a runtime issue?

Runtime

### Package Version

  "@web3-onboard/coinbase": "^2.2.3",     "@web3-onboard/injected-wallets": "^2.8.6",     "@web3-onboard/vue": "^2.5.7-alpha.3",     "@web3-onboard/walletconnect": "^2.3.7",

### Node Version

v18.12.1

### What browsers are you seeing the problem on?

Chrome

### Anything else?

<img width="1097" alt="image" src="https://github.com/blocknative/web3-onboard/assets/9047883/f9401888-799f-4edd-8dd9-72731d190872">

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
We also have some troubleshooting tips for multiple wallets: [https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed](https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed)

**Comment by leightkt** [comment]
@xinchen37 Double check that your metamask extension is enabled. I also suggest if you have OXC set as your default wallet- you try turning that off and refreshing/retrying to connect to metmask.

**Comment by xinchen37** [comment]
@leightkt  Enabling OKX Wallet overwrites window.ethereum. Disabling OKX Wallet works fine

<img width="1427" alt="image" src="https://github.com/blocknative/web3-onboard/assets/9047883/c3947475-7564-43f3-a487-4587a979c2c1">

禁用 OKX Wallet 
<img width="1406" alt="image" src="https://github.com/blocknative/web3-onboard/assets/9047883/e6fe4e68-ce59-4368-878f-31a7de0471e8">

**Comment by leightkt** [comment]
@xinchen37 This is unfortunately a known issue:

[https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed](https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed)

This is the case with MetaMask which injects to the window.ethereum browser space as does many other wallets. With current EIP standards this space can only hold one wallet so the wallet that loads the slowest will override the previous and be the only wallet available. To address this issue:

Users should navigate to their browser's extension settings (within Chrome browser it is: chrome://extensions/ or you can click the puzzle piece in the extension row)
Ensure that all other browser wallets are disabled (or not set to be the default web3 wallet) and your target wallet is enabled
Once this is completed a refresh of the browser should give the dapp access to the desired wallet.

**Comment by leightkt** [comment]
Closing this issue- please feel free to continue the conversation if you run into anything else!
