### ISSUE TITLE
[Feature]: Keplr Support

### ISSUE THREAD

**Issue by sandoche** [blocknative/web3-onboard#1722]
### Is your request related to a problem?

No

### Feature Description

I would like to know if there are plans to support Keplr wallet

### Alternative Solutions

Use Keplr directly

**Comment by Adamj1232** [comment]
@sandoche there are currently no plans to support Keplr as it is a Cosmos based wallet and Web3-Onboard is an EVM based wallet library.
Can you provide more info on how Keplr would be used in your project?

**Comment by sandoche** [comment]
I'm looking for ways to improve the onboarding experience of app.evmos.org and this web3 on-board library would help a lot!

Evmos support both Ethereum wallet such as metamask and cosmos wallet such as Keplr. Therefore I would be able to use this library only if it could support both.

**Comment by Adamj1232** [comment]
This requested has been raised to our product team. We have discussed adding chains outside of evm chains but do not currently have this feature on our road map. Will close for now but will update if/when this changes. Thanks!
