### ISSUE TITLE
React disconnect hook throws JSON Exception

### ISSUE THREAD

**Issue by schauersbergern** [blocknative/web3-onboard#1735]
### Current Behavior

When triggering React disconnect hook:
`const [{ wallet, connecting }, connect, disconnect] = useConnectWallet()`

from a disconnect button in my app like this:
`<button onClick={() => { disconnect({ label: wallet.label }) }}>Disconnect</button>`

the disconnect function in web3-onboard core throws following error:

```
Uncaught (in promise) SyntaxError: Unexpected token 'M', "MetaMask" is not valid JSON
    at JSON.parse (<anonymous>)
    at disconnect (index-8e3ff0c1.js:3287:1)
    at async useConnectWallet.js:18:1
```

Also using the widgets Disconnect Wallet Option throws the same error
<img width="309" alt="image" src="https://github.com/blocknative/web3-onboard/assets/22813752/147b06db-0f60-49ff-be48-add335b9907c">

Which leaves the UI and Widget in a bad state where only reloading the page helps.

Also disconnecting a Ledger with `disconnect({ label: "Ledger" })` throws the Metamask error, which is very strange...

### Expected Behavior

Disconnect Hook works like expected

### Steps To Reproduce

1. create react app with typescript `npx create-react-app my-app --template typescript`
2. Follow instructions for React App Rewired as found on https://onboard.blocknative.com/docs/modules/react#if-using-create-react-app
3. Implement npm way of web3 onboard connect button as shown here:
https://onboard.blocknative.com/examples/connect-wallet

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

"@web3-onboard/react": "^2.8.3"

### Node Version

v16.19.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@schauersbergern can you please update to the latest version of the web3-onboard/react package at version `2.8.4`

**Comment by schauersbergern** [comment]
> @schauersbergern can you please update to the latest version of the web3-onboard/react package at version `2.8.4`

@Adamj1232 Just updated to `2.8.4` but unfortunately the issue remains

**Comment by Adamj1232** [comment]
@schauersbergern I am unable to reproduce this issue. Can you confirm an issue at https://reactdemo.blocknative.com/ ?
Which you can see the code for here - https://github.com/blocknative/react-demo

**Comment by schauersbergern** [comment]
> @schauersbergern I am unable to reproduce this issue. Can you confirm an issue at https://reactdemo.blocknative.com/ ? Which you can see the code for here - https://github.com/blocknative/react-demo

@Adamj1232 No, on the demo you have stated everything works fine.
The example given in 
https://onboard.blocknative.com/examples/connect-wallet
differs in using typescript and using
```
<Web3OnboardProvider web3Onboard={web3Onboard}>
      <ConnectWallet />
    </Web3OnboardProvider>
```
So I think this is an issue with the Web3OnboardProvider

**Comment by Adamj1232** [comment]
Hmm I am still unable to reproduce with the example we have here using the provider - https://github.com/blocknative/web3-onboard/tree/develop/examples/with-nextjs-13
Can you provide a reproducible example?

**Comment by schauersbergern** [comment]
> Hmm I am still unable to reproduce with the example we have here using the provider - https://github.com/blocknative/web3-onboard/tree/develop/examples/with-nextjs-13 Can you provide a reproducible example?

@Adamj1232 sure, added my project to github:
https://github.com/schauersbergern/web3onboard

when you run it locally it throws said error.

But now, plot twist:
To cross check I deployed the project to railway, and the error doesn't occur anymore:
https://web3onboard-production.up.railway.app/

What could be the difference here?

**Comment by schauersbergern** [comment]
> Hmm interesting, are the deployed build and local versions of node equivalent? Which versions of node are you running? Hmm im unable to get your project running locally using yarn or npm - running node v16.18.1

@Adamj1232 
Locally I ran v16.19.0, when I checked railway deployment I found out they are using v16.18.1 like you.
I switched also to v16.18.1 locally (nvm alias default 16.18.1) but I still get the error

**Comment by Adamj1232** [comment]
@schauersbergern after switching versions of node did you reinstall dependencies?
Any progress here? I am unable to get your project running locally, if you have steps outside of `yarn && yarn start` send em my way...also if you can setup a stackblitz I can troubleshoot for there

**Comment by schauersbergern** [comment]
@Adamj1232 Yes, I reinstalled after switching node version. Which error do you get when running it locally?
On stackblitz I can't run the project, I got several errors, so I published it on replit:
https://replit.com/@NikolausSchauer/web3onboard

But you guess, there it also works.

As it seem to be good on live env and only fails on local I've decided to go on and don't spend further time on the issue.
Thanks for checking on the issue, I'm sorry not to find the real error.
