### ISSUE TITLE
[Feature]: Enable update appMetadata

### ISSUE THREAD

**Issue by slotZero01** [blocknative/web3-onboard#1747]
### Is your request related to a problem?

My project implements a theme switching from light to dark. The logo url used is different for both themes, and right now, it's not possible to update app metadata once it's initialized

### Feature Description

implement update appMetadata after web3 onboard is initizialiedinitialized

**Comment by leightkt** [comment]
Thanks for the suggestion! We'll get a ticket made and keep you posted on progress.

**Comment by leightkt** [comment]
@slotZero01 digging into this a little more- this functionality already exists- you should be able to use `onboard.state.actions.updateTheme()` 
let me know if this works for you!

**Comment by slotZero01** [comment]
that is only to update the color scheme, not the app logo url

**Comment by leightkt** [comment]
PR is up for this feature: https://github.com/blocknative/web3-onboard/pull/1779

**Comment by leightkt** [comment]
Changes have been merged into develop and you can now update appMetadata via @web3onboard/core: 2.20.3-alpha.1
`onboard.state.actions.updateAppMetadata({
  logo: `<svg width="100%" height="100%" viewBox="0 0 12 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 0L0.0100002 6L4 10L0.0100002 14.01L0 20H12V14L8 10L12 6.01V0H0ZM10 14.5V18H2V14.5L6 10.5L10 14.5Z" fill="#929BED"/>
  </svg>`,
  description: 'Updated Description!'
})`
