### ISSUE TITLE
React WalletConnect V2 RPC issues

### ISSUE THREAD

**Issue by mihaic195** [blocknative/web3-onboard#1769]
### Current Behavior

Unable to connect wallet using WalletConnect V2 when multiple chains and associated RPC links are provided. The connection fails abruptly whenever I scan the QR.

I'm not sure if the issue is on `web3-onboard` side or WalletConnect itself. I briefly reviewed the code on both sides, and based on what I've seen at first glance, everything seems to be as expected. Still, I might lean toward something wrong with WalletConnect and EthereumProvider initialization. 

I thought to post here before digging deeper. Maybe I'm blind to something obvious.

### Expected Behavior

WalletConnect V2 should work seamlessly on QR scanning.

### Steps To Reproduce

I'm currently initializing the WalletConnect module in the following way:

```typescript
init({
  wallets: [
    walletConnectModule({
      version: 2,
      projectId: Settings.walletConnectProjectId,
    }),
  ],
  chains: Object.keys(networksMap).map((id) => ({
    id: `0x${Number(id).toString(16)}`,
    token: networksMap[+id].currencySymbol,
    label: networksMap[+id].fullName,
    rpcUrl: networksMap[+id].rpcUrl,
  })),
  appMetadata: {
    ...
  },
});
```

I can see the chain list in the WalletConnect namespaces:
<img width="731" alt="Screenshot 2023-06-09 at 14 23 41" src="https://github.com/blocknative/web3-onboard/assets/34626017/aa2dddb9-fd5b-450c-a2ef-354b72d5c1cb">

The problem is that the `rpcMap` contains only 1 RPC link, the one associated to ETH, but not the others.

If I look at the WalletConnect optional namespaces, I see that the `rpcMap` is correctly populated for all chains:
<img width="721" alt="Screenshot 2023-06-09 at 14 34 28" src="https://github.com/blocknative/web3-onboard/assets/34626017/dff8ba68-495b-449d-b440-f6283873b0cd">

Because of this issue, the connection fails whenever I scan the QR.

Everything seems to work fine if I pass in the `chains` attribute only one chain and 1 RPC link associated with the chain.

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.3.8

### Node Version

16.13.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@mihaic195 We have released a new version of the @web3-onboard/walletconnect package that has updated deps. 
Can you give that a try?
Also, which wallet are you using? Not all injected wallets support WC v2 yet.
The RPC map shown in the browser shouldnt cause issue as I was able to connect Zerion to both Eth main and BSC.

**Comment by mihaic195** [comment]
> @mihaic195 We have released a new version of the @web3-onboard/walletconnect package that has updated deps. Can you give that a try? Also, which wallet are you using? Not all injected wallets support WC v2 yet. The RPC map shown in the browser shouldnt cause issue as I was able to connect Zerion to both Eth main and BSC.

Thanks for the quick reply. I updated the package to the latest version, and it seems to work now. I used TrustWallet and Fireblocks by scanning the QR. For Fireblocks, something is still wrong when connecting to a Testnet vault, but it works when connecting to the main production vault. Anyway, that might be Fireblocks related.

Thanks for pointing out the update.

**Comment by Adamj1232** [comment]
Great to hear @mihaic195 and thank you for raising this issue for visibility. I will close for now but feel free to continue the conversation.
