### ISSUE TITLE
Bug: wc2, DEEPLINK_CHOICE breaks usage when no app can be opened

### ISSUE THREAD

**Issue by L03TJ3** [blocknative/web3-onboard#1780]
### Current Behavior (Desktop!)

https://github.com/WalletConnect/walletconnect-monorepo/issues/2303#issuecomment-1539185204

There is a localstorage item set: WALLETCONNECT_DEEPLINK_CHOICE
this gets set whenever you select a wallet on the wc2 modal (using deeplinking)

When the link set in this storage item does not have a corresponding app to open (like a desktop app / mobile app) it redirects on the dapp to the last used deep link. This redirect happens on every transaction attempt, even if the connected wallet is not the one set on storage
the actual tx request does pop up in a connected wallet, but the entire session on the dapp side is lost 

### Expected Behavior

based on this demo: https://react-app.walletconnect.com/
the item gets removed whenever navigating back in the wc-modal, and gets cleared upon opening the modal
this prevents accidental setting of item, and seems more likely that the connected wallet <> deeplink set are intended to be there
(added vid for clarification)

### Steps To Reproduce

1. use onboard connect modal (latest)
2. click on wallet-connect (v2)
3. click on one of the shown deeplink-wallets
4. DONT CONNECT
5. click back, and use QR scanning or copy URI to connect an alternative wallet
6. once connected, attempt to do a transaction
7. redirect happens on dapp
*. can verify here that the page that opens is the link set in storage on walletconnect_deeplink_choice

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.3.9

### Node Version

16.17.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by L03TJ3** [comment]
Expected behavior based on the wc2 demo. (I think this will mostly solve the issue, just clear the storage item when no connection is established or another wallet ends up being used)
[Screencast from 16-06-23 15:33:38.webm](https://github.com/blocknative/web3-onboard/assets/6606028/ead68de1-fefc-4036-b451-4c167c8db163)

More rigorous would be something to check if it is a proper deeplink, but idk

**Comment by glitch-txs** [comment]
Is this supposed to happen purely on mobile? If so how could someone use the QR code 🤔

**Comment by L03TJ3** [comment]
@glitch-txs no this is a desktop issue
when selecting a wallet from the list on wc-modal on desktop.
the expected behavior is that this opens a corresponding desktop-app wallet (not browser extension)
but the choice which is selected gets cached. so that when you click but don't decide to connect this choice stays and interferes with any usage after when you connect an alternative wallet by copying/scanning QR

**Comment by Adamj1232** [comment]
This has been resolved on the WC side - PR to resolve within W3O: https://github.com/blocknative/web3-onboard/pull/1851

**Comment by Adamj1232** [comment]
@L03TJ3 those updates are available with the latest version of @web3-onboard/walletconnect at version 2.4.4-alpha.1 and was merged with this PR for any more details : https://github.com/blocknative/web3-onboard/pull/1851/files
