### ISSUE TITLE
React WalletConnect V2 useSetChain hook

### ISSUE THREAD

**Issue by mihaic195** [blocknative/web3-onboard#1782]
### Current Behavior

Using `setChain` of the `useSetChain` hook in a React app with the new WalletConnect V2 has no effect when connected using Fireblocks.

### Expected Behavior

Tested with Trust Wallet, and it seems to set the network correctly, so not sure why in the case of Fireblocks it doesn't work.

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.7

### Node Version

16.13.0

### What browsers are you seeing the problem on?

Chrome

**Comment by glitch-txs** [comment]
Hey, keep on mind WalletConnect v2 is multichain, so you usually will mostly notice the "switch" when triggering a transaction. Also judging on your comment it seems to be an issue on the wallet side maybe?:)

**Comment by taylorjdawson** [comment]
Hey @mihaic195 thanks for opening this issue, by chance do you have the minimal reproducible example that you could provide us with? Thanks!

**Comment by Adamj1232** [comment]
@mihaic195 is this still an issue with the latest react & walletconnect packages?

**Comment by Adamj1232** [comment]
Closing as this issue has become stale. Please feel free to continue the conversation
