### ISSUE TITLE
`@web3-onboard/ledger` is missing a dependency on `@ethersproject/providers`

### ISSUE THREAD

**Issue by ghivert** [blocknative/web3-onboard#1806]
### Current Behavior

Hi,

When using Yarn 3 with the latest release of Ledger onboard, an error pops up.

```
error - ../../.yarn/cache/@web3-onboard-ledger-npm-2.5.0-2c15715192-c2ded6b1d5.zip/node_modules/@web3-onboard/ledger/dist/v1.js:30:48
Module not found: Can't resolve '@ethersproject/providers'
```

It turns out that ledger is importing `@ethersproject/providers`, but it's not defined in the `package.json`.

### Expected Behavior

Importing should not throw.

### Steps To Reproduce

Init a project with Yarn 3, and init an app with ledger module.

### What package is effected by this issue?

@web3-onboard/ledger

### Is this a build or a runtime issue?

N/A

### Package Version

2.5.0

### Node Version

18.14.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@ghivert thank you for opening this issue. We have a fix in PR here - https://github.com/blocknative/web3-onboard/pull/1807 and it will be available shortly

**Comment by Adamj1232** [comment]
This fix is available with the latest alpha version of the ledger package as shown in the associated PR #1807 
An official release for this package will be out shortly
