### ISSUE TITLE
bug: Attempt to connect to relay via transportOpen has stalled. Retrying

### ISSUE THREAD

**Issue by frankye23** [blocknative/web3-onboard#1823]
### Current Behavior

After upgrading to wallet connect v2, our website often shows Attempt to connect to relay via transportOpen has stalled. Retrying. If i refresh it, the error will be gone.
![image](https://github.com/blocknative/web3-onboard/assets/92201847/566369e6-35d6-4962-b6e8-095da35da52b)

I wonder if this is related to relay url, which i didn't find how to add it in configuration of walletConnect module.

### Expected Behavior

I expect this error not to be shown in console

### Steps To Reproduce

1. Upgrade to wallet connect v2
2. Try to load the website or connect your wallet after loading the website
3. Go to the developer console of your browser.

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

"@web3-onboard/vue": "^2.7.8"

### Node Version

18.15.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
Have you upgraded to the most recent version of @web3-onboard/walletconnect- 2.4.2?

**Comment by frankye23** [comment]
> Have you upgraded to the most recent version of @web3-onboard/walletconnect- 2.4.2?

Yes, i do.
![image](https://github.com/blocknative/web3-onboard/assets/92201847/38cd0cde-12f2-4eba-885d-f3b45a75033e)

And i also add dappUrl both in WalletConnectOptions and in appMetadata.explore that is supplied to the web3-onboard init.

To reproduce, i have to send multiple request to my own api. But i wonder why axios request will be stalled by wc socket stalled.

**Comment by Adamj1232** [comment]
@frankye23 you may want to reach out to the walletconnect team as the transport relay is out of our scope

**Comment by Adamj1232** [comment]
@frankye23 is this still an issue on your end?

**Comment by frankye23** [comment]
> @frankye23 is this still an issue on your end?

Sorry to respond late. It turns out i init the wc provider in a wrong way. So it's no longer a issue. Thanks for reply anyway!
