### ISSUE TITLE
Switching Metamask from other connected injected (e.g.Okx)

### ISSUE THREAD

**Issue by bzhongy** [blocknative/web3-onboard#1824]
### Current Behavior

Apologies if this issue is reproduced. I have tested this on our dapp and other dapps that use the library

Once a user is connected via Okx through web3-onboard but then attempts to connect to Metamask in the future, the user is unable to reopen the MetaMask modal to access their MetaMask wallets, it would always divert back to Okx (unless user clears browser cache or uninstalls Okx)

Hope I made sense

### Expected Behavior

Whatever the user clicks should be the wallet provider that appears (i.e. if MetaMask is clicked, only metamask should appear). Or even the Okx option that allows users to pick MetaMask or Okx - however once user is connected on Okx, its very hard to go back to metamask wallets

I note that I think the opposite works fine - Users are able to connect to Okx through the okx button if the user connects to Metamask previously but it seems only switching back to MetaMask doesn't work. 

### Steps To Reproduce

1. Connect to Okx - ensure connected through okx 
2. Refresh page (may need to do steps 1/2 multiple times?)
3. Disconnect from Dapp
4. Attempt to connect to Metamask (but Okx wallet would pop up with previous connected wallet to connect). User is now unable to change back to Metamask

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.9

### Node Version

17.0.2

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
This sounds likely due to an issue with multiple wallets sharing the window.ethereum space. Take a look at our article on troubleshooting here: 
[https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed](https://onboard.blocknative.com/docs/resources/troubleshooting#_2-multiple-wallets-installed)
