### ISSUE TITLE
Rabby injected wallet not working using blocknative

### ISSUE THREAD

**Issue by anuj0361** [blocknative/web3-onboard#1835]
### Current Behavior

I should be able to connect using the Rabby wallet.

### Expected Behavior

I should be able to connect using Rabby wallet.

### Steps To Reproduce

1. Open https://oliveapp.finance/earn/vaults
2. Click Connect Wallet & Choose Rabby wallet option
3. It will not connect & don't through any error.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.8

### Relevant log output

```shell
No Output in the console.
```

### Anything else?

Versions
"@web3-onboard/injected-wallets": "^2.10.1",
"@web3-onboard/react": "^2.8.8",
"@web3-onboard/walletconnect": "^2.4.0",

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment]
@anuj0361 I will check this out and see if I can repro on my end, thanks for bring this to our attention!

**Comment by lm93547** [comment]
Any updates on this

**Comment by Adamj1232** [comment]
@anuj0361 @lm93547 Is this using Rabby through walletconnect or the injected package?

**Comment by anuj0361** [comment]
Using injected package @Adamj1232

**Comment by taylorjdawson** [comment]
@anuj0361 connect through our [docs site](https://onboard.blocknative.com/) and see if it works for you. It worked for me so I am assuming this is an issue with the olive app itself

**Comment by taylorjdawson** [comment]
@anuj0361 is this still an issue?

**Comment by anuj0361** [comment]
Resolved. Please close this issue. Got to know the name got changed from 'Rabby' to 'Rabby Wallet' in block-native library.
