### ISSUE TITLE
'@web3-onboard/torus' - NextJS 12 Loads in dev, but not in Vercel production

### ISSUE THREAD

**Issue by Seroxdesign** [blocknative/web3-onboard#1848]
## ISSUE

the torus module doesn't' work in Vercel production, but it works in development.

I have set up webpack, babel and installed all packages following the documentation:
 https://onboard.blocknative.com/docs/wallets/torus
 
 The package loads, and is available in the wallets array, but doesn't show up/work.
 
 

### Expected Behavior

It should work as it works in development

### Steps To Reproduce

1. Install ``import torusModule from '@web3-onboard/torus'``
2. Set up in wallets array for init
3. click the onboard connect modal in development, notice torus loads
4. deploy to vercel
5. notice the torus connect button doesn't exist

### What package is effected by this issue?

@web3-onboard/torus

### Is this a build or a runtime issue?

Runtime

### Package Version

2.20.04

### Node Version

Node 16

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
The function: torusModule() is console logged, but is not visible or interactable in UI
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@Seroxdesign is this still an issue?

**Comment by Seroxdesign** [comment]
Still an issue @Adamj1232, unfortunately we set this aside for now until this gets resolved.

**Comment by Adamj1232** [comment]
@Seroxdesign did you happen to look into the web3auth/torus docs for resolution?

**Comment by Seroxdesign** [comment]
> @Seroxdesign did you happen to look into the web3auth/torus docs for resolution?

I did, I practically scoured everything I could find, including docs, github issues etc.. could be something to do with our complex tech stack

**Comment by glitch-txs** [comment]
In the next.config.js file try setting swcMinify to false

**Comment by leightkt** [comment]
@Seroxdesign we recently uppdated the @web3-onboard/torus package- will you update and let me know if you're still experiencing this issue?

**Comment by leightkt** [comment]
@Seroxdesign closing for now- feel free to reopen if you test the updated package and still experience the same issue (or please post if you found a solution previously). Thanks!
