### ISSUE TITLE
WalletConnect: Allow requiredChains OR optionalChains to be empty

### ISSUE THREAD

**Issue by ReflectiveChimp** [blocknative/web3-onboard#1850]
### Current Behavior

`requiredChains` is required, passing an empty array will default to `[1]` i.e. ethereum
`optionalChains` is optional, allowed to be empty

https://github.com/blocknative/web3-onboard/blob/64fe1c0596604eef36fa3e216212fe5a26c6fb65/packages/walletconnect/src/v2.ts#L89-L96

### Expected Behavior

Allow requiredChains OR optionalChains to be empty

✔️ `optionalChains` should be allowed to be empty so long as `requiredChains` is not.  
❌ `requiredChains` should be allowed to be empty so long as `optionalChains` is not. 

### Steps To Reproduce

1. Pass empty `requiredChains` of `[]` and `optionalChains` of `[250]` to wallet connect module init
2. Attempt to connect via WC with a wallet that only supports the optional chain e.g. safe.fantom.network
3. Connection will fail as ethereum [1] isn't supported e.g. by the fantom safe wallet

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

@web3-onboard/walletconnect@2.4.3

### Node Version

16

### Anything else?

We need this functionality as we do not require the user to select a chain before connecting their wallet, so no chains are required. Having required default to [1] ethereum means the connection fails for wallets that do not support ethereum e.g. non-ethereum gnosis safes.

EthereumProvider was fixed to accept empty `chains` OR `optionalChains` in this pr: https://github.com/WalletConnect/walletconnect-monorepo/pull/2781

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@ReflectiveChimp thanks for raising this issue! PR to resolve: https://github.com/blocknative/web3-onboard/pull/1851

**Comment by Adamj1232** [comment]
@ReflectiveChimp those updates are available with the latest version of @web3-onboard/walletconnect at version `2.4.4-alpha.1` and was merged with this PR for any more details : https://github.com/blocknative/web3-onboard/pull/1851/files

**Comment by ReflectiveChimp** [comment]
@Adamj1232 Thank you for quick turn around. Can confirm alpha works and we can send only optional chains now.

p.s. description needs updated to say that it defaults to `[]` now, not `[1]`
https://github.com/blocknative/web3-onboard/blob/53526e15c6eba1b167986c966503053742e14c9b/packages/walletconnect/src/index.ts#L48-L52

**Comment by Adamj1232** [comment]
Closed as this bug has been fixed with the latest release. Thanks for reporting!
