### ISSUE TITLE
WalletConnect: Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry

### ISSUE THREAD

**Issue by slotZero01** [blocknative/web3-onboard#1852]
### Current Behavior

when connect using wallet connect, received this error

```
Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry
```

### Expected Behavior

walletconnect modal should popup

### Steps To Reproduce

config
```
"@web3-onboard/core": "^2.20.5",
 "@web3-onboard/injected-wallets": "^2.10.3",
 "@web3-onboard/react": "^2.8.10",
 "@web3-onboard/walletconnect": "^2.4.3",
 ```

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.4.3

### Node Version

16

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by glitch-txs** [comment]
Hi @slotZero01! Could you add a minimal reproducible example of the issue?

**Comment by Adamj1232** [comment]
@slotZero01 I am unable to reproduce. Are you seeing the same issue when running our [react demo](https://github.com/blocknative/react-demo) example?

**Comment by slotZero01** [comment]
seems it's a problem with the walletconnect side after we released the app to prod. Will update here if we able to fix it

**Comment by glitch-txs** [comment]
This usually happens when the modal/config is being rendered multiple times.

**Comment by slotZero01** [comment]
yeah after debugging, there's a third-party library that uses the same web3 onboard as their connect wallet. As a result, the init function is called twice. We already resolved this issue. Thanks
