### ISSUE TITLE
[Feature]: Allow dapps to read the required namespace methods for walletconnect

### ISSUE THREAD

**Issue by Sednaoui** [blocknative/web3-onboard#1884]
### Is your request related to a problem?

As a dapp, there's no way to get the required namespace methods that the wallet is supporting with walletconnect. 

### Feature Description

The feature would support reading the [requiredNamespace for methods](https://docs.walletconnect.com/2.0/advanced/providers/ethereum#required-and-optional-methods) so that dapp can adjust its interface based on the supported methods. 

Usecase: 

If dapps know that a wallet supports [wallet_sendFunctionCallBundle](https://eips.ethereum.org/EIPS/eip-5792#wallet_sendfunctioncallbundle), it can adjust its interface to send a bundle call to allow for a one-click interface. This is highly relevant to smart wallets.

### Alternative Solutions

The dapp can communicate additional optional methods during session initialization to ask certain methods. That is unfortunately not very useful since the dapp have no means of knowing if the wallet supports the optional methods or not. 

The dapp can also communicate [required methods](https://github.com/blocknative/web3-onboard/pull/1883) during session initialization, but that forces the dapp to not accommodate its interface with all wallets. Also at the moment, popular wallets (metamask) bypass this checks as if it is non-existent. The reason why they do it is to not break any connections with dapps.

**Comment by leightkt** [comment]
@Sednaoui Thanks for the feature request! We'll add to the team backlog and keep you posted as we discuss.

**Comment by leightkt** [comment]
author opened PR: https://github.com/blocknative/web3-onboard/pull/1883

**Comment by Sednaoui** [comment]
Thank you! 

> author opened PR: #1883

To clarify, the PR that I opened is only one part supporting the requiredName space for walletconnect. It enables Dapps to send required methods to wallets. It doesn't enable dapps to read the required namespace that the wallet provides, which is the feature request for this open issue.

**Comment by Adamj1232** [comment]
I am reviewing and testing your PR today and reached out to the WC team for clarity regarding your request here. Thanks again!

**Comment by Adamj1232** [comment]
This has been released with the latest version of  `@web3-onboard/walletconnect`
The provider returned from the web3-onboard api will now include an `instance` prop for walletconnect connections. Within this you can check out `instance.session` for info about namespaces and functions allowed in the wallet.
Closing for now but feel free to continue the conversation if needed

**Comment by Sednaoui** [comment]
perfect thank you!
