### ISSUE TITLE
Naming Error Tag Release

### ISSUE THREAD

**Issue by tomrpl** [blocknative/web3-onboard#1891]
### Current Behavior

Naming Tag number error:

https://github.com/blocknative/web3-onboard/releases/tag/2.47.8

### Expected Behavior

This release should have been tagged 2.24.8 instead of 2.47.8

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

2.47.8

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Thanks for reporting this issue, I will get it fixed up today

**Comment by Adamj1232** [comment]
This release has been updated with the proper release tag, thank you for reporting!
https://github.com/blocknative/web3-onboard/releases/tag/2.24.8
