### ISSUE TITLE
Cannot see Fordefi wallet in demo website

### ISSUE THREAD

**Issue by rony-arnac** [blocknative/web3-onboard#1894]
### Current Behavior

I went to https://onboard.blocknative.com/examples/connect-wallet and clicked on `Connect` and I don't see [Fordefi wallet](https://github.com/blocknative/web3-onboard/pull/1820).

Here are some prints of my `window`
![image](https://github.com/blocknative/web3-onboard/assets/98841690/b406aabe-98bb-4114-8800-cae8c2990b7d)

### Expected Behavior

See the wallet in the options.

### What package is effected by this issue?

@web3-onboard/injected

### Is this a build or a runtime issue?

N/A

### Package Version

"@web3-onboard/injected-wallets": "^2.10.5",

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@rony-arnac do you have Fordefi wallet installed on your browser and set to be your primary wallet?

**Comment by rony-arnac** [comment]
@Adamj1232 yep. added prints of my `window` above

**Comment by Adamj1232** [comment]
Are you seeing the same behavior here- https://reactdemo.blocknative.com/
The docs site may need to have its deps updated

**Comment by rony-arnac** [comment]
maybe the issue is that `Fordefi` uses `otherProviderFlagsExist` when isMetaMask is true as well?

https://github.com/blocknative/web3-onboard/blob/develop/packages/injected/src/wallets.ts#L822

**Comment by Adamj1232** [comment]
Im not too sure, I cant find where I can download the extension to test

**Comment by Adamj1232** [comment]
Are you a Fordefi dev by chance? Why is `isMetaMask` marked as true?

**Comment by rony-arnac** [comment]
> Are you a Fordefi dev by chance? Why is `isMetaMask` marked as true?

We use their open source provider.. 
I think this is a bug in the code I pushed

**Comment by rony-arnac** [comment]
yep, will create a PR to fix it!
