### ISSUE TITLE
[Feature]: Persist connection on page refresh

### ISSUE THREAD

**Issue by 0xARK** [blocknative/web3-onboard#1898]
### Is your request related to a problem?

Sometimes, users have to refresh the page for x or y reason. I used the examples/with-nextjs-13, to check this, but unfortunately when I refresh the page, the wallet is disconnected. I assume that this is normal due to the react state, but I'm looking for a way to persist the connection.

### Feature Description

I would like to know if it's possible to detect if a wallet has already been connected and connect the user to this wallet automatically without requiring any action from his part.

In the case that this is not possible, I would recommend to add this feature, but I think that this is already doable since that curve finance use web3-onboard and is able to reconnect a wallet previously connected without any user action.

Of course, I already looked for online solutions/answers to this question, but I have not been able to find it :(

**Comment by Adamj1232** [comment]
@0xARK this feature already exists, you can use the `autoConnectLastWallet` or `autoConnectAllPreviousWallets` flags within the `connect` object of the web3onboard initialization.
Example: https://github.com/blocknative/react-demo/blob/8e882c14f4952d3a230eac5d4e425af5e25b1d29/src/services.js#L157
Checkout the docs here: https://onboard.blocknative.com/docs/modules/core#connect

Going to close this issue as this feature exists but feel free to continue the conversation here for any support.

**Comment by 0xARK** [comment]
Great, I just tested and it works ! Thanks :)
