### ISSUE TITLE
otherProviderFlagsExist for metamask is unnecessary

### ISSUE THREAD

**Issue by puderty** [blocknative/web3-onboard#1900]
### Current Behavior

for metamask, you have a otherProviderFlagsExist check, and lot of wallet set isMetamask to true with their own flag. And then the user can't connect by metamask even if the wallet is metamask compatible. Why is this necessary?

### Steps To Reproduce

connect to dapp demo in okx mobile wallet by click on metamask

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

latest

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by puderty** [comment]
And also why is platform restricted to desktop for okx wallet?
![image](https://github.com/blocknative/web3-onboard/assets/538759/b085f7d3-281e-4bfb-9b2c-84e8a190a64c)

**Comment by Adamj1232** [comment]
@puderty the OKX wallet integration was done by the OKX team. If you would like to open a PR to add mobile support and test please feel free to do so.
`otherProvidersFlagsExists` method is necessary to reduce spoofing. Wallets should not set both flags to be true, this is bad UX and misleading users. MetaMask is the only wallet that should set `isMetaMask` to true and MetaMask should be the only wallet that opens if the user selects MetaMask.
Im not sure what you mean by MetaMask compatible, can you please clarify?

**Comment by puderty** [comment]
For some dapp not using your sdk, and if they only integrate with metamask, if we don't set ismetamask to true, the dapp cannot connect is okx mobile wallet. So we have to set it for compatible reason, but your check will broken it and make it cannot connect by click on metamask when using blocknative.

I'm from okx wallet mobile team, if otherProvidersFlagsExists is necessary, can you change the platform from desktop to all for okx wallet?

**Comment by Adamj1232** [comment]
@puderty `set it for compatible reason` is spoofing and is a misleading UX.
If you are from the OKX team please pass this along to the dev team.
If the wallet is to be used the provider flag needs to be specified and not rely upon MetaMask to mislead people into selecting one wallet and getting another.
If you would like to open a PR to make this update and test we would be happy to review.

**Comment by puderty** [comment]
But can we remove otherProvidersFlagsExists on mobile? Because the on mobile app there should be only one injected ethereum object and it's injected by the mobile web3 wallet the user is using.

**Comment by Adamj1232** [comment]
@puderty that update was made as part of this PR - https://github.com/blocknative/web3-onboard/pull/1901/files and will be merged into staging shortly.
This should allow OKX wallet to display properly on mobile. We wont be removing `otherProvidersFlagsExists` from MetaMask as this is to avoid spoofing of wallets.

**Comment by puderty** [comment]
Can you add some flag under window object so we can check that the dapp is using this library? So we can avoid setting other flags for dapps using this library. Such as window.isUsingBlockNative = true.

**Comment by Adamj1232** [comment]
We don't alter the provider object on the window so there is not a flag we can set. Please try using the latest alpha packages of core, react or vue to see if the update to the device settings for OKX wallet solves the issue - See #1901 for those versions

**Comment by Adamj1232** [comment]
@puderty support should be stabilized with a release going out today. We would be interested in doing a marketing post to our community around wallet support. Feel free to reach out for a contact within Blocknative if interested

**Comment by puderty** [comment]
Sure. I still suggest we remove the check on mobile, because for every mobile web3 wallet, there's only one injected window.ethereum, and every wallet should do their best to help their users to connect the dapp to the wallet. A lot of dapps only show Metamask as the only option. 
There's no spoofing on mobile web3 wallet or mobile browser.
