### ISSUE TITLE
[Feature]: Add EIP6963 Support

### ISSUE THREAD

**Issue by lzg0321** [blocknative/web3-onboard#1902]
### Is your request related to a problem?

Hello,

I hope this message finds you well. I'm interested in DApp developing and I see that EIP-6963 could significantly benefit the project by solving unfair competition for Wallet Providers and lack of interoperability.

Could you please confirm whether there are plans to integrate EIP-6963 into the project? If yes, is there a rough timeline for when this feature might be available?

Understanding your stance on this would greatly aid in planning my development efforts.

Thank you for your time and your contributions to this project. Looking forward to your response.

Best regards

### Feature Description

support [EIP6963](https://eips.ethereum.org/EIPS/eip-6963) which supports discovering multiple injected Wallet Providers in a web page without window.ethereum

**Comment by Adamj1232** [comment]
@lzg0321 thank you for opeing this feature request. Implementing 6963 is on the roadmap but currently our team is spread thin so we dont have an exact date we can begin implementing this functionality. I will raise this with our product team and keep you update on a timeline.

**Comment by glitch-txs** [comment]
Any updates on this? 🙂

**Comment by Adamj1232** [comment]
This is available with the latest version of @web3-onboard/injected
Please feel free to let us know if there are any other issues!
