### ISSUE TITLE
[BUG] containerElements connectModal option not working with React

### ISSUE THREAD

**Issue by kalashshah** [blocknative/web3-onboard#1909]
### Current Behavior

When adding a selector for the `connectModal` in a React application, it gives an error that the HTML element with that selector does not exist. We need to run the `init` method before any hooks and need to pass it to the provider so cannot wait for the dom tree to load as well. Hence unable to use this functionality in React.js, since it lacks the ability to use a `ref` here.

### Expected Behavior

The prop works as defined and we can disable the `connectWallet` modal and embed it in custom UIs.

### Steps To Reproduce

1. Open the demo application
2. Try to disable the modal and embed it into the UI

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Build

### Package Version

2.8.12

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
@kalashshah Thanks for opening. Do you have a minimal reproducible example we can refer to?

**Comment by kalashshah** [comment]
Hi, please refer this repo for the same: [https://github.com/kalashshah/bknative-test](https://github.com/kalashshah/bknative-test)

**Comment by Adamj1232** [comment]
Hi @kalashshah I have confirmed `containerElements` are working for the `connectModal`
With react and other frameworks that use a virtualized DOM the target element must be available prior to react creating its virtual DOM to be accessible at time of rendering. For an example please see the target containerElement defined [here](https://github.com/blocknative/react-demo/blob/ca207d236c1490255e3a01a246b4108f03502efc/public/index.html#L21) in the `index.html` and then that same html element defined [here](https://github.com/blocknative/react-demo/blob/ca207d236c1490255e3a01a246b4108f03502efc/src/services.js#L328) in the Web3-Onboard config by its ID.
HTML IDs are expected so there isn't trouble with duplicate html elements.
When going this route you will need to style the container as needed.
I am going to close for now but we can continue the conversation here 😄

**Comment by pellyadolfo** [comment]
Any example for NextJS with AppRouter? Not able to make it work.

**Comment by pellyadolfo** [comment]
@Adamj1232 

and your configuration with an static root file is required for React for any case integrating Web3OnBoard, even when containerElements (which is optional param) is not used.
