### ISSUE TITLE
WalletConnect v2 add chain or switch chain not working

### ISSUE THREAD

**Issue by itsmnthn** [blocknative/web3-onboard#1911]
### Current Behavior

On WalletConnect wen I call `onboard.setChain({ chainId }` to change the chain on connected wallet or add the chain to the connected wallet it just returns false without sending events through WalletConnect to connected wallet e.g. MetaMask Mobile, Trust Mobile or Core Mobile wallet.

### Expected Behavior

It should propmt on connected wallet to add network or switch network.

### Steps To Reproduce

call setChain on WalletConnect with MetaMask

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime, N/A

### Package Version

2.4.6

### Node Version

18

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by taylorjdawson** [comment]
Hey @itsmnthn we'll take a look at this. To me this looks very similar to this issue [here](https://github.com/blocknative/web3-onboard/issues/1783). Let us know if that's the case.

**Comment by Adamj1232** [comment]
Hi @itsmnthn I am currently looking into with the support of the WalletConnect team (@ganchoradkov @finessevanes). 
From my testing this seems to be a MetaMask issue as other wallets connected through WalletConnect are behaving normally. 
When I switch chains through the app nothing happens in either the wallet or the app (as the app listens for response on the chainsChanged event from WC to update). - I think the is the biggest problem for dapps is not be able to change the chain prior to sending a transaction.
When I change the chain within the MetaMask app there isn’t an event that reflects this through the WC connector.
If I send a transaction with a `setChain` call proceeding the transaction call the chain update is sent to the MetaMask wallet and seen within the wallet.
When performing the same steps with Trust the mobile Trust wallet updates along with the app.

**Comment by Adamj1232** [comment]
PR in the works to fix this issue #1926

**Comment by itsmnthn** [comment]
Thanks for the support. It seems the pr is merged to develop and will soon try it.

**Comment by Adamj1232** [comment]
@itsmnthn it has been merged and is available with the latest `-alpha.x` version of the @web3-onboard/walletconnect module

**Comment by Adamj1232** [comment]
This has been released with the latest version of @web3-onboard/walletconnect please upgrade to the latest stable version for this fix. Thank you again for reporting!
