### ISSUE TITLE
@web3-onboard/coinbase dependency fails to install on node v18.18.0

### ISSUE THREAD

**Issue by sirtimid** [blocknative/web3-onboard#1924]
### Current Behavior

When attempting to install @web3-onboard/coinbase on Node version v18.18.0, the installation fails, producing the following error:

```shell
warning Error running install script for optional dependency: "/Users/.../node_modules/bufferutil: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/.../node_modules/bufferutil
Output:
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v18.18.0"
``` 

This error is thrown due to a dependency on @coinbase/wallet-sdk@3.7.1 by @web3-onboard/coinbase.

### Expected Behavior

The @web3-onboard/coinbase package should install successfully without any errors on Node version v18.18.0. The dependent package @coinbase/wallet-sdk should also be installed seamlessly, resolving and compiling all of its native addons and dependencies correctly, thereby not causing the parent package installation to fail.

### Steps To Reproduce

1. install node v18.18.0
2. install @web3-onboard/coinbase
3. see fail logs

### What package is effected by this issue?

@web3-onboard/coinbase

### Is this a build or a runtime issue?

Runtime

### Package Version

2.2.5

### Node Version

18.18.0

### Relevant log output

```shell
warning Error running install script for optional dependency: "/Users/.../node_modules/bufferutil: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/.../node_modules/bufferutil
Output:
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v18.18.0"
```

### Anything else?

Suggested Solutions
@coinbase/wallet-sdk@3.7.2 fixed the issue to installation problems on Node v18.18.0, so the dependency needs to be updated

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@sirtimid looking into bumping the coinbase dep version today. Thanks for reporting!

**Comment by Adamj1232** [comment]
A fix for this has been merged into staging and is available with the latest alpha version of the coinbase package. It will be released shortly.

**Comment by Adamj1232** [comment]
This has been fixed with the release of the latest @web3-onboard/coinbase package version.
Thank you for reporting!
