### ISSUE TITLE
@web3-onboard/torus uses outdated version of @toruslabs/torus-embed

### ISSUE THREAD

**Issue by sergeyi23** [blocknative/web3-onboard#1935]
### Current Behavior

@web3-onboard/torus uses outdated version of @toruslabs/torus-embed. Because of that Torus does not behave properly within onboard on Chrome browsers. It gets stuck on a popup with button "Continue to app" that does not do anything.

### What package is effected by this issue?

@web3-onboard/torus

### Is this a build or a runtime issue?

Runtime

### Package Version

2.2.5

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
@sergeyi23  we've updated the @web3-onboard/torus package in the latest release- closing for now. Please feel free to comment again if your issue persists.
