### ISSUE TITLE
still gets walletConnect V1 deprecated warnings

### ISSUE THREAD

**Issue by sajwanAshish** [blocknative/web3-onboard#1949]
### Current Behavior

gets this warning when installing @web3-onboard/walletconnect package;

 @walletconnect/types@1.8.0: WalletConnect's v1 SDKs are now deprecated. Please upgrade to a v2 SDK. For details see: https://docs.walletconnect.com/

even on npm page its mentioned that walletConnect V1 is depricated

https://www.npmjs.com/package/@web3-onboard/walletconnect

### Expected Behavior

 WalletConnect's V1 dependency should be updated to V2

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.21.2

### Node Version

18

### Anything else?

when can we expect the changes in https://www.npmjs.com/package/@web3-onboard/walletconnect 

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@sajwanAshish We will look into this issue this week. Thanks for reporting!

**Comment by Adamj1232** [comment]
This fix has been updated with the latest version of @web3-onboard/walletconnect, please upgrade when you have a moment and thank you for reporting the issue!
