### ISSUE TITLE
Web3Onboard Walletconnect - Failed to publish payload, please try again

### ISSUE THREAD

**Issue by devamitsharma101** [blocknative/web3-onboard#1964]
### Current Behavior

This issue comes intermittently on our production where our client are using their wallet to connect with out daap using wallet connect and trying to sign a typed message.

```
[
{
context: core
}, 
{
context: core/relayer
}, 
{
context: core/relayer/publisher
}, 
{
message: Failed to publish payload, please try again., 
name: Error, 
stack: 
@https://app.s9y.gg/static/js/main.604d0b07.js:2:1167146
a@https://app.s9y.gg/static/js/main.604d0b07.js:7:30362
}
]
```

This is the stack trace we get in our logs. Does this mean the session is getting disconnected sometimes? If so than web3onboard does not provider any callbacks for that. 

The typed data has no issue because the same data when used in a new session works good.

### Expected Behavior

The signing should work each time.

### Steps To Reproduce

The issue is not reproducible at the moment.

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

2.4.7

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
[
typed sign error ---->, 
{
message: Failed to publish payload, please try again., 
name: Error, 
stack: 
@https://app.s9y.gg/static/js/main.9a927abd.js:2:1163704
a@https://app.s9y.gg/static/js/main.9a927abd.js:7:30440
}
]
```

### Anything else?

One thing is that this issue has been observed in apple ecosystem as of now. Chrome and Safari on Mac OS and iPhone. Will update if it comes up in any other ecosystem.

### Sanity Check

- [ ] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@devamitsharma101 thanks for opening this issue! Ill try to get some insight from the WC team on what might be a cause.

**Comment by meshin-dev** [comment]
The same issue, holesky safe not possible to use because of this issue.

**Comment by Adamj1232** [comment]
@meshin-dev @devamitsharma101 is this a persistent issue?
When brought up with the WC team they said:
> This indicates an issue with the network, might be flaky network condition, extension modifying the network, vpn etc

I dont believe there is anything we can do on the W3O side to mitigate but wanted to check back in.

**Comment by Adamj1232** [comment]
WalletConnect team advised us this is a network issue and nothing we can do on our end. If the issue persists we would recommend visiting the WalletConnect teams troubleshooting site for further information
