### ISSUE TITLE
wallectConnect not working

### ISSUE THREAD

**Issue by kr-keshav-kk** [blocknative/web3-onboard#1989]
### Current Behavior

Not able to use walletConnect feature. Asks for: To use QR modal, please install @walletconnect/modal package.

![image](https://github.com/blocknative/web3-onboard/assets/138488364/d77bb4da-63f6-4081-b103-acb47115b124)

### Expected Behavior

WalletConnect should open

### Steps To Reproduce

- in production walletConnect doesn't open while in localhost it works fine.

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

core: 2.21.2 , walletconnect: 2.5.0

### Node Version

18.16.1

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [ ] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@kr-keshav-kk thanks for reporting! What framework are you using?
Have you tried adding the @walletconnect/modal package to your project?

**Comment by kr-keshav-kk** [comment]
@Adamj1232 I am using SvelteKit. Yes i tried adding @walletconnect/modal. Still the result was same.

**Comment by kr-keshav-kk** [comment]
Thanks @Adamj1232 .
It got fixed by adding this: 		
`commonjsOptions: {
	transformMixedEsModules: true
}`
in vite.config.ts

**Comment by Adamj1232** [comment]
Excellent, thanks for noting! I will close this issue for now. Thanks again!
