### ISSUE TITLE
Error: To use QR modal, please install @walletconnect/modal package 

### ISSUE THREAD

**Issue by yisacc** [blocknative/web3-onboard#2006]
## Description

When using the `@web3-onboard/walletconnect` package with Vite, the package works as expected in development mode. However, when building the application for production, the following error is thrown: "To use QR modal, please install @walletconnect/modal package".

## Actual Behavior

The `@walletconnect/modal` package is not included in the production build, causing the application to throw an error when trying to use it.

## Possible Solution

I've tried to force Vite to include the package in the build using the `optimizeDeps.include` option in the `vite.config.js` file, but this did not resolve the issue.

## Additional Context

Here's the relevant part of my `vite.config.ts` file:

```typescript
import solid from "solid-start/vite";
import UnoCSS from "unocss/vite";
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";
import solidSvg from "vite-plugin-solid-svg";
import tsconfigPaths from "vite-tsconfig-paths";
import process from "node:process";

export default defineConfig({
  plugins: [
    // my plugins...
  ],
  optimizeDeps: {
    include: ["@walletconnect/modal", "@web3-onboard/walletconnect"]
  }
  // rest of my config...
});

### Expected Behavior

The `@walletconnect/modal` package should be included in the production build and work as expected, just like in development mode.

### Steps To Reproduce

1. Install `@walletconnect/modal` and `@web3-onboard/walletconnect` in a Vite project.
2. Use the package in the application.
3. Run the application in development mode - everything works as expected.
4. Build the application for production.
5. Serve the production build locally.
6. Observe the error message.

note: I am initializing onboard if it is not server 

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.7.15

### Node Version

18.16.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
N/A
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by yisacc** [comment]
I have created a pr to solve this issue [here](https://github.com/blocknative/web3-onboard/pull/2007)

**Comment by Adamj1232** [comment]
Thank you @yisacc your PR and fix has been released with the latest WC package
