### ISSUE TITLE
 ERROR  in ./node_modules/@web3-onboard/core/dist/Index-a8f5e52f.js  |  Module parse failed: Unexpected token (2148:140)   | Vue2 + Nuxt

### ISSUE THREAD

**Issue by wadguk** [blocknative/web3-onboard#2024]
### Current Behavior

 ERROR  in ./node_modules/@web3-onboard/core/dist/Index-a8f5e52f.js 
  friendly-errors 19:19:23
Module parse failed: Unexpected token (2148:140)   
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 		});
| 
> 	let if_block2 = !/*$accountCenter$*/ ctx[9].hideTransactionProtectionBtn && (/*primaryWalletOnMainnet*/ ctx[6] || /*validAppChain*/ ctx[5]?.protectedRpcUrl) && create_if_block_6(ctx);
| 	let if_block3 = /*$appMetadata$*/ ctx[11] && create_if_block_2$1(ctx);
| 	let if_block4 = /*secondaryTokens*/ ctx[8] && /*secondaryTokens*/ ctx[8].length && create_if_block_1$1(ctx);

 @ ./node_modules/@web3-onboard/core/dist/index-4c4d8815.js 10594:3-32
 @ ./node_modules/@web3-onboard/core/dist/index.js
 @ ./node_modules/@web3-onboard/vue/dist/index.js
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/organisms/Header.vue?vue&type=script&lang=js&
 @ ./components/organisms/Header.vue?vue&type=script&lang=js&
 @ ./components/organisms/Header.vue
 @ ./.nuxt/components/index.js
 @ ./.nuxt/components/plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build

### Package Version

2.7.12

### Anything else?

"vue": "^2.6.14",
"@vue/composition-api": "^1.7.2",
"nuxt": "^2.15.8",

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by wadguk** [comment]
Please help, I have no idea how to solve this problem.
Did everything related to the nuxt build setup.

**Comment by wadguk** [comment]
"dependencies": {
    "@hokify/vuejs-datepicker": "^2.0.2",
    "@nfteyez/sol-rayz": "^0.10.2",
    "@nuxtjs/auth-next": "^5.0.0-1648802546.c9880dc",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/sentry": "^7.1.9",
    "@project-serum/anchor": "^0.17.0",
    "@solana/web3.js": "^1.72.0",
    "@sumsub/websdk": "^1.3.6",
    "@vue/composition-api": "^1.7.2",
    "@vue/runtime-core": "^3.3.8",
    "@web3-onboard/vue": "^2.7.12",
    "autoprefixer": "^10.4.13",
    "cookie-universal-nuxt": "^2.2.2",
    "core-js": "^3.19.3",
    "eslint-plugin-nuxt": "^4.0.0",
    "ethers": "5.0.0",
    "lodash": "^4.17.21",
    "nuxt": "^2.15.8",
    "pinia": "2.0.0",
    "qrcode.vue": "1.7.0",
    "sh-v-owl-carousel": "^1.0.5",
    "v-click-outside": "^3.2.0",
    "v-tooltip": "^2.1.3",
    "vue": "^2.6.14",
    "vue-connect-wallet": "^0.1.7",
    "vue-js-modal": "^2.0.1",
    "vue-scrollto": "^2.20.0",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "web3modal-vue2": "^1.0.9",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@commitlint/cli": "^17.1.2",
    "@commitlint/config-conventional": "^17.1.0",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config": "^11.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "@nuxtjs/stylelint-module": "^4.1.0",
    "@sentry/tracing": "7.45.0",
    "@sentry/webpack-plugin": "1.20.0",
    "@types/node": "^18.11.18",
    "eslint": "^8.24.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-vue": "^9.5.1",
    "husky": "^8.0.1",
    "postcss-html": "^1.5.0",
    "sass": "^1.54.8",
    "sass-loader": "10",
    "stylelint": "^14.13.0",
    "stylelint-config-recommended-vue": "^1.4.0",
    "stylelint-config-standard": "^28.0.0"
  },
  "browserslist": [
    "defaults"
  ]

**Comment by wadguk** [comment]
`export default {
  // Disable server-side rendering: https://go.nuxtjs.dev/ssr-mode
  ssr: true,

  // Global page headers: https://go.nuxtjs.dev/config-head
  head () {
    const meta = [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'format-detection', content: 'telephone=no' }
    ]
    let script = []

    if (process.env.NODE_ENV === 'production') {
      meta.push({ name: 'facebook-domain-verification', content: 'aukx5hfkaao23wr0eimdalbf8iavu8' })
      script = [
        {
          innerHTML: `
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '570028715040158');
            fbq('track', 'PageView');
          `,
          type: 'text/javascript',
          charset: 'utf-8'
        },
        { async: true, src: 'https://www.googletagmanager.com/gtag/js?id=G-J15NKH21NL%22%3E' },
        {
          innerHTML: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-J15NKH21NL');
          `,
          type: 'text/javascript',
          charset: 'utf-8'
        },
        {
          innerHTML: `
            (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3415316,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
            })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
          `,
          type: 'text/javascript',
          charset: 'utf-8'
        }
      ]
    }

    return {
      title: 'quantelica',
      htmlAttrs: {
        lang: 'en'
      },
      meta,
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap'
        }
      ],
      script,
      __dangerouslyDisableSanitizers: ['script']
    }
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '~assets/scss/base.scss',
    "vue-connect-wallet/dist/style.css"
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    '~/plugins/axios',
    '~/plugins/vue-js-modal',
    { src: 'plugins/tooltip.js', mode: 'client' },
    { src: 'plugins/owl.js', mode: 'client' },
    { src: '~/plugins/lodash', mode: 'client' },
    { src: '~/plugins/vuejs-datepicker', mode: 'client' },
    { src: '~/plugins/v-click-outside', ssr: false },
    { src: '~/plugins/launcher-updating', mode: 'client' }
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    // '@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/stylelint
    // '@nuxtjs/stylelint-module',

    // https://typescript.nuxtjs.org/guide/setup#configuration
    '@nuxt/typescript-build'
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    '@nuxtjs/axios',
    'cookie-universal-nuxt',
    '@nuxtjs/auth-next',
    'vue-scrollto/nuxt'
  ],

  sentry: {
    config: {
      debug: true
    },

    clientIntegrations: {
      CaptureConsole: {
        levels: ['log']
      }
    },

    serverIntegrations: {
      CaptureConsole: {
        levels: ['log']
      }
    }
  },

  middleware: ['tfa-guard'],

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    standalone: true,
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      }),
      config.node = {
        fs: 'empty'
      }
    },
  },

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    proxyHeaders: true,
    proxy: true,
    credentials: true
  },

  publicRuntimeConfig: {
    axios: {
      browserBaseURL: process.env.BROWSER_BASE_API_URL
    },
    cookie: {
      domain: process.env.COOKIES_DOMAIN
    },
    url: process.env.APP_URL,
    browserApiUrl: process.env.BROWSER_BASE_API_URL,
    imagesApiUrl: process.env.IMAGES_API_URL,
    isLauncher: process.env.IS_LAUNCHER,
    buyNftUrl: process.env.BUY_NFT_URL,
    envDev: process.env.ENV_DEV ?? true,
    STRAPI_URL: process.env.STRAPI_URL,
    STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN
  },

  privateRuntimeConfig: {
    axios: {
      baseURL: process.env.BASE_API_URL
    }
  },

  auth: {
    strategies: {
      local: {
        scheme: '~/schemes/custom',
        token: {
          property: 'response.token',
          global: true,
          type: false,
          maxAge: 31536000 // One year
        },
        endpoints: {
          login: { url: '/auth/login', method: 'post' },
          logout: { url: '/auth/logout', method: 'post' },
          user: { url: '/profile/get-user', method: 'get' }
        },
        user: {
          property: 'response.user',
          autoFetch: true
        }
      }
    },
    redirect: {
      login: '/account/login',
      logout: '/',
      callback: '/account/login',
      home: '/'
    }
  },

  router: {
    middleware: ['auth']
  }
}
`

**Comment by Adamj1232** [comment]
Closing issue as it was part of the build settings
