### ISSUE TITLE
Update Onboard Ledger Connect Kit deps

### ISSUE THREAD

**Issue by tuckerchapin** [blocknative/web3-onboard#2027]
### Current Behavior

[Ledger recently announced](https://x.com/ledger/status/1735291427100455293) a vulnerability in Ledger Connect Kit which Onboard depends on.

### What package is effected by this issue?

@web3-onboard/ledger

### Is this a build or a runtime issue?

N/A

### Package Version

Latest

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Blocknative’s Web3-Onboard pulls in the latest Ledger Connect Kit update. It is now pulling in 1.1.8. Please ensure you are using the latest version of Web3-Onboard let us know if you have any questions

We are working closely with the Ledger team as they improve and update their processes for the Ledger dependencies.

According to the Ledger team the malicious software was only delivered for 5 hours and believed to only be active for two - https://twitter.com/Ledger/status/1735326240658100414

Also for avoidance of doubt:

To confirm you are on the latest version, load dapp, select Ledger from the Web3-onboard option, open developer console, select Sources tab and expand the folder shown in the image below.

<img width="1889" alt="Screenshot 2023-12-14 at 09 28 18" src="https://github.com/blocknative/web3-onboard/assets/24457880/2566c75c-b71f-4190-8270-ba84f41f00f6">

**Comment by clathrop** [comment]
Can you address whether or not users utilizing the ledger connect kit via web3-onboard are potentially still vulnerable due to browsers cacheing the delivered package? Seems like the max-age for the package is 7 days. If a user doesn't clear his or her cache they could be loading the malicious package. Be safe out there.
