### ISSUE TITLE
[Feature]: enableMobileWalletLink for @coinbase/wallet-sdk

### ISSUE THREAD

**Issue by betulerkoc** [blocknative/web3-onboard#2090]
### Feature Description

I need to enable a direct connection for mobile use. According to the information provided [here](https://docs.cloud.coinbase.com/wallet-sdk/docs/deep-link), this feature is exclusively available in Coinbase Wallet SDK version 3.8.0 or later. However, as the current version stands at 3.7.2, I am unable to access this feature.

Can you please increase the version to 3.8.0 or above and add 'enableMobileWalletLink' to CoinbaseWalletSDKConstructor

**Comment by Adamj1232** [comment]
Hi @betulerkoc! Thanks for reporting this!
I have created a PR to update the package deps and extend some new init props for the Coinbase SDK
That PR can be found [here](https://github.com/blocknative/web3-onboard/pull/2093)

**Comment by Adamj1232** [comment]
This is available with the latest version of @web3-onboard/coinbase
Please feel free to let us know if there are any other issues!
