### ISSUE TITLE
Non-existing Inter font was used

### ISSUE THREAD

**Issue by remy727** [blocknative/web3-onboard#2091]
### Current Behavior

![image](https://github.com/blocknative/web3-onboard/assets/69775411/fd434e11-f2a4-46ef-8c82-7451660dbef1)

### Expected Behavior

No errors

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.2.6

### Node Version

21.5.0

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@remy727 thank you for reporting this issue. It is a known problem that the Inter font url has changed.
I have a PR to update this [here](https://github.com/blocknative/web3-onboard/pull/2092) and it should be out shortly.
Cheers!

**Comment by Adamj1232** [comment]
This is available with the latest version of @web3-onboard/core | react | vue | solid
Please feel free to let us know if there are any other issues!
