### ISSUE TITLE
Documentation mention wrong package `@web3-onboard/injected`

### ISSUE THREAD

**Issue by marc-aurele-besner** [blocknative/web3-onboard#2139]
### Current Behavior

At multiple place in docs and Readme we mention to install `@web3-onboard/injected` but this package does not exist.

### Expected Behavior

The correct package is `@web3-onboard/injected-wallets`

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

latest

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by marc-aurele-besner** [comment]
- #2140

**Comment by Adamj1232** [comment]
@marc-aurele-besner thank you for flagging! This has been updated!
