### ISSUE TITLE
Impossible to use transaction-preview package

### ISSUE THREAD

**Issue by 0xOzy42** [blocknative/web3-onboard#2196]
### Current Behavior

The transaction-preview package doesn't seem to work when imported into the dapp. The error displayed indicates that the utils import of ethers is not working.

### Steps To Reproduce

1. npm i @web3-onboard/transaction-preview
2.  import the transactionPreviewModule into the config file

### What package is effected by this issue?

@web3-onboard/transaction-preview

### Is this a build or a runtime issue?

N/A

### Package Version

@web3-onboard/transaction-preview 2.0.9

### Node Version

20.10.0

### Relevant log output

```shell
./node_modules/@web3-onboard/transaction-preview/dist/index.js
Attempted import error: 'ethers'.'utils' is not exported from 'ethers' (imported as 'ethers').
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@0xOzy42 Transaction Preview has been fully deprecated and sunset as we no longer support simulating transaction on Ethereum. Thanks for using Web3-Onboard!
