### ISSUE TITLE
Add chain method if chain is not available

### ISSUE THREAD

**Issue by vanxh** [blocknative/web3-onboard#2235]
### Current Behavior

if a user don't has the chain in their wallet that we passed to setChain method then it errors. we should automatically prompt the user to add the chain to their wallet / have a method in library to add chain to a user's wallet.

### Expected Behavior

When we call setChain with a chain that is not available in user's wallet then it should prompt the user to add the network to their wallet and then switch to that chain.

### Steps To Reproduce
```ts
          const { setChain } = useOnboard();
          ...
          await setChain({
            chainId: '0x38',
            token: 'BSC',
            wallet: connectedWallet.value?.label,
            label: 'Binance Smart Chain'
          })
```

### What package is effected by this issue?

@web3-onboard/vue

### Is this a build or a runtime issue?

N/A

### Package Version

2.8.0

### Anything else?

It will make it a good user experience to automatically prompt the user to add the network if the chain is not available in user's wallet so it prevents any errors.

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Vitomir2** [comment]
@vanxh I am experiencing errors when the chain doesn't exist, too. The strange thing is that some time ago, it was working fine.

Did you solve it by updating the package or what?
