### ISSUE TITLE
Can not signMessage when use safe wallet connect by Walletconnect

### ISSUE THREAD

**Issue by yanfeizuo** [blocknative/web3-onboard#2277]
### Current Behavior

Call signMessage, get 0x0.

### Expected Behavior

Get none zero hex string

### Steps To Reproduce

1. env
- Walletconnect: @web3-onboard/walletconnect@2.6.1
- ethers version: ethers@6.11
- Safewallet: https://safe.meter.io
2. run
- connect by
- get signer: new ethers.BrowserProvider(provider).getSigner()
- call signMessage: signer.signMessage(SIGN_MSG)
3. If I use metamask or connect mobile wallet by walletconnect to signMessage are correct, so I'm not sure if this is walletconnect's problem. 

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Build

### Package Version

2.6.1

### Node Version

18

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by tdeli123** [comment]
any update on that?

**Comment by yanfeizuo** [comment]
not yet
