### ISSUE TITLE
[Bug]: Wallet provider not updating correctly when network is changed

### ISSUE THREAD

**Issue by chiuzon** [blocknative/web3-onboard#808]
### Current Behavior

Wallet provider isn't updated correctly after the network is changed to the correct network.

### Expected Behavior

Wallet provider should change when new network is selected instead of changing when the network select process begins.

### Steps To Reproduce

1. Create default Onboard() object with network set to 1
2. Connect to network (walletSelect(), walletCheck())
3. walletReset()
4. onBoard.config({networkId: 4});
5. Connect to network (walletSelect(), walletCheck())

### Onboard Version

1.37.2

### Node Version

14

### What browsers are you seeing the problem on?

Firefox

**Comment by taylorjdawson** [comment]
@chiuzon Which wallet are you using? And what do you mean by "Wallet provider should change"?

**Comment by taylorjdawson** [comment]
@greedythib This seems like a separate issue? Is this the issue with the network value returned from the network callback?

**Comment by miguelmota** [comment]
Some users are reporting a similar issue with the 1inch mobile wallet. When changing networks on the app (eg Ethereum to Polygon) it doesn't trigger the subscriptions network callback so it makes it impossible to do any transactions because onboardjs doesn't detect the mobile wallet network

```js
...
subscriptions: {
  network: (connectedNetworkId) => {
   // this doesn't get trigged on network change on certain wallets
  }
}
```

**Comment by Adamj1232** [comment]
@miguelmota is this still an issue you are experiencing? Our current recommendation would be to upgrade to the latest version of web3-onboard that has active development teams working on features, enhancements and bugs

**Comment by Adamj1232** [comment]
Closing this issue as I have been unable to contact. Please reopen if the issue persists
