### ISSUE TITLE
[Bug]: Empty screen (react app broken) if no MetaMast installed - Opera Browser

### ISSUE THREAD

**Issue by lobovkin** [blocknative/web3-onboard#851]
### Current Behavior

> Uncaught TypeError: Cannot read properties of undefined (reading 'isMetaMask')

window[injectedNamespace] is undefined if no MetaMast installed and checking provider.isMetaMask breaks everything.
`const validWallets = filteredWallets.filter(({ injectedNamespace, checkProviderIdentity, label }) => {
            const provider = window[injectedNamespace];
            const walletExists = checkProviderIdentity({ provider, device });
            if (walletExists &&
                provider.isMetaMask &&
                label !== ProviderLabel.MetaMask &&
                label !== 'Detected Wallet') {
                removeMetaMask = true;
            }
            return walletExists;
        });`

### Expected Behavior

Do not break the app, silently hide MetaMask button.

### Steps To Reproduce

Remove MetaMast extension

### Onboard Version

2.0.1

### Node Version

17.6

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'isMetaMask')
```

**Comment by Adamj1232** [comment]
@lobovkin looking into this now but having troubles reproducing...are you running locally or hitting https://reactdemo.blocknative.com/ ?

**Comment by Adamj1232** [comment]
Ahh gotcha, looking into this now and will have a fix shortly

**Comment by Adamj1232** [comment]
https://github.com/blocknative/web3-onboard/pull/853 has a fix for this issue and should be out by the EOD
