### ISSUE TITLE
Is there a way for MetaMask to show up in the modal if it isn't installed/injected?

### ISSUE THREAD

**Issue by anthonysgro** [blocknative/web3-onboard#861]
The other wallets like Torus, WalletConnect, Coinbase, etc. have the option to put in the modal like this:

`import Onboard from "@web3-onboard/core";
import injectedModule from "@web3-onboard/injected-wallets";

import torusModule from "@web3-onboard/torus";
const torus = torusModule();

const injected = injectedModule();

const onboard = Onboard({
    wallets: [injected, torus, ledger, keystone, walletLink, walletConnect],

... etc
`

Metamask shows up when I have it installed because of the "injected" feature, but when I don't have it installed it doesn't show up and I don't see anything that would let me do that. I am not very experienced in this area so if I'm missing something please tell me!

**Comment by aaronbarnardsound** [comment]
Hey @anthonysgro we made a design decision for version 2 that web3-onboard would only show wallets that were available to the user. The injected wallet module will detect if MetaMask is available (or any other injected wallets) and display them for selection.

**Comment by anthonysgro** [comment]
Ah okay, makes sense. I also see the "RecommendedWallets" property which is super helpful. I appreciate the quick response!
