### ISSUE TITLE
[Bug]: TypeError: chain is undefined - when selecting Ropsten Test Network in Metamask

### ISSUE THREAD

**Issue by meglio** [blocknative/web3-onboard#870]
### Current Behavior

1. Select Ropsten Test Network in Metamask.
2. Connect via API.

An error is thrown: `TypeError: chain is undefined`
.. in `getEns()`
.. in `updateAccountDetails()`

Looks like `updateAccountDetails()` cannot find a chain by its `namespace` and `id`, and as a result, it calls `getEns()` with undefined:

![image](https://user-images.githubusercontent.com/282177/157350407-dd20b171-a882-497d-99ca-9d811a228e12.png)

### Steps To Reproduce

1. Select Ropsten Test Network in Metamask.
2. Connect via API.

### Onboard Version

@web3-onboard/core 2.0.7, @web3-onboard/injected-wallets 2.0.1

### Node Version

v16.14.0

### What browsers are you seeing the problem on?

Firefox

**Comment by meglio** [comment]
Wow this was quick.

**Comment by aaronbarnardsound** [comment]
No worries, thanks for reporting!
