### ISSUE TITLE
[Feature]: Introduce CSS variable for the content

### ISSUE THREAD

**Issue by wrap-that-potassium** [blocknative/web3-onboard#877]
### Feature Description

There is no CSS variable for the background color.

### Anything else?

I'd like to replace the white background in the content with another color:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/83176631/157719618-f7793beb-b65e-4376-8e58-2d117a6fa35a.png">

Introducing a `--onboard-connect-content-background` variable should solve this.

**Comment by aaronbarnardsound** [comment]
Hey @wrap-that-potassium that is a good suggestion. We will try and get this in to prod asap with a new CSS variable.

**Comment by Adamj1232** [comment]
@wrap-that-potassium closing as this update has been released with #929
