### ISSUE TITLE
[Bug]: Gnosis Wallet not displaying on Modal

### ISSUE THREAD

**Issue by brunomenezes** [blocknative/web3-onboard#883]
### Current Behavior

**The title is half true**. Let me explain; After adding the gnosis wallet to the list, opening my Dapp and starting the modal I can't see the Gnosis Safe as an option. But, if I go to [gnosis-safe app](https://gnosis-safe.io/app/) and open my Dapp from there it will be in the list and connects as expected.

### Expected Behavior

I was expecting the same behaviour as V1, where it displays in the list **indicating to the user that we have support** and once the user clicks it would ask them to go to the [gnosis-safe app](https://gnosis-safe.io/app/) so they can do the usual procedure through gnosis app. 

### Steps To Reproduce

1. Install @web3-onboard/core@2.0.9 and @web3-onboard/gnosis@2.0.1
2. Instantiate the gnosis module (no params was passed down)
3. Do the onboard wallets / chains setup as usual
4. Open onboard modal to select a wallet

### Onboard Version

2.0.9

### Node Version

v16.13.2

### What browsers are you seeing the problem on?

Chrome

**Comment by aaronbarnardsound** [comment]
Hey Bruno, yes this is one of main differences between version 1 and version 2. We believe to improve the UX of connecting a wallet, that it is better to only show wallets that the user can successfully connect to. To indicate support for Gnosis safe, could you add an icon to your app somewhere that links them to your app via Gnosis safe instead?

**Comment by brunomenezes** [comment]
I see, but the suggested path would break the idea of a better UX, no? because, I have the modal with the wallets but I also have somewhere else let's say an icon to the gnosis safe to redirect you to the gnosis safe app. I am assuming I can't add anything in the modal at this point. For example, if I start that module with `whitelistedDomains:[]` and head to gnosis safe app I see exactly what I was expecting in the first place and that is why I opened the issue. 

Here is a screenshot of the nice warning message and an explanation of what should be done with the above config and opening inside gnosis-safe-app. 😄 

![image](https://user-images.githubusercontent.com/1239768/159203919-f18dfa56-ac47-4bff-a0f5-490b5047d37d.png)

**Comment by nicosampler** [comment]
This should be documented properly. Seems like this provider is intended to be used only when the app is a safe-app.

**Comment by majdeddinea** [comment]
Hello, The same problem until now that Gnosis Wallet not displaying on Modal, but it is working when using [gnosis-safe app](https://gnosis-safe.io/app/)
I see that if we did the same warning message in the screenshot, it is going to be bizarre because we should see this warning message when we are not in the gnosis-safe app, not the opposite. I am working on it, but I did not find until now the way to add a warning message when selecting wallet in blocknative V2.

![image](https://user-images.githubusercontent.com/1239768/159203919-f18dfa56-ac47-4bff-a0f5-490b5047d37d.png)
