### ISSUE TITLE
[Feature]: Use @coinbase/wallet-sdk instead of deprecated walletlink package

### ISSUE THREAD

**Issue by nbeuchat** [blocknative/web3-onboard#885]
### Is your request related to a problem?

It is possibly related to https://github.com/ethereumjs/ethereumjs-abi/issues/67

### Feature Description

The [`walletlink`](https://www.npmjs.com/package/walletlink) package is deprecated in favor of [`@coinbase/wallet-sdk`](https://www.npmjs.com/package/@coinbase/wallet-sdk).

**Comment by aaronbarnardsound** [comment]
Closed via #904
