### ISSUE TITLE
[Bug]: Error incorrectly asks to use import to load ES Module

### ISSUE THREAD

**Issue by lukeod6** [blocknative/web3-onboard#889]
### Current Behavior

From previously using BNC-onboarder V1 and attempting to upgrade to the latest version after installing the node packages and attempting to launch the app there is an error that suggests that we must us import to load ES modules. We don't use any requires in the repo and also as the error suggests the source of the error seems to be in the node package itself. We are a Vue stack that uses Nuxt js
 
Current stack:
Npm 6
Vue 2.6.11
Nuxt 2.15.8
Ethers 5.4.7

### Expected Behavior

Expect the app to launch without erroring and launching the modal

### Steps To Reproduce

1. install core and injected wallets versions of app
3. start up a local server and you will see the error

### Onboard Version

2.0.11

### Node Version

12.22.6

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
Must use import to load ES Module: ../node_modules/@web3-onboard/core/dist/index.js require() of ES modules is not supported. require() of ../node_modules/@web3-onboard/core/dist/index.js from ../node_modules/@nuxt/vue-renderer/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ../node_modules/@web3-onboard/core/package.json.
```

**Comment by leovct** [comment]
Hello, any news regarding this issue? We're stuck migrating from `bnc-onboard` to `web3-onboard` :(
```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/@web3-onboard/react/dist/index.js from .../.next/server/pages/_app.js not supported.
Instead change the require of index.js in .../.next/server/pages/_app.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by taylorjdawson** [comment]
@leovct @ayudh37 @lukeod6 
Try setting this in your nuxt.config.js file:

```
 build: {
    standalone: true,
  }
```

**Comment by leovct** [comment]
@taylorjdawson it doesn't work on my end unfortunately

**Comment by aaronbarnardsound** [comment]
@leovct I just spun up a new next.js app and added web3-onboard and injected wallets and couldn't replicate the error. Here is the repo if you want to try it? https://github.com/aaronbarnardsound/next-js-web3-onboard.

**Comment by aaronbarnardsound** [comment]
Hey @lukeod6 and @ayudh37 I setup a new Nuxt project and added the core and injected-wallets packages and saw the same error. I then added the suggestion from @taylorjdawson (`build.standalone = true`) to the config file and it all works smoothly from there. I have a repo you can check out [here](https://github.com/aaronbarnardsound/nuxt-js-web3-onboard).

**Comment by aaronbarnardsound** [comment]
Closing this for now as there is a solution above for Nuxt projects and these instructions have been added to documentation. Also could not replicate the issue in Next.js.

Feel free to reopen if you are still seeing issues.

**Comment by leovct** [comment]
> Closing this for now as there is a solution above for Nuxt projects and these instructions have been added to documentation. Also could not replicate the issue in Next.js.
> 
> Feel free to reopen if you are still seeing issues.

Hi! To inform you about the problem encountered when using the web3-onboard library with nextjs, we were using nextjs v10 and we switched to v12 which solved all the `ERR_REQUIRE_ESM` issue. All good!
