### ISSUE TITLE
[Feature]: Using BlockWallet

### ISSUE THREAD

**Issue by greedythib** [blocknative/web3-onboard#892]
### Is your request related to a problem?

Hi guys, I would like to add BlockWallet to my Blocknative connection options. It currently works through detected wallet when BlockWallet is set to default, hence hiding Metamask injected wallet. 

Thanks!

### Feature Description

Is there any other way I could add it while still having Metamask ?

**Comment by Adamj1232** [comment]
@greedythib we have a card to get this knocked out in the next couple weeks and will update you when that is completed

**Comment by greedythib** [comment]
amazing! thank you @Adamj1232

**Comment by greedythib** [comment]
@Adamj1232  does a card mean that there will be a separate plugin for Blockwallet?

**Comment by Adamj1232** [comment]
@greedythib I believe it is an injected wallet so it would come out in a new version of the injected wallets package
Pinging @taylorjdawson as he may have some insight

**Comment by greedythib** [comment]
Thanks @Adamj1232! @taylorjdawson do you know how Blockwallet will be integrated in the new blocknative version?

**Comment by Adamj1232** [comment]
@greedythib Blockwallet support has been merged and is available in the latest version of the injected-wallets package!
