### ISSUE TITLE
[Bug]: how to customizing CSS ?

### ISSUE THREAD

**Issue by chutuan1126** [blocknative/web3-onboard#899]
### Onboard Version

v2

### Node Version

14

**Comment by Adamj1232** [comment]
Hello @chutuan1126 there is a video available around full web3-onboard customization including customizing the CSS HERE -> https://youtu.be/XbmylsqmD3k
Closing as there is not issue reported, you can reopen if there is a specific package issue.
Please join our discord for dev support.
Thanks again for reaching out!
