### ISSUE TITLE
[Feature]: Opera crypto browser support.

### ISSUE THREAD

**Issue by xyzz0121** [blocknative/web3-onboard#908]
### Is your request related to a problem?

I opened https://zapper.fi (which use BN lib) in Opera crypto browser, click "Opera" option,  and can't connect the wallet. 
Weird! The website prompts me to download the browser.
![screenshot-1](https://user-images.githubusercontent.com/41335762/160558643-36365271-57bf-4fc6-8c9a-0a51b566a768.png)

### Feature Description

When I connect wallet, I select "Opera" option and can connect the wallet in Opera crypto browser not prompts me to download the browser.

### Anything else?

Opera crypto browser download: https://www.opera.com/crypto/next
Website which use this lib: https://zapper.fi

**Comment by xyzz0121** [comment]
The Opera crypto browser can be detected with the window.ethereum.isOpera flag.

**Comment by aaronbarnardsound** [comment]
Hey @xyzz0121 I can't seem to replicate this on my end and can successfully connect my opera wallet to zapper.fi. 
<img width="430" alt="Screen Shot 2022-04-01 at 12 23 39 pm" src="https://user-images.githubusercontent.com/29873495/161176642-1af914db-48e6-4bd2-a242-81d06a042e76.png">
You could try resetting permissions and try again.

**Comment by aaronbarnardsound** [comment]
Closed via #920
