### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by francose** [blocknative/web3-onboard#912]
### Current Behavior

After installing the package into the project here what i m getting below;
it s expecting lower version i assume but the only way i was resolving this issue with downgrading the react-scripts 
however i dont know is this expected behavior with react-scripts > 5.0

![image](https://user-images.githubusercontent.com/13445813/160905763-dc82d67b-aee6-4abf-80fb-824d6e33d175.png)

### Steps To Reproduce

npm run start

### Onboard Version

2.1.0

### Node Version

i have tried 12 and 16

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by taylorjdawson** [comment]
Hey @francose thanks for bringing this to our attention. What framework are you using?

**Comment by whatsyourgithub** [comment]
See https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

React scripts 5 uses webpack 5. I've been sticking with react scripts 4 for the time being.

**Comment by francose** [comment]
Thank you very much i dont know why it keeps giving me same error. I will try to rebuild in a new project..

**Comment by francose** [comment]
@taylorjdawson Thanks it all worked out.
