### ISSUE TITLE
[Bug]: Build error: Cannot find module './i18n/en.json'

### ISSUE THREAD

**Issue by bisio2332** [blocknative/web3-onboard#913]
### Current Behavior

I got an error when I try to build my Angular app using `@web3-onboard/core` :
`Error: node_modules/@web3-onboard/core/dist/types.d.ts:7:21 - error TS2307: Cannot find module './i18n/en.json' or its corresponding type declarations.`
http://joxi.ru/V2VkjdGFBdeygA

As we can see we have no this file in `node_module` folder http://joxi.ru/KAxRabgHVZQ7Pm
At the same time we have it in repo:
http://joxi.ru/1A5eVXRI4DWVXA

### Expected Behavior

Expect to have no errors with the build

### Steps To Reproduce

1. Install core wallets versions of app
2. Start up a local server and you will see the error

### Onboard Version

2.1.0

### Node Version

16.13.2

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Error: node_modules/@web3-onboard/core/dist/types.d.ts:7:21 - error TS2307: Cannot find module './i18n/en.json' or its corresponding type declarations.

import type en from './i18n/en.json';
                      ~~~~~~~~~~~~~~~~
✖ Failed to compile.
```

**Comment by aaronbarnardsound** [comment]
Hey @bisio2332 what bundler are you using? Could you try deleting your node_modules and re-running `yarn` / `npm i`? I have not seen this build error before and cannot replicate locally.

**Comment by bisio2332** [comment]
Hello @aaronbarnardsound , thank you for your answer. 

Yea I deleted my `node_modules` and re-ran it but it did not help. I tried all versions of`@web3-onboard/core` library but I faced the same result.

I am using `Angular CLI` to build the app.

You can easily create a clear Angular project with the latest version. 
Add `@web3-onboard/core` and after that try to do `ng serve`.
For a clear Angular project, it does not work for me as well. 
Thank you

**Comment by aaronbarnardsound** [comment]
Hey @bisio2332 does adding the following to the `compilerOptions` parameter in your `tsconfig.json` file fix it?

```json
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}
```

**Comment by bisio2332** [comment]
Hi @aaronbarnardsound I tried your solution with my project and with the clear Angular Project, but unfortunately, it didn’t help me 😔. Should I give more information for you? 
Thanks

**Comment by clostao** [comment]
Does it still needed to use the --resolveJsonModule? I'm running into the same problem than @aaronbarnardsound, with that resolveJsonModule set to `true`, it works. Is it necessary or I'm running into sth?
