### ISSUE TITLE
[Bug]: Why explicitly remove MetaMask?

### ISSUE THREAD

**Issue by schonfeld** [blocknative/web3-onboard#914]
### Current Behavior

When a user has multiple injected web3 providers(e.g. {CoinbaseWallet, MetaMask}), web3-onboard explicitly hides the MetaMask option. Why was this logic implemented? Why hide MetaMask, specifically? Some of our users have MetaMask, plus another injected wallet, and want the ability to use MM.

https://github.com/blocknative/web3-onboard/blob/be9e6a6819fd623038cb0d6300391ec72acb85ef/packages/injected/src/index.ts#L67

### Onboard Version

2

### Node Version

14.7.0

**Comment by aaronbarnardsound** [comment]
That logic is there to remove MetaMask in the case that a provider has the `isMetaMask` property set to true, but is not MetaMask.

In the case that you are referring to, when a user has two extensions installed that both sit on the `window.ethereum` namespace, one will overwrite the other, making the first extension (usually MM) unavailable to the app. In the case of Coinbase wallet they keep the reference to the MM provider and add it to a `providers` property. We are working on an enhancement that checks that parameter and includes all providers that are included in that array. We have a working branch [here](https://github.com/blocknative/web3-onboard/tree/enhancement/handle-cb-mm) that we are working on testing further before releasing.

**Comment by schonfeld** [comment]
Of course our users just so happened to have found the one pair that does work right :)

Thanks for the detailer. Will watch out for the next releases...

> That logic is there to remove MetaMask in the case that a provider has the `isMetaMask` property set to true, but is not MetaMask.
> 
> In the case that you are referring to, when a user has two extensions installed that both sit on the `window.ethereum` namespace, one will overwrite the other, making the first extension (usually MM) unavailable to the app. In the case of Coinbase wallet they keep the reference to the MM provider and add it to a `providers` property. We are working on an enhancement that checks that parameter and includes all providers that are included in that array. We have a working branch [here](https://github.com/blocknative/web3-onboard/tree/enhancement/handle-cb-mm) that we are working on testing further before releasing.
