### ISSUE TITLE
[Feature]: Create hook to switch locale

### ISSUE THREAD

**Issue by Kadajett** [blocknative/web3-onboard#918]
### Is your request related to a problem?

Right now, the locale only switches if the browser language changes. But, our application offers a selection to change language as well. I don't see any config change available after initialization, so this seems to be impossible. 

### Feature Description

Provide local setter in react hooks and subsequent non-hook implementations

**Comment by aaronbarnardsound** [comment]
Hey @Kadajett we can definitely expose the function to change the locale. We will try to get to this in the next couple of weeks.

**Comment by taylorjdawson** [comment]
merged into develop: #986
