### ISSUE TITLE
[Bug]:  Custom injected wallet validation and documentation differencies

### ISSUE THREAD

**Issue by band94** [blocknative/web3-onboard#921]
### Current Behavior

As the [documentation](https://docs.blocknative.com/onboard/injected-wallets#adding-custom-injected-wallets) shows, you don't need to define `checkProviderIdentity`-t, but the `InjectedWalletModule` interface  requires it.

Also in the validation:
- `getIcon` and `getInterface` require arity, but the example shows otherwise.
- `checkProviderIdentity` has double `.required` check
- `providerIdentityFlag: Joi.string().required()` missing

### Expected Behavior

Need to fix the validation and update the given example correcty according to the changes.

### Steps To Reproduce

Just use the example given in the doc

### Onboard Version

2.0.2

### Node Version

16

**Comment by aaronbarnardsound** [comment]
Hey @band94 we will take a look at this, thanks for reporting.

**Comment by taylorjdawson** [comment]
Fixed in #988
