### ISSUE TITLE
[Feature]: Return boolean value when calling setChain from react package

### ISSUE THREAD

**Issue by enzoferey** [blocknative/web3-onboard#923]
### Is your request related to a problem?

As of right now, I'm not aware of any way to know if the `setChain` call has been successful when using the React package.

### Feature Description

`setChain` of the core package [signature](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard/packages/core/src/chain.ts#L14) returns `Promise<boolean>`. We should be able to return the same type for the React package.

It would be enough to return the return value of the core package function here:

https://github.com/blocknative/web3-onboard/blob/83e93ed5fbd696b1cacd5d033d20da1b37ce5084/packages/react/src/index.ts#L111-L117

it would become:

```ts
const set = useCallback(async (options: SetChainOptions) => {
    setInProgress(true)

    const hasSuccess = await setChain({ ...options, wallet: walletLabel })

    setInProgress(false)

    return hasSuccess;
  }, [])
```

### Anything else?

Let know if you are interested in a PR 👍🏻

**Comment by aaronbarnardsound** [comment]
Hey @enzoferey that is a good suggestion and a PR would be most welcome!

**Comment by enzoferey** [comment]
Sorry for the delay, done at https://github.com/blocknative/web3-onboard/pull/956.

**Comment by Adamj1232** [comment]
Thank you for adding your PR! It has been merged and released with the latest version of the @web3-onboard/react #956
