### ISSUE TITLE
[Feature]: update language around Coinbase Desktop extension vs Coinbase mobile app

### ISSUE THREAD

**Issue by morozj01** [blocknative/web3-onboard#926]
### Feature Description

Low priority issue but would it be possible to clarify the language differentiating the Coinbase mobile app vs the Coinbase extension:
![image](https://user-images.githubusercontent.com/28926919/162271548-c24dac0d-7ac6-4e0f-bd1f-03d55c964672.png)

We have seen some confusion here regarding what to do when both options are presented. 

Potentially:
Coinbase Wallet -> Coinbase Extension
Coinbase -> Coinbase Mobile

**Comment by morozj01** [comment]
Happy to open a PR if you agree this is correct

**Comment by aaronbarnardsound** [comment]
Yeah I agree with this as well. I was thinking another option is that we could give both modules the same label and then dedupe wallet names inside the core libary so that only one option displayed.

**Comment by aaronbarnardsound** [comment]
Closed via #1007 
We decided to name both Coinbase Wallet and then deduplicate if both exist.
