### ISSUE TITLE
[Bug]: magic wallet UX bugs

### ISSUE THREAD

**Issue by jadbox** [blocknative/web3-onboard#932]
### Current Behavior

"@web3-onboard/magic": "^2.0.0",
"@web3-onboard/core": "^2.2.0",

Bug #1: The email sign in modal pops up BEHIND Onboard.js wallet prompt.
<img width="596" alt="Screenshot 2022-04-11 072046" src="https://user-images.githubusercontent.com/595843/162760923-19efabd3-f69d-4ddf-9686-d89201625f18.png">

Bug #2: On page reload, there should be a way to reconnect Magic without the user re-inputting their email. Ideally we should be able to store in localstorage and then provide to the Magic init constructor the email address to use on page reload.
<img width="526" alt="Screenshot 2022-04-11 072334" src="https://user-images.githubusercontent.com/595843/162761421-8c626b55-85fa-43d2-927d-0826bbc1b320.png">

### Expected Behavior

Bug #1) Magic email login modal should be above the Onboard UX
Bug #2) there should be a way to provide the Magic adaptor an email address to use to auto-reconnect on page reload

### Onboard Version

2.2.0

### Node Version

16

**Comment by Adamj1232** [comment]
Hi @jadbox I am looking into this now. I will also expose the z-index of the login modal as an external variable...I have a PR [here](https://github.com/blocknative/web3-onboard/pull/934) where you can track the progress

**Comment by Adamj1232** [comment]
Closing issue as this has been addressed in the latest Magic 2.0.1 release. Thank you for pointing this out! - https://github.com/blocknative/web3-onboard/releases/tag/web3-onboard%2Fmagic-v2.0.1
