### ISSUE TITLE
[Feature]: Pre set Chain

### ISSUE THREAD

**Issue by bisio2332** [blocknative/web3-onboard#938]
### Is your request related to a problem?

Hello, it would be great to be able set chain before user choose a wallet. 
Currently, I have access to `setChain` method only after initialization onboard and it looks like a workoround, because I always connect to the one default network and after that immediately change it to the choosen by the user.

### Feature Description

To be able to set Chain before connect to wallet.
For example add to the onBoard init option object `selectedChain`

**Comment by bisio2332** [comment]
More detailed example for adding `selectChain` to the onBoard object
`onboard = Onboard({
      wallets: [injected, walletConnect, coinbase, ledger, trezor, gnosis],
      selectedChain: {
                id: '0x1',
                token: 'ETH',
                label: 'Ethereum Mainnet',
                rpcUrl: this.ETH_MAINNET_RPC
            }
     }),`

**Comment by aaronbarnardsound** [comment]
Hey @bisio2332 is there any reason as to why it is an issue for you to call the `setChain` method after connecting a wallet? 

The chain that a wallet is connected to cannot be set until after the wallet has been selected and the current connected chain has been established. Adding the additional options you suggest to the Onboard initialization object just adds complexity to Onboard without any discernible benefit.

**Comment by aaronbarnardsound** [comment]
Closing this issue for now, @bisio2332  feel free to reopen when you are ready to respond.
