### ISSUE TITLE
[Bug]: Error with @web3-onboard/coinbase-wallet-sdk  

### ISSUE THREAD

**Issue by s-pcode** [blocknative/web3-onboard#942]
### Current Behavior

The current @web3-onboard/walletlink is deprecated in favour of @web3-onboard/coinbase-wallet-sdk  ,but there's no such package in the npm registry. 

### Onboard Version

"@web3-onboard/walletlink": "^2.0.1"

### Node Version

v16.13.1

**Comment by Adamj1232** [comment]
Thank you for pointing out this typo, The coinbase wallet package is available at https://www.npmjs.com/package/@web3-onboard/coinbase
I will get this updated, thanks again!
