### ISSUE TITLE
[Bug]: Metamask and Coinbase Wallet don’t show on mobile devices

### ISSUE THREAD

**Issue by bisio2332** [blocknative/web3-onboard#943]
### Current Behavior

Hello, There is no way to choose `Metamask` and `Coinbase wallet` on mobile devices http://joxi.ru/5mdpevGiq8LDLm
You can check it on reactdemo https://reactdemo.blocknative.com/
Thank you

### Expected Behavior

Users should be able to choose `Metamask` and `Coinbase wallet` on mobile devices

### Steps To Reproduce

1. Open https://reactdemo.blocknative.com/ on the mobile device
2. Click `Select a Wallet`
3. There is no `Metamask` and `Coinbase wallet` in opened modal dialog

### Onboard Version

2.2.1

### Node Version

16.13.2

**Comment by bisio2332** [comment]
@aaronbarnardsound @taylorjdawson one more thing was found by me
We can’t see `metamask` and `coinbase wallet` in incognito mode http://joxi.ru/vAW1jLVi3OZLWm
Thanks

**Comment by Adamj1232** [comment]
Closing as this is not an issue, please continue the conversation if needed and if a problem is found we can re-open this issue

**Comment by moymat** [comment]
Hi !

I'm continuing this discussion instead of opening a new one since I have a similar issue with Metamask on mobile.
In the Metamask app, the react demo is displaying the metamask option correctly, but not with my app (not present in the walletModules array in the onboard object's state). I checked the demo's code and it seems that my setup is correct. Currently I can connect to metamask with WalletConnect, but I would like to use metamask directly.

Metamask appears on desktop though.

<details><summary>My code if it helps :</summary>

```js
import injectedModule from "@web3-onboard/injected-wallets";
import ledgerModule from "@web3-onboard/ledger";
import { init, useConnectWallet, useSetChain } from "@web3-onboard/react";
import walletConnectModule from "@web3-onboard/walletconnect";
import { useCallback, useEffect, useState } from "react";

import logo from "../assets/logo.svg";

const injected = injectedModule();
const walletConnect = walletConnectModule();
const ledger = ledgerModule();

const { VITE_BLOCKCHAIN_RPC } = import.meta.env;

const onboard = init({
  wallets: [injected, ledger, walletConnect],
  chains: [
    {
      id: "0x1",
      token: "ETH",
      label: "Ethereum Mainnet",
      rpcUrl: VITE_BLOCKCHAIN_RPC,
    },
  ],
  appMetadata: {
    name: "app name",
    icon: logo,
    description: "app description",
    recommendedInjectedWallets: [
      { name: "MetaMask", url: "https://metamask.io" },
      { name: "Coinbase", url: "https://wallet.coinbase.com" },
      { name: "Binance", url: "https://www.binance.com" },
      { name: "Ledger", url: "https://www.ledger.com" },
    ],
  },
  accountCenter: {
    desktop: {
      enabled: false,
    },
  },
});

const useOnboard = () => {
  const [web3Onboard, setWeb3Onboard] = useState(onboard);
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet();
  const [{ chains, connectedChain, settingChain }, setChain] = useSetChain();

  const initOnboard = useCallback(async () => {
    const selectedWallet = window.localStorage.getItem("selectedWallet");

    const connectOptions: {
      autoSelect?: { label: string; disableModals: boolean };
    } = {};

    if (selectedWallet)
      connectOptions.autoSelect = {
        label: selectedWallet,
        disableModals: false,
      };

    await connect(connectOptions);
    await setChain({ chainId: "0x1" });
  }, [setChain, connect]);

  useEffect(() => {
    if (!wallet) return;
    window.localStorage.setItem("selectedWallet", wallet.label);
  }, [wallet]);

  useEffect(() => {
    initOnboard();
  }, [initOnboard]);

  return {
    wallet,
    address: wallet?.accounts[0].address,
    provider: wallet?.provider,
    connecting,
    initOnboard,
    disconnect,
  };
};

export default useOnboard;`

**Comment by Adamj1232** [comment]
@moymat is MetaMask not displaying on your app within MetaMask mobile?

**Comment by Adamj1232** [comment]
@moymat interesting, which versions of the react and injectedWallet packages are you using? Are you using SSR?

**Comment by moymat** [comment]
No SSR. For the versions :
```
"@web3-onboard/injected-wallets": "^2.0.5",
"react": "^17.0.2",
```

**Comment by moymat** [comment]
@Adamj1232 I already checked with vConsole and no errors.
Yes, metamask displays correctly with the demo :
![Screenshot_2022-05-02-18-39-04-808_io.metamask_1.jpg](https://user-images.githubusercontent.com/36814609/166288168-1aa65324-27c0-4d97-9b4e-a0bd26d64160.jpg)

**Comment by Adamj1232** [comment]
@moymat Using VConsole are you able to log out and see the MetaMask provider at `window.ethereum`?

**Comment by moymat** [comment]
It's `undefined`.

**Comment by Adamj1232** [comment]
@moymat that's really strange, especially within the MetaMask app.
You can try using `onboard.state.actions.setWalletModules([injected...])` as seen [here](https://github.com/blocknative/web3-onboard/tree/v2-web3-onboard/packages/core#actions-to-modify-state) and see if you can re-mount wallets after loading or on a specific action

**Comment by moymat** [comment]
Still no metamaks and window.ethereum is stil `undefined` :/
I tried with `useEffect`, `useLayoutEffect` and after an action, same result.

**Comment by Adamj1232** [comment]
@moymat hmm very strange, I don't know why it would be undefined after page load and if you are using within the MteMask app it should be there immediately. Extra strange that the Blocknative reactDemo is working within your MM app.
Unfortunately I don't have an Android to help troubleshoot but I will ask around on the team

**Comment by moymat** [comment]
I'll double check my code, maybe there is something that breaks the android metamask app in some way that prevent it to load it, but I don't know how it could.
I'll get back to you with my colleague's test result on his device.
Thank for the help!

**Comment by moymat** [comment]
@Adamj1232 Same issue on my colleague's android phone, no metamask option and I didn't find anything in my code that could explain this behavior.

**Comment by smallfish06** [comment]
@Adamj1232 Any update with this issue? 
I'm also having same issue with v2-web3-onboard

All components works fine with injected wallet + coinbase module in PC(chrome). 

But with **same code**(deployed website), using android, iphone(I've tested stable release between metamask v3.8.0~v5.0.2) with metamask application, only coinbase option appears. 
> I don't think nobody reach with this issue since 2021

With my short idea, after with some update on v2-web3-onboard, creating connection with injected wallet function to installed app(mobile) has broke. Because coinbase module + coinbase app on mobile works fine, only on injected wallet + installed app on mobile
 
pc
---
<img width="632" alt="image" src="https://user-images.githubusercontent.com/37919847/169655598-547b9d1e-b473-44e1-b9c3-f3c1493be5e4.png">

> it only has metamask extension

android
---
<img width="848" alt="image" src="https://user-images.githubusercontent.com/37919847/169655537-ed8e4683-b220-4fe8-922b-9cbf9b8a6d44.png">

> it has both metamask, coinbase application

**Comment by smallfish06** [comment]
@Adamj1232 @aaronbarnardsound 
I'm not that familiar with internal of this library, but can it be the clue?

https://github.com/blocknative/web3-onboard/commit/56623ac2877951d87e0eebe1d2b4c9cb3abb225e
```typescript
const metamask: InjectedWalletModule = {
  label: ProviderLabel.MetaMask,
  injectedNamespace: InjectedNameSpace.Ethereum,
  checkProviderIdentity: ({ provider }) =>
    !!provider && !!provider[ProviderIdentityFlag.MetaMask],
  getIcon: async (https://github.com/blocknative/web3-onboard/commit/7abe6af5854b4e785edea89738e4aca79e0ea80d => (await import('./icons/metamask.js')).default,
  getInterface: async () => ({
    provider: window.ethereum as EIP1193Provider
  }),
  platforms: ['all']
}
```
`window.ethereum as EIP1193Provider` has changed onto 
```typescript
function getInjectedInterface(
  identity: string
): () => Promise<{ provider: EIP1193Provider }> {
  return async () => ({
    provider: (window.ethereum.providers &&
    Array.isArray(window.ethereum.providers)
      ? window.ethereum.providers.find(provider => !!provider[identity])
      : window.ethereum) as EIP1193Provider
  })
}

```
Cause metamask has shipped this feature on all products, but we removed direct use of EIP1193Provider
https://github.com/ethereum/EIPs/issues/2319#issuecomment-658400151

**Comment by Adamj1232** [comment]
@smallfish06 the `Coinbase` wallet option being shown looks to be the Coinbase SDK package and not the `Coinbase Wallet` which is injected. With that package added the `Coinbase` option will show up even in the metamask app.
Can you clarify the problem you are facing for me?
Are you saying on Android within the MetMask app with the injected wallets package added to Onboard init you are not seeing MetaMask as an option?
On my iPhone I am able to see the MetaMask option within the MetaMask app and don't see the injected Coinbase Wallet option.
To troubleshoot the mobile provider `window.ethereum` you can use the VConsole package (as seen [here](https://github.com/blocknative/react-demo/blob/ea4e27628fffde4adfbc5fb1efb72991c8a0bb10/src/App.js#L11) ) Can you please let me know what the injected window object looks like at `window.ethereum` on devices/browsers causing you problems?

**Comment by smallfish06** [comment]
> @smallfish06 the `Coinbase` wallet option being shown looks to be the Coinbase SDK package and not the `Coinbase Wallet` which is injected. With that package added the `Coinbase` option will show up even in the metamask app. Can you clarify the problem you are facing for me? Are you saying on Android within the MetMask app with the injected wallets package added to Onboard init you are not seeing MetaMask as an option? On my iPhone I am able to see the MetaMask option within the MetaMask app and don't see the injected Coinbase Wallet option. To troubleshoot the mobile provider `window.ethereum` you can use the VConsole package (as seen [here](https://github.com/blocknative/react-demo/blob/ea4e27628fffde4adfbc5fb1efb72991c8a0bb10/src/App.js#L11) ) Can you please let me know what the injected window object looks like at `window.ethereum` on devices/browsers causing you problems?

Sorry for not clarifying the issue

below is our current code we use injected module+ coinbase module + walletconnect module
```typescript
import Onboard from '@web3-onboard/core'
import coinbaseWalletModule from '@web3-onboard/coinbase'
import injectedModule, {ProviderLabel} from '@web3-onboard/injected-wallets'
import walletConnectModule from '@web3-onboard/walletconnect'

import icon from 'shared/resources/icon.png'

const coinbaseWalletSdk = coinbaseWalletModule()
const injected = injectedModule({
  filter: {
    [ProviderLabel.Detected]: false
  }
})
const walletConnect = walletConnectModule()

const modules = [coinbaseWalletSdk, injected, walletConnect]

export const onboard = Onboard({
  wallets: modules,
  chains: [
    {
      id: "0x1",
      token: "ETH",
      namespace: "evm",
      label: "Ethereum Mainnet",
      rpcUrl: ''
    }
  ],
  appMetadata: {
    name: '',
    icon: icon,
    logo: icon,
    description: '',
    recommendedInjectedWallets: [
      {name: "MetaMask", url: "https://metamask.io"}
    ]
  }
})
```
```typescript
  const onConnectWallet = async () => {
    try {
      const wallets = await onboard.connectWallet()
      const {accounts} = wallets[0]
      setAccount(accounts[0])
    } catch (error) {
      console.error('Please, try again connecting wallet or reload the page')
      alert('Please, try again connecting wallet or reload the page')
    }
  }
```
After reading your comment, I found out situations are different
> On my iPhone I am able to see the MetaMask option within the MetaMask app and don't see the injected Coinbase Wallet option.

With using those code, android-S21, iphone-9 (both are metamask app installed) we can't see metamask option. only coinbase and walletconnect appears. 

I got those things(`window.ethereum`) with `chrome://inspect/#devices`, and found out reason.
- On desktop(PC) `window.ethereum` works fine(I mean they exists).
- But on mobile, `window.ethereum` is **`undefined`**, 

With the usage I understand, `window.ethereum` is auto injected and there's nothing client needs to do. 
We are using same code basis for mobile and pc (like monorepo). 
Can you comment what we are doing wrong?

**Comment by Adamj1232** [comment]
@smallfish06 thank you for clarifying!
MetaMask only injects the wallet provider within its browser and not on the global browser. Which is why you aren't seeing `window.ethereum` Wallets generally inject into the browser within their native applications on mobile.
You see it on desktop along with the wallet options because the extensions have injected the provider there. If you remove the extensions from your browser you won't see those options any longer.
Web3-Onboard only shows options that the users has available in the browser they are using, thus why you aren't seeing MetaMask on mobile using a browser that isn't within a Wallet App

**Comment by smallfish06** [comment]
@Adamj1232 Thanks, your comments definitely solved my question. 

What made me confuse is that some reference sites are using blocknative and able to call metamask app from mobile. 
by clicking open metamask, it redirects to `metamask.app.link/~~~`
Is V1 capable of calling app from mobile page? 
> If then what makes difference?

![KakaoTalk_Photo_2022-05-24-02-55-36 002](https://user-images.githubusercontent.com/37919847/169878936-939a5cd9-d510-4b4a-b19d-c9790d2abd36.jpeg)
![KakaoTalk_Photo_2022-05-24-02-55-35 001](https://user-images.githubusercontent.com/37919847/169878954-31d0e76b-6ad9-465d-a0b8-8ae09efe1874.jpeg)
t

**Comment by Adamj1232** [comment]
@smallfish06 V1 does have that ability but we haven't built that portion out in V2 yet. V2 only displays the injected wallets that are available in the browser. 
It would be helpful to our product team to add this request to the github issues for Onboard V2
A possible work around would be adding notes around this to the appMetaData.description within the init props or using the i18n props to change the verbiage anywhere in the app to whatever you would like - the defaults are found [here](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard/packages/core/src/i18n/en.json)
