### ISSUE TITLE
[Feature]: is it possible to have several injected wallets displayed?

### ISSUE THREAD

**Issue by greedythib** [blocknative/web3-onboard#944]
### Is your request related to a problem?

Hi, currently only one injected wallet is displayed when connecting with onboard ->
![Capture d’écran 2022-04-13 à 14 50 48](https://user-images.githubusercontent.com/12110896/163184022-718e7a57-134e-4313-b8ca-9b6e9b3e45dc.png)

 Is it possible to have several injected wallets displayed instead of one? 

Thanks!

**Comment by Adamj1232** [comment]
@greedythib which injected-wallets package version are you on? Which wallets are you wanting to show?
In the latest version of injected-wallets package, if a user has Coinbase wallet installed both CB and MM will be shown

**Comment by greedythib** [comment]
@Adamj1232 I am using the very last versions for react and injected-wallets modules. OK thanks, indeed coinbase injected wallet is displayed separately from metamask, that's amazing!

However, it seems like `await connect()` does not trigger the connection when the array `connectedWallets` is empty. Do you know what it could be? 

Thanks

**Comment by Adamj1232** [comment]
@greedythib hmm Im not too sure, could you share a little more context around the code block causing an issue?
We have this working in our demo project [here](https://github.com/blocknative/react-demo) and I'm not seeing an issue when `await connect()` is called triggered and `connectedWallets` is empty

**Comment by greedythib** [comment]
My code is exactly similar to the demo you mentioned. It was working smoothly but with the new updates, the call `await connect()` does not work anymore. I am not sure whether this is the reason but it is only triggering the connect modal when `connectedWallets` is not empty.

**Comment by Adamj1232** [comment]
@greedythib I would need more context around when `await connect()` is called to help

**Comment by Adamj1232** [comment]
@greedythib there is a new version of web3-onboard react out that I owuld recommend updating to and then comparing your code to the react demo code. I am going to close this issue as it is unrelated to the title but we can continue this discussion or I can meet you on discord for chat support which would be the easiest way to communicate

**Comment by enzoferey** [comment]
Hey @Adamj1232, sorry for bringing this back, but we are facing this issue where users that use Opera GX are only being suggested the Opera Wallet and not MetaMask even though they have MetaMask installed on their browser. Is there any way around that ?

**Comment by enzoferey** [comment]
Amazing thanks !
