### ISSUE TITLE
[Bug]: `addNewChain` should specify the blockchain explorer url

### ISSUE THREAD

**Issue by wrap-that-potassium** [blocknative/web3-onboard#948]
### Current Behavior

`addNewChain` is missing the `blockExplorerUrls` setting, so the user has a created chain with **no** blockchain explorer.

### Expected Behavior

`addNewChain` should specify `blockExplorerUrls` setting, coming from enriched `chains` config when initializing `Onboard`.

### Steps To Reproduce

1. Start with a fresh MetaMask installation
2. Switch to a non included chain, like Polygon
3. Polygon network is added in MetaMask with **no** blockchain explorer url

### Onboard Version

2.2.1

### Node Version

16

**Comment by aaronbarnardsound** [comment]
Hey @wrap-that-potassium that is a good suggestion and we can get that added.

**Comment by mahmud-bn** [comment]
@wrap-that-potassium 
Closing this issue since [a solution has been merged ](https://github.com/blocknative/web3-onboard/pull/1021).
