### ISSUE TITLE
[Feature]: use background instead of background-color

### ISSUE THREAD

**Issue by 0xcharchar** [blocknative/web3-onboard#950]
### Is your request related to a problem?

Working on a site that uses a gradient for backgrounds, unable to set a `linear-gradient` in a number of places because variables are attached to `background-color` in onboard-v2

### Feature Description

Replace instances of `background-color` with `background`.

### Alternative Solutions

None that I can think of

### Anything else?

Happy to send a PR if this is something onboard would like to include.

Screenshot where I have edited one of the button attributes to use `background` instead of `background-color` to get a gradient working
![gradient-onboard](https://user-images.githubusercontent.com/87212793/163494126-60612678-e699-41fe-95a5-c3a424c6d9bc.png)

The changed code:
```diff
+ button.relative {
+ --onboard-wallet-button-background-hover: var(--gradient-background-link);
+ }
+
button.svelte-ucnmri:hover {
- background-color: var( --onboard-wallet-button-background-hover, var(--onboard-primary-100, var(--primary-100)) );
+ background: var( --onboard-wallet-button-background-hover, var(--onboard-primary-100, var(--primary-100)) );
}
```

**Comment by mahmud-bn** [comment]
Hi @0xcharchar,
Thanks for creating this. We're working on this and will push a release soon.

**Comment by mahmud-bn** [comment]
@0xcharchar 
Closing this issue has the suggested feature has been merged with [this PR](https://github.com/blocknative/web3-onboard/pull/1074)
