### ISSUE TITLE
[Bug]: Cannot Close and Reopen Onboard modal in angular app

### ISSUE THREAD

**Issue by joharzmn** [blocknative/web3-onboard#954]
### Current Behavior

Using this code to connect MetaMask wallet in web browser in my angular app
```typescript
    const injected = injectedModule()
    const onboard = Onboard({
      wallets: [injected],
      chains: [
        {
          id: '0x1',
          token: 'ETH',
          label: 'Ethereum Mainnet',
          rpcUrl: "https://rpc.ankr.com/eth"
        }
      ],
    });
    const connectedWallets = await onboard.connectWallet();
```

I run this code when the user clicks on connect wallet button from UI. First time it opens the modal with MetaMask wallet and try to connect with meta mask that is correct. But when I close the modal by clicking on X button on modal and try to click on connect wallet again. I am receiving the below error: `Error: At least one chain must be set before attempting to connect a wallet` 
I am not sure why pressing X button is clearing my chains from onboard object.

### Expected Behavior

Modal should open again after pressing on X button without any error.

### Steps To Reproduce

1. Go to StackBiltz: https://stackblitz.com/edit/angular-13-template-redg9y?file=src%2Fapp%2Fapp.component.html
1. Click on Connect Wallet Button
1. Click on X button to close the Modal
1. Then Click on Connect Wallet button again 
1. See Console for error

### Onboard Version

2.2.3

### Node Version

v14.17.4

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: At least one chain must be set before attempting to connect a wallet
Error: At least one chain must be set before attempting to connect a wallet
    at Object.<anonymous> (index.js:1665:15)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1427:1)
    at Object.<anonymous> (asyncToGenerator.js:21:1)
    at Object.connect$1 [as connectWallet] (index.js:1654:16)
    at AuthenticationService.<anonymous> (auth.service.ts:114:44)
    at Generator.next (<anonymous>)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25574:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)
```

### Anything else?

StackBiltz: https://stackblitz.com/edit/angular-13-template-redg9y?file=src%2Fapp%2Fapp.component.html

**Comment by narslan** [comment]
If you instantiate the `OnboardAPI` within `ngOnInit`  and use the resulted (`onboard`) property in the async call
then error will be gone. 
Check: 
https://stackblitz.com/edit/angular-13-template-lrwsd8?file=src%2Fapp%2Fapp.component.ts

**Comment by joharzmn** [comment]
@narslan  The issue is indeed fixed. But I don't understand why we need to use async?

**Comment by narslan** [comment]
Because the API of `web3-onboard` is Promise-based.   
Such an API can be managed with `async`-`await` feature.
For example `onboard.connectWallet()` returns `Promise<WalletState[]>` which needs to be "resolved" with `await`.
Many javascript APIs in ethereum ecosystem, that I'm aware of, are Promise-based. `ethers.js` is another example.
As soon as you make use of Promise-based API's, you bring in the `aysnc` - `await` into your project.
That is a method to deal with asynchronous requests (a http request waiting for server response, a modal window waiting  to be closed...).
Angular however, manages asynchronous calls through Observable. 
That is  why we rarely see Promises in Angular.
You can work with Promises in your Angular without any drawback, even though it feels uncomfortable.

**Comment by dmatora** [comment]
I'm calling `const wallets = await onboard.connectWallet()` from async functions but still getting `Error: At least one chain must be set before attempting to connect a wallet` on 99 of 100 attempts, but on very few occasions (when making changes to React code) I get the popup
