### ISSUE TITLE
[Feature]: Web3Auth Support (Torus2.0)

### ISSUE THREAD

**Issue by jadbox** [blocknative/web3-onboard#955]
### Is your request related to a problem?

The next release of Torus is now called Web3Auth. The API is similar, but there are differences. 

Key improvements:
- Signing and transactions shouldn't require signing anymore

Overview:
https://docs.web3auth.io/get-started/quickstart

Example of Web3Auth integration that works on any domain (this should be the target implementation):
https://gist.github.com/himanshuchawla009/aa065b1ffbee77337488a27f2583202e

I'd recommend forking the Torus Onboardjs plugin and rewrite it using the example above.

**Comment by mahmud-bn** [comment]
Hi @jadbox 
Closing this issue has this has your suggested [feature has been integrated.](https://github.com/blocknative/web3-onboard/pull/1056)
