### ISSUE TITLE
[Bug]: Webpack 5 Unsupported (Buffer)

### ISSUE THREAD

**Issue by kyokosdream** [blocknative/web3-onboard#957]
### Current Behavior

Trying to connect using several of the supported wallets (including Coinbase Wallet), leads to the following error:

`QRCode.js:28 Uncaught ReferenceError: Buffer is not defined`

The error is in the QR code generations:
`const base64 = Buffer.from(qrcode.svg(), "utf8").toString("base64");` 

and again here:
`var buf = Buffer.from(arr.buffer)` as part of `typedarrayToBuffer`

I understand why this error is occurring, it is a result of the breaking changes introduced by Webpack 5 polyfills. But I do not intend to downgrade my code, and the latest versions of create-react-app use Webpack 5. 

What is the effective solution to this problem and how can dependency on Buffer be removed so that we can move forward with integration with web3-onboard?

### Expected Behavior

Should display QR code for Coinbase Wallet. Should allow connection to WalletConnect. 

### Steps To Reproduce

Follow the integration guide here:

https://docs.cloud.coinbase.com/wallet-sdk/docs/web3-onboard

### Onboard Version

@web3-onboard/core@2.2.3

### Node Version

v16.14.2

### What browsers are you seeing the problem on?

Chrome

**Comment by aaronbarnardsound** [comment]
See the [build environment docs](https://docs.blocknative.com/onboard/core#webpack-5) for polyfilling node builtins for webpack 5

**Comment by narslan** [comment]
Hey, @kyokosdream,
I had a similar problem with my angular project, see #945 .
I solved it through decorating global environment  with  the missing objects.
I'm no React user, so I don't have a solid solution for you. But those lines I put together 
might give you some clue.
```ts
global.Buffer = require("buffer").Buffer;
global.process = require("process");
```

**Comment by kyokosdream** [comment]
Thanks for the community support on this but I ended up using Web3modal in combination with craco (create react app configuration override). I will investigate returning to web3-onboard through the solutions discussed.

**Comment by mahmud-bn** [comment]
HI @kyokosdream 

We hope you would consider using web3-onboard. We've provided additional React 18 and webpack 5 support which you can find here: https://docs.blocknative.com/onboard/core#webpack-5
