### ISSUE TITLE
[Bug]: "custom derivation path" does not allow me to set a custom derivation path with Ledger

### ISSUE THREAD

**Issue by john-light** [blocknative/web3-onboard#969]
### Current Behavior

When I try to connect a hardware wallet (Ledger) using a custom derivation path (specifically, the [RSK](https://developers.rsk.co/rsk/architecture/account-based/) derivation path), I am shown an error in Blocknative web3-onboard:

> m/44’/137’/0’/0 is not a valid derivation path.

I encountered this when trying to connect using [Gnosis Safe](https://gnosis-safe.io/app/welcome).

### Expected Behavior

I expect to be able to connect my Ledger hardware wallet using a custom derivation path, as the entry field "Custom derivation path" suggests I should be able to.

### Steps To Reproduce

1. Connect Ledger hardware wallet
2. Select "custom derivation path"
3. Enter `m/44’/137’/0’/0` as the path
4. See error `m/44’/137’/0’/0 is not a valid derivation path.`

### Onboard Version

whatever Gnosis Safe is using

### Node Version

n/a

### Anything else?

![blocknative_dpath](https://user-images.githubusercontent.com/9424721/165565011-3d478d59-0f7b-40a7-a230-48e7132ae78e.png)

**Comment by Adamj1232** [comment]
@john-light we will have a fix going up for this in web3-onboard(onboard v2) today and will try to get a release for Onboard v1 together shortly.
Gnosis should update to the latest version of Onboard as V1 has been moved to maintenance mode and active development is no longer occurring

**Comment by Adamj1232** [comment]
PRs up for this fix V1 - #974 & V2 - #972

**Comment by john-light** [comment]
@Adamj1232 appreciate the fix for Trezor in https://github.com/blocknative/web3-onboard/pull/974 however Ledger is not working on v1 either. I have gotten in touch with the Gnosis Safe team to update to v2 but until that happens having a fix for Ledger on v1 would be really helpful 🙏  Is there anything holding back a fix for Ledger on v1?

**Comment by aaronbarnardsound** [comment]
@john-light we are going to get this fixed in V1 next week, will drop updates here.

**Comment by Adamj1232** [comment]
Closing as this issue has been fixed in V1. Thank you for reporting this issue!
