### ISSUE TITLE
[Bug]:  issue deriving Ethereum Ledger Live path on Trezor

### ISSUE THREAD

**Issue by john-light** [blocknative/web3-onboard#970]
### Current Behavior

When I try to enter the Ethereum Ledger Live derivation path as a custom derivation path for Trezor, specifically, I am shown an error message:

> Error: There was a problem deriving an address from path m/44'/60'.

I encountered this issue when using [Gnosis Safe](https://gnosis-safe.io/app/welcome), which uses Blocknative web3-onboard, on Brave browser. I have no browser extensions or settings that might be interfering with this feature.

### Expected Behavior

I expect to be able to enter and use the Ethereum Ledger Live dpath with my Trezor hardware wallet.

### Steps To Reproduce

1. Connect with Trezor on https://gnosis-safe.io/app/welcome while Trezor Bridge is running locally
2. Select "custom derivation path"
3. Enter Ethereum Ledger Live dpath `m/44'/60'`
4. connect.trezor.io tab will open, then close, and web3-onboard module will show error message: `Error: There was a problem deriving an address from path m/44'/60'.`
![blocknative_ledgerlive](https://user-images.githubusercontent.com/9424721/165566602-355b5c0e-8df4-4289-88aa-21ca495482ad.png)

### Onboard Version

whatever Gnosis Safe is using

### Node Version

n/a

**Comment by Adamj1232** [comment]
@john-light it looks like you are using onboard-v1. Have you considered checking out our v2-web3-onboard which has current development support, enhanced UX and can be much lighter(depending on developer/dapp setting)?
https://www.npmjs.com/package/@web3-onboard/core

**Comment by john-light** [comment]
@Adamj1232 does it fix this issue? this would be a request for Gnosis Safe. I can open an issue in their repo if updating to v2 would fix this.

**Comment by john-light** [comment]
Thanks @Adamj1232 for the quick fix on this issue and #969. I have created an issue in the Safe repo requesting that they update:
https://github.com/gnosis/safe/issues/536
