### ISSUE TITLE
[Bug]: eip-712 peer dependency types are missing

### ISSUE THREAD

**Issue by enzoferey** [blocknative/web3-onboard#971]
### Current Behavior

When using any package that uses `web3-onboard/common` in a TypeScript project, if I run `tsc --noEmit` with `skipLibCheck: false` I'm getting:

```
node_modules/@web3-onboard/common/dist/types.d.ts:4:51 - error TS2307: Cannot find module 'eip-712' or its corresponding type declarations.

export type { TypedData as EIP712TypedData } from 'eip-712';
```

### Expected Behavior

I expect the packages to bundle their internal required types.

### Steps To Reproduce

1. Install any package that uses `web3-onboard/common`.
2. Set `skipLibCheck: false` in your `tsconfig.json` file.
3. Run `tsc --noEmit`.

### Onboard Version

v2

### Node Version

v16.14.0

### Relevant log output

```shell
node_modules/@web3-onboard/common/dist/types.d.ts:4:51 - error TS2307: Cannot find module 'eip-712' or its corresponding type declarations.

export type { TypedData as EIP712TypedData } from 'eip-712';
```

**Comment by taylorjdawson** [comment]
@enzoferey are you still experiencing this issue I think it is fixed now at least on my end.

**Comment by enzoferey** [comment]
Hey @taylorjdawson ! Yes, it still happens when `skipLibCheck: false`. I just noticed I forgot to mention it, sorry for that, I'm updating the issue description.

**Comment by taylorjdawson** [comment]
@enzoferey Cool! If you want to PR to fix that would be great! Otherwise we'll get to this later as it's a lower priority for now 👍🏾

**Comment by Adamj1232** [comment]
@enzoferey is the problem persisting? I believe it should have been fixed in the latest package versions. Thanks!

**Comment by enzoferey** [comment]
Hey @Adamj1232 unfortunately I'm no longer working on this project, so I cannot double check. If you believe it should be solved now please go ahead and just close the issue, I will reopen if it bites me again in the future 😄
