### ISSUE TITLE
[Bug]: Modal doesn't lock scrolling

### ISSUE THREAD

**Issue by arne-z** [blocknative/web3-onboard#973]
### Current Behavior

The modal and the background for it are rendered in front of the page with the styles:
```
section.svelte-lkspmm {
    position: absolute;
    top: 0;
    left: 0;
    pointer-events: none;
    z-index: var(--onboard-modal-z-index, var(--modal-z-index));
}
```
which causes them to show up at the top of the page. 
If the user scrolls down or is already scrolled down on the page the modal and its background will not cover the part of the page below where the viewport would be with the page scrolled up.

### Expected Behavior

The modal and background should render with `position: fixed` so the user can't scroll past it, as described originally in https://github.com/blocknative/web3-onboard/issues/246

### Steps To Reproduce

Environment:
Next.js app using tailwind for styling, the only styling that should affect the modal is:
```
:root {
  --onboard-modal-z-index: 50;
}
```
to make sure it renders over the navbar.
On a page that is longer than the viewport, where the user can scroll down.
1. Call `connect` imported from:
```
import { useConnectWallet, useSetChain, useWallets } from "@web3-onboard/react";
const [{ connecting, wallet }, connect, disconnect] = useConnectWallet();
```
2. When the modal pops up, scroll down, past the area the modal covers.

### Onboard Version

2.0.6

### Node Version

16.13.1.

### What browsers are you seeing the problem on?

Chrome

**Comment by Adamj1232** [comment]
@arne-z a PR has been created [here](https://github.com/blocknative/web3-onboard/pull/976) to address this. Please review and respond here with any concerns

**Comment by Adamj1232** [comment]
Updated in latest release
