### ISSUE TITLE
[Bug]: WalletConnect websocket issue

### ISSUE THREAD

**Issue by samuveth** [blocknative/web3-onboard#978]
### Current Behavior

When I choose WalletConnect I see this message and no error in the console. `ws does not work in the browser. Browser clients must use the native WebSocket object`
<img width="790" alt="image" src="https://user-images.githubusercontent.com/51686767/166219386-c11bccd2-7cf2-49b4-9115-7a2dfcc62ccb.png">

### Expected Behavior

Can connect

### Onboard Version

@vueuse/core ^8.3.1

### Node Version

v14.19.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

### Anything else?

"vite": "^2.9.6"
"vue": "^3.2.25"

**Comment by taylorjdawson** [comment]
@samuveth which browser are you using?

**Comment by samuveth** [comment]
This was an issue with Vite. You guys need to update the docs on Vite 🙁

**Comment by mahmud-bn** [comment]
@samuveth 
As mentioned in your other Issue #979, documentation for the Vite.js config has been updated and WalletConnect works fine for vite.js setups.
