### ISSUE TITLE
[Bug]: Unknown address auto-connected on xdai using Gnosis Safe

### ISSUE THREAD

**Issue by philippe-git** [blocknative/web3-onboard#980]
### Current Behavior

Loading https://xdai.curve.fi through a Gnosis Safe auto-connects an unknown address. Reconnecting manually by triggering the Onboard modal again and picking "Gnosis Safe" connects the right Safe address.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/2307365/166968702-6c6ef871-542a-4731-abf5-097f45b4428e.png">

### Expected Behavior

Loading https://xdai.curve.fi  through a Gnosis Safe should auto-connect to the Safe's address; note: on curve.fi's onboard integration, on first load there won't be any auto-connecting, users do need to pick "gnosis safe" in the Onboard modal; this is different behavior from the described "current behavior" which auto-selects a seemingly random address

### Onboard Version

@web3-onboard/core@2.2.3, @web3-onboard/gnosis@2.0.1

### Node Version

v12.22.7

### Anything else?

I haven't had the ability to dive deeper into this issue to make sure it's 100% one of those packages exhibiting an unexpected behavior. However, loading Curve.fi sites like curve.fi (Ethereum) or polygon.curve.fi (Polygon) using Gnosis Safe doesn't exhibit the behavior described in "current behavior": they behave like "expected behavior": this alone would seem to point to @web3-onboard/gnosis

**Comment by Adamj1232** [comment]
@philippe-git is this issue still happening?

**Comment by ejc8** [comment]
@philippe-git closing this - if this issue re-occurs feel free to reach back out
