### ISSUE TITLE
[Bug]: AccountCenter widget causes state updates to trigger after every click

### ISSUE THREAD

**Issue by wonderbeel** [blocknative/web3-onboard#985]
### Current Behavior

If I enable the AccountCenter widget it seems that a global listener is attached to every click event in the page that causes the onboard state to update after every user action; if I disable the AccountCenter this doesn't happen.

### Expected Behavior

Enabling AccountCenter shouldn't cause every click event to trigger a state update.

### Steps To Reproduce

1. Add a `console.log` in the state update callback function
2. Open an inspector
3. Click anywhere
4. See that log after every click

### Onboard Version

2.2.7

### Node Version

16.14.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

Reproduction repo: https://github.com/wonderbeel/onboard-subscription-bug

**Comment by taylorjdawson** [comment]
@wonderbeel Working on a fix!

**Comment by taylorjdawson** [comment]
Fixed in #989
