### ISSUE TITLE
[Feature]: Web3 Onboarding - Allow users to only connect one wallet

### ISSUE THREAD

**Issue by ajaypillay** [blocknative/web3-onboard#990]
### Is your request related to a problem?

https://docs.blocknative.com/onboard/react-hooks

It doesn't seem that there's a way to restrict users to only connecting one wallet.

### Feature Description

Allow users to connect exactly 1 wallet.

**Comment by cmalex23** [comment]
Of course there is. You need to remove the `useWallets()` hook and implement your logic to not show the connect button once a wallet is connected.
You will use the `wallet` member from `useConnectWallet()` as the only wallet instance and check if that is defined (connected) or not.
