### ISSUE TITLE
[Bug]: getTransactionReceipt throws with undefined error for hardware wallets

### ISSUE THREAD

**Issue by danielcrt** [blocknative/web3-onboard#994]
### Current Behavior

When I am connected to a hardware wallet (Ledger) and I try to retrieve the transaction receipt using ethers library, an TypeError is thrown.
Example:
`try {
   const populatedTransaction = contract.populateTransaction.method();
    const tx = await signer.populateTransaction(await populatedTxn);
    const response: TransactionResponse = signer.sendTransaction(tx);
    const receipt: ethers.providers.TransactionReceipt = await tx.wait();
} catch(error: any) {
     console.error(error);
}`

<img width="537" alt="Screenshot 2022-05-10 at 13 24 35" src="https://user-images.githubusercontent.com/43569886/167616978-2aae24a5-5fad-45c6-bbf3-7235029fda09.png">

Everything is working fine when connected with Metamask.

### Expected Behavior

Return TransactionReceipt without errors.

### Steps To Reproduce

1. Connect to a hardware wallet (e.g. Ledger)
2. Retrieve a contract populated transaction
3. call signer.populateTransaction
4. call signer.sendTransaction
5. wait for transaction to be mined.

### Onboard Version

v2

### Node Version

14.17.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'message')
at checkError (json-rpc-provider.ts:71:1)
at Web3Provider, <anonymous> (json-rpc-provider.ts:596:1)
at Generator. throw (<anonymous>)
at rejected (json-rpc-provider.ts:2:1)
at nrWrapper ((index) :28:29077)
```

**Comment by taylorjdawson** [comment]
@danielcrt Thanks for finding this I'll take a look this week 👍🏾

**Comment by taylorjdawson** [comment]
Fixed in [latest release](https://github.com/blocknative/web3-onboard/releases/tag/web3-onboard%2F2.2.0)! 🙌🏾
