### ISSUE TITLE
[Bug]:  Gnosis Safe SafeAppProvider is not a constructor error when connecting

### ISSUE THREAD

**Issue by tokensex** [blocknative/web3-onboard#997]
### Current Behavior

When trying to connect with gnosis wallet, I get the error `SafeAppProvider is not a constructor`.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/104802160/167787050-b1155b28-47a5-4301-acbf-bd7e87f4c38b.png">

### Expected Behavior

Wallet connects

### Steps To Reproduce

1. Setup your supported wallets
```
...

import gnosisModule from "@web3-onboard/gnosis";
const gnosis = gnosisModule();
const onboard = Onboard({
    wallets: [
      injected,
      walletConnect,
      gnosis,
      ledger,
...

```
2. Login: https://gnosis-safe.io/app/
3. Add app
4. Try to connect wallet

### Onboard Version

core-v2.2.6

### Node Version

v16.14.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No console logs
```

**Comment by Adamj1232** [comment]
@tokensex are you still experiencing this issue with the latest web3-onboard packages?

**Comment by taylorjdawson** [comment]
@tokensex  Friendly ping on this :) And if this still is an issue please provide your build configuration as this is usually caused by improperly configured build environments, thanks!

**Comment by Adamj1232** [comment]
I am going to close this issue as it is stale and unreproducible. @tokensex if the issue is still a problem please feel free to get back to us with the requested information above and reopen. Cheers and thanks again!

**Comment by gabevandesande** [comment]
I am experiencing this issue currently, has there been a resolution here?

Here is my build configuration:
`  build: {
    sourcemap: mode === 'development',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        forbidden: resolve(__dirname, 'forbidden.html'),
      },
      external: ['@web3-onboard/*'],
      plugins: [
        nodePolyfills({ include: ['crypto', 'http', 'buffer'] }),
        //, inject({ Buffer: ['Buffer', 'Buffer'] })
      ],
      output: {
        manualChunks: {
          react: ['react', 'react-dom', 'react-router-dom'],
          chartjs: ['react-chartjs-2'],
          'web3-onboard': ['@web3-onboard/core', '@web3-onboard/common', '@web3-onboard/injected-wallets'],
          ui: ['@chakra-ui/react'],
        },
      },
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },`
