### ISSUE TITLE
[Bug]: Walletconnect does not work on chrome browser

### ISSUE THREAD

**Issue by akim-bow** [blocknative/web3-onboard#999]
### Current Behavior

I use this config to init onboard. 
On my site i have button "Connect wallet" which initiate connection.
On desktop browsers it works fine. But chrome mobile browser doesn't work as expected. I don't know about other mobile browsers.
This is what i see from the phone perspective.
![image](https://user-images.githubusercontent.com/59872966/168086177-55bb18cd-330b-441d-babd-c93cafa4568f.png)
Mobile chrome browser version is 101.0.4951.41

### Steps To Reproduce

const web3Onboard = Web3Onboard({
    wallets: [
        injectedModule(),
        coinbaseWalletModule({ darkMode: true }),
        walletConnectModule({
            bridge: 'https://bridge.walletconnect.org',
            qrcodeModalOptions: {
                mobileLinks: ['rainbow', 'metamask', 'argent', 'trust', 'imtoken', 'pillar'],
            },
        }),
    ],
    chains: [
        {
            id: '0x38',
            token: 'BNB',
            label: 'BSC Mainnet',
            rpcUrl: 'https://bsc-dataseed.binance.org/',
        },
        {
            id: '0x61',
            token: 'BNB',
            label: 'BSC Testnet',
            rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
        },
    ],
    accountCenter: {
        desktop: { enabled: false },
    },
})

### Onboard Version

2.2.7

### Node Version

16.14.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

**Comment by LeNei** [comment]
Any progress on this? Im facing the same issue with mobile chrome browsers.

**Comment by LeNei** [comment]
@taylorjdawson thanks for the update. Got a temporary fix working locally and will look forward to the next release :)

**Comment by taylorjdawson** [comment]
@LeNei @akim-bow Can you both test again on the [reactdemo](https://reactdemo.blocknative.com/). I just tried it and it worked fine! `@web3-onboard/react` v2.11.8
See [react-demo repo](https://github.com/blocknative/react-demo) for example on how to configure.

**Comment by taylorjdawson** [comment]
@LeNei @akim-bow Friendly ping on this :)

**Comment by LeNei** [comment]
@taylorjdawson unfortunately for me it still crashes the entire site. Im currently using Nextjs 12 with 
```
    "@web3-onboard/injected-wallets": "^2.0.10",
    "@web3-onboard/react": "^2.2.0",
    "@web3-onboard/walletconnect": "^2.0.3",
```

**Comment by taylorjdawson** [comment]
@LeNei but does it crash only on Chrome Mobile? And if it crashes could you provide error messages, your web3-onboard config settings, and a way to reproduce this?

**Comment by taylorjdawson** [comment]
@LeNei @akim-bow Friendly ping on this :)

**Comment by LeNei** [comment]
@taylorjdawson sorry for the late reply, I was on vacation. With the updated versions everything seems to be running now. Great work :)
